var hskLevel5Sentences = [
    {
        "id": 3673,
        "character": "丑",
        "character_pinyin": "chǒu",
        "eng": "ugly; disgraceful",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "以前，当别人说她丑的时候，她会很敏感，但是经过长时间的悲伤，她现在已经变得冷漠了。",
        "compound_pinyin": "Yǐqián, dāng biérén shuō tā chǒu de shíhòu, tā huì hěn mǐngǎn, dànshì jīngguò cháng shíjiān de bēishāng, tā xiànzài yǐjīng biàn dé lěngmòle.",
        "compound_definition": "In the past, she would be very sensitive when others said she was ugly, but after a long period of sadness, she has now become indifferent.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3675,
        "character": "乏",
        "character_pinyin": "fá",
        "eng": "tired; weary",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我这几天工作很乏，想休息一下。",
        "compound_pinyin": "Wǒ zhè jǐ tiān gōngzuò hěn fá, xiǎng xiūxí yīxià.",
        "compound_definition": "I've been very tired from work these past few days and want to rest a bit.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3685,
        "character": "俱",
        "character_pinyin": "jù",
        "eng": "all; together",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我们班的同学都俱来参加了这个活动。",
        "compound_pinyin": "Wǒmen bān de tóngxué dōu jù lái cānjiāle zhège huódòng.",
        "compound_definition": "All the students in our class came together to participate in this event.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3691,
        "character": "傻",
        "character_pinyin": "shǎ",
        "eng": "silly; foolish",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他做了个傻事，让大家都笑了。",
        "compound_pinyin": "Tā zuòle gè shǎ shì, ràng dàjiā dōu xiào le.",
        "compound_definition": "He did something silly that made everyone laugh.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3696,
        "character": "冻",
        "character_pinyin": "dòng",
        "eng": "to freeze; frozen",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "外面的天气太冷，水已经冻住了。",
        "compound_pinyin": "Wàimiàn de tiānqì tài lěng, shuǐ yǐjīng dòng zhùle.",
        "compound_definition": "The weather outside is too cold; the water has already frozen.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3704,
        "character": "勤",
        "character_pinyin": "qín",
        "eng": "diligent; hardworking",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她是一个勤奋的学生，每天都很努力学习。",
        "compound_pinyin": "Tā shì yīgè qínfèn de xuéshēng, měitiān dōu hěn nǔlì xuéxí.",
        "compound_definition": "She is a diligent student and studies hard every day.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3710,
        "character": "厉",
        "character_pinyin": "lì",
        "eng": "severe; strict",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的父母对他的学习要求很厉。",
        "compound_pinyin": "Tā de fùmǔ duì tā de xuéxí yāoqiú hěn lì.",
        "compound_definition": "His parents have very strict expectations for his studies.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3721,
        "character": "唯",
        "character_pinyin": "wéi",
        "eng": "only; just",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "唯有努力才能获得成功，这是我一直相信的。",
        "compound_pinyin": "Wéi yǒu nǔlì cáinéng huòdé chénggōng, zhè shì wǒ yīzhí xiāngxìn de.",
        "compound_definition": "Only through hard work can one achieve success; this is what I’ve always believed.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3723,
        "character": "坦",
        "character_pinyin": "tǎn",
        "eng": "flat; smooth",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这条路很坦，开车的时候很舒服。",
        "compound_pinyin": "Zhè tiáo lù hěn tǎn, kāichē de shíhòu hěn shūfú.",
        "compound_definition": "This road is very flat, making it comfortable to drive on.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3739,
        "character": "尤",
        "character_pinyin": "yóu",
        "eng": "especially; particularly",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "这个地方的风景尤为迷人，吸引了很多游客。",
        "compound_pinyin": "Zhège dìfāng de fēngjǐng yóuwéi mírén, xīyǐnle hěn duō yóukè.",
        "compound_definition": "The scenery in this place is particularly charming, attracting many visitors.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3745,
        "character": "幽",
        "character_pinyin": "yōu",
        "eng": "quiet; secluded",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个公园的角落非常幽静，适合读书和思考。",
        "compound_pinyin": "Zhège gōngyuán de jiǎoluò fēicháng yōujìng, shìhé dúshū hé sīkǎo.",
        "compound_definition": "This corner of the park is very quiet, perfect for reading and thinking.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3758,
        "character": "悄",
        "character_pinyin": "qiāo",
        "eng": "quietly; softly",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "尽管这个聪明的女孩被禁止进入房间，但她还是悄悄地降了进去。",
        "compound_pinyin": "Jǐnguǎn zhège cōngmíng de nǚhái bèi jìnzhǐ jìnrù fángjiān, dàn tā háishì qiāoqiāo de jiàngle jìnqù.",
        "compound_definition": "Although the clever girl was forbidden to enter the room, she quietly descended inside.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3761,
        "character": "悲",
        "character_pinyin": "bēi",
        "eng": "sorrow; sadness",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的故事充满了悲伤，让人心痛。",
        "compound_pinyin": "Tā de gùshì chōngmǎnle bēishāng, ràng rén xīntòng.",
        "compound_definition": "His story is filled with sadness, causing heartache.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3765,
        "character": "慌",
        "character_pinyin": "huāng",
        "eng": "to panic; hurried",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他慌忙赶到机场，生怕错过航班。",
        "compound_pinyin": "Tā huāngmáng gǎn dào jīchǎng, shēngpà cuòguò hángbān.",
        "compound_definition": "He hurried to the airport, afraid of missing his flight.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3801,
        "character": "敏",
        "character_pinyin": "mǐn",
        "eng": "sensitive; quick",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她对别人的情感非常敏感，总是能察觉到变化。",
        "compound_pinyin": "Tā duì biérén de qínggǎn fēicháng mǐngǎn, zǒng shì néng chájúedào biànhuà.",
        "compound_definition": "She is very sensitive to others' emotions and can always sense changes.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3804,
        "character": "斜",
        "character_pinyin": "xié",
        "eng": "slanting; oblique",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "虽然地面是平坦，但是桌子却稍微斜了。",
        "compound_pinyin": "Suīrán dìmiàn píngtǎn, dànshì zhuōzi què shāowéi xiéle.",
        "compound_definition": "Although the ground was flat, the table was slightly tilted.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3806,
        "character": "暂",
        "character_pinyin": "zàn",
        "eng": "temporarily; for the time being",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "由于天气原因，活动暂时取消。",
        "compound_pinyin": "Yóuyú tiānqì yuányīn, huódòng zànshí qǔxiāo.",
        "compound_definition": "The event has been temporarily canceled due to weather conditions.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3808,
        "character": "朗",
        "character_pinyin": "lǎng",
        "eng": "bright; clear",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的声音朗朗上口，让人印象深刻。",
        "compound_pinyin": "Tā de shēngyīn lǎnglǎng shàngkǒu, ràng rén yìnxiàng shēnkè.",
        "compound_definition": "His voice is clear and catchy, leaving a deep impression.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3809,
        "character": "朵",
        "character_pinyin": "duǒ",
        "eng": "measure word for flowers; clusters",
        "hsk_level": 5,
        "part_of_speech": "measure word/noun",
        "compound_cantonese": "",
        "compound": "这朵软的花象征着悲伤。我们可以冷冻它来保存它。",
        "compound_pinyin": "Zhè duǒ ruǎn de huā xiàngzhēngzhe bēishāng. Wǒmen kěyǐ lěngdòng tā lái bǎocún tā.",
        "compound_definition": "This soft flower symbolizes sadness. We can freeze it to preserve it.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3839,
        "character": "漠",
        "character_pinyin": "mò",
        "eng": "desert; indifferent",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的态度漠不关心，让人感到失望。",
        "compound_pinyin": "Tā de tàidù mò bù guānxīn, ràng rén gǎndào shīwàng.",
        "compound_definition": "His indifferent attitude disappointed people.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3843,
        "character": "烂",
        "character_pinyin": "làn",
        "eng": "rotten; broken",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个苹果已经烂了，不能再吃了。",
        "compound_pinyin": "Zhège píngguǒ yǐjīng lànle, bù néng zài chīle.",
        "compound_definition": "This apple is already rotten and can't be eaten anymore.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3849,
        "character": "狂",
        "character_pinyin": "kuáng",
        "eng": "crazy; mad",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他对篮球狂热，几乎每天都去打球。",
        "compound_pinyin": "Tā duì lánqiú kuángrè, jīhū měitiān dōu qù dǎqiú.",
        "compound_definition": "He is crazy about basketball and plays almost every day.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3859,
        "character": "疯",
        "character_pinyin": "fēng",
        "eng": "crazy; insane",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个疯子向一家计算机硬件商店投了一些盘子。",
        "compound_pinyin": "Zhège fēngzi xiàng yījiā jìsuànjī yìngjiàn shāngdiàn tóule yīxiē pánzi.",
        "compound_definition": "This lunatic threw some plates at a computer hardware store.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3860,
        "character": "瘦",
        "character_pinyin": "shòu",
        "eng": "thin; skinny",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她最近瘦了很多，朋友们都很关心她的健康。",
        "compound_pinyin": "Tā zuìjìn shòule hěn duō, péngyǒumen dōu hěn guānxīn tā de jiànkāng.",
        "compound_definition": "She has lost a lot of weight recently, and her friends are concerned about her health.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3867,
        "character": "硕",
        "character_pinyin": "shuò",
        "eng": "large; great",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他在大学里获得硕士学位，开始了新的人生阶段。",
        "compound_pinyin": "Tā zài dàxué lǐ huòdé shuòshì xuéwèi, kāishǐle xīn de rénshēng jiēduàn.",
        "compound_definition": "He earned a master's degree at university and began a new phase of life.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3868,
        "character": "硬",
        "character_pinyin": "yìng",
        "eng": "hard; tough",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个木头非常硬，制作家具非常合适。",
        "compound_pinyin": "Zhège mùtou fēicháng yìng, zhìzuò jiājù fēicháng héshì.",
        "compound_definition": "This wood is very hard, making it suitable for furniture.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3871,
        "character": "私",
        "character_pinyin": "sī",
        "eng": "private; personal",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "由于自己的身体又臭又丑，她更喜欢私下脱衣服。",
        "compound_pinyin": "Yóuyú zìjǐ de shēntǐ yòu chòu yòu chǒu, tā gèng xǐhuān sīxià tuō yīfú.",
        "compound_definition": "Since her body was smelly and ugly, she preferred to undress in private.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3873,
        "character": "稍",
        "character_pinyin": "shāo",
        "eng": "slightly; a little",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "她对自己的瘦弱稍微敏感。她想通过锻炼让自己变得更胖一点。",
        "compound_pinyin": "Tā duì zìjǐ de shòuruò shāowéi mǐngǎn. Tā xiǎng tōngguò duànliàn ràng zìjǐ biàn dé gèng pàng yīdiǎn.",
        "compound_definition": "She is a little sensitive about her thinness. She wants to make herself a little fatter through exercise.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3883,
        "character": "紫",
        "character_pinyin": "zǐ",
        "eng": "purple",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她慌乱之中选择戴上斜戴的紫色帽子，却被一位帅气的律师表示赞赏。",
        "compound_pinyin": "Tā huāngluàn zhòng xuǎnzé dài de zǐsè màozi, què bèi yī wèi shuàiqì lǜshī de zànshǎng.",
        "compound_definition": "The purple hat she chose to wear in a panic was praised by a handsome lawyer.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3884,
        "character": "繁",
        "character_pinyin": "fán",
        "eng": "complicated;繁荣",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个城市的夜景繁华，吸引了很多游客。",
        "compound_pinyin": "Zhège chéngshì de yèjǐng fánhuá, xīyǐnle hěn duō yóukè.",
        "compound_definition": "The night view of this city is vibrant and attracts many tourists.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3892,
        "character": "聪",
        "character_pinyin": "cōng",
        "eng": "clever; intelligent",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她是一个聪明的学生，总是能很快理解老师的讲解。",
        "compound_pinyin": "Tā shì yīgè cōngmíng de xuéshēng, zǒng shì néng hěn kuài lǐjiě lǎoshī de jiǎngjiě.",
        "compound_definition": "She is a clever student who always understands the teacher's explanations quickly.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3903,
        "character": "脆",
        "character_pinyin": "cuì",
        "eng": "crispy; fragile",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "由于我们的厨房暂时无法使用，制作脆皮鸡将会很艰巨。",
        "compound_pinyin": "Yóuyú wǒmen de chúfáng zhànshí wúfǎ shǐyòng, zhìzuò cuì pí jī jiāng huì hěn jiānjù.",
        "compound_definition": "Since our kitchen is temporarily unavailable, making crispy chicken is going to be a daunting task.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3905,
        "character": "臭",
        "character_pinyin": "chòu",
        "eng": "smelly; stinky",
        "hsk_level": 5,
        "part_of_speech": "adjective/verb",
        "compound_cantonese": "",
        "compound": "这个垃圾散发着臭味，必须马上清理。",
        "compound_pinyin": "Zhège lājī sànfāzhe chòuwèi, bìxū mǎshàng qīnglǐ.",
        "compound_definition": "This garbage gives off a bad smell and must be cleaned up immediately.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3907,
        "character": "艰",
        "character_pinyin": "jiān",
        "eng": "difficult; hard",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这段旅程非常艰难，但她依然坚持完成。",
        "compound_pinyin": "Zhè duàn lǚchéng fēicháng jiānnán, dàn tā yīrán jiānchí wánchéng.",
        "compound_definition": "This journey was very difficult, but she persevered to complete it.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3908,
        "character": "艳",
        "character_pinyin": "yàn",
        "eng": "gorgeous; beautiful",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "让我们来赞赏一下这只色彩鲜艳的鸟。",
        "compound_pinyin": "Ràng wǒmen lái zànshǎng yīxià zhè zhǐ sècǎi xiānyàn de niǎo.",
        "compound_definition": "Let's admire this colorful bird.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3914,
        "character": "虚",
        "character_pinyin": "xū",
        "eng": "empty; false",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的话听起来很虚，让人难以相信。",
        "compound_pinyin": "Tā de huà tīng qǐlái hěn xū, ràng rén nányǐ xiāngxìn.",
        "compound_definition": "His words sound empty and hard to believe.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3921,
        "character": "详",
        "character_pinyin": "xiáng",
        "eng": "detailed; elaborate",
        "hsk_level": 5,
        "part_of_speech": "adjective/verb",
        "compound_cantonese": "",
        "compound": "她对项目的计划做了详尽的说明，确保大家理解。",
        "compound_pinyin": "Tā duì xiàngmù de jìhuà zuòle xiángjìn de shuōmíng, quèbǎo dàjiā lǐjiě.",
        "compound_definition": "She provided a detailed explanation of the project plan to ensure everyone understood.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3923,
        "character": "豪",
        "character_pinyin": "háo",
        "eng": "hero; bold",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "征服之路十分艰辛，所以他自豪地抽着卷烟庆祝自己的胜利。",
        "compound_pinyin": "Zhēngfú zhī lù shífēn jiānxīn, suǒyǐ tā zìháo de chōuzhe juǎnyān qìngzhù zìjǐ de shènglì.",
        "compound_definition": "The road to conquest had been difficult, so he proudly celebrated his victory by smoking a cigarette.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3924,
        "character": "豫",
        "character_pinyin": "yù",
        "eng": "to be prepared; Henan province",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他们在豫省的旅行中，体验了独特的地方文化。",
        "compound_pinyin": "Tāmen zài Yùshěng de lǚxíng zhōng, tǐyànle dútè de dìfāng wénhuà.",
        "compound_definition": "During their trip to Henan province, they experienced the unique local culture.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3932,
        "character": "软",
        "character_pinyin": "ruǎn",
        "eng": "soft; gentle",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这张沙发非常软，坐上去很舒服。",
        "compound_pinyin": "Zhè zhāng shāfā fēicháng ruǎn, zuò shàngqù hěn shūfú.",
        "compound_definition": "This sofa is very soft and comfortable to sit on.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3936,
        "character": "辛",
        "character_pinyin": "xīn",
        "eng": "bitter; laborious",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他经历了许多辛苦的日子，终于实现了自己的目标。",
        "compound_pinyin": "Tā jīnglìle xǔduō xīnkǔ de rìzi, zhōngyú shíxiànle zìjǐ de mùbiāo.",
        "compound_definition": "He went through many tough days and finally achieved his goals.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3953,
        "character": "闲",
        "character_pinyin": "xián",
        "eng": "idle; free",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "寒山顶虽是休闲的好去处，但登较为艰难。尽管如此，我们还是会频繁去访。",
        "compound_pinyin": "Hánshān dǐng suī shì xiūxián de hǎo qùchù, dàn dēng jiàowéi jiānnán. Jǐnguǎn rúcǐ, wǒmen háishì huì pínfán qù fǎng.",
        "compound_definition": "Although Hanshan Peak is a good place for leisure, it is difficult to climb. Despite this, we still visit it frequently.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3955,
        "character": "雄",
        "character_pinyin": "xióng",
        "eng": "male; heroic",
        "hsk_level": 5,
        "part_of_speech": "adjective/noun",
        "compound_cantonese": "",
        "compound": "消防员爬上梯子救出孩子，这位英雄值得我们赞扬。",
        "compound_pinyin": "Xiāofáng yuán pá shàng tīzi jiùchū háizi, zhè wèi yīngxióng zhídé wǒmen zànyáng.",
        "compound_definition": "The firefighter climbed up the ladder to rescue the child. This hero deserves our praise.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3958,
        "character": "频",
        "character_pinyin": "pín",
        "eng": "frequent; often",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她频繁地去健身房锻炼，保持身体健康。",
        "compound_pinyin": "Tā pínfán de qù jiànshēnfáng duànliàn, bǎochí shēntǐ jiànkāng.",
        "compound_definition": "She frequently goes to the gym to exercise and maintain her health.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3959,
        "character": "颗",
        "character_pinyin": "kē",
        "eng": "measure word for small round objects; grain",
        "hsk_level": 5,
        "part_of_speech": "measure word/noun",
        "compound_cantonese": "",
        "compound": "一个穷而疯狂的人把这颗紫色宝石卖给了我。",
        "compound_pinyin": "Yīgè qióng ér fēngkuáng de rén bǎ zhè kē zǐsè bǎoshí mài gěile wǒ.",
        "compound_definition": "A poor and crazy man sold me this purple gem.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3680,
        "character": "仔",
        "character_pinyin": "zǎi",
        "eng": "young; child",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他有一个可爱的仔仔，刚刚学会走路。",
        "compound_pinyin": "Tā yǒu yīgè kě'ài de zǎizǎi, gānggāng xuéhuì zǒulù.",
        "compound_definition": "He has a cute little boy who just learned to walk.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3687,
        "character": "偶",
        "character_pinyin": "ǒu",
        "eng": "couple; to meet by chance",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "我偶然遇见了一个老朋友，真是惊喜。",
        "compound_pinyin": "Wǒ ǒurán yùjiànle yīgè lǎo péngyǒu, zhēn shì jīngxǐ.",
        "compound_definition": "I unexpectedly ran into an old friend, and it was such a surprise.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3690,
        "character": "傅",
        "character_pinyin": "fù",
        "eng": "to teach; to instruct",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他的老师傅教了他很多实用的技能。",
        "compound_pinyin": "Tā de lǎoshī fù jiàole tā hěn duō shíyòng de jìnéng.",
        "compound_definition": "His mentor taught him many practical skills.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3692,
        "character": "兔",
        "character_pinyin": "tù",
        "eng": "rabbit",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "小兔子在草地上跳来跳去，真可爱。",
        "compound_pinyin": "Xiǎo tùzi zài cǎodì shàng tiàolái tiàoqù, zhēn kě'ài.",
        "compound_definition": "The little rabbit is hopping around in the grass; it’s so cute.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3693,
        "character": "册",
        "character_pinyin": "cè",
        "eng": "book; volume",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这本书有三册，每册都很有趣。",
        "compound_pinyin": "Zhè běn shū yǒu sān cè, měi cè dōu hěn yǒuqù.",
        "compound_definition": "This book has three volumes, and each one is very interesting.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3694,
        "character": "军",
        "character_pinyin": "jūn",
        "eng": "army; military",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他想加入军队，为国家服务。",
        "compound_pinyin": "Tā xiǎng jiārù jūnduì, wèi guójiā fúwù.",
        "compound_definition": "He wants to join the army to serve his country.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3695,
        "character": "冠",
        "character_pinyin": "guàn",
        "eng": "crown; to crown",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她赢得了比赛，戴上了冠军的冠。",
        "compound_pinyin": "Tā yíngdéle bǐsài, dàishàngle guànjūn de guàn.",
        "compound_definition": "She won the competition and put on the champion's crown.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3705,
        "character": "匹",
        "character_pinyin": "pǐ",
        "eng": "measure word for horses; to match",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他买了一匹漂亮的马，准备参加比赛。",
        "compound_pinyin": "Tā mǎile yī pǐ piàoliang de mǎ, zhǔnbèi cānjiā bǐsài.",
        "compound_definition": "He bought a beautiful horse to prepare for the competition.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3709,
        "character": "厅",
        "character_pinyin": "tīng",
        "eng": "hall; room",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "我们在大厅里举办了一个生日派对。",
        "compound_pinyin": "Wǒmen zài dàtīng lǐ jǔbànle yīgè shēngrì pàiduì.",
        "compound_definition": "We held a birthday party in the hall.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3712,
        "character": "厨",
        "character_pinyin": "chú",
        "eng": "kitchen; chef",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她在厨师学校学习，想成为一名专业厨师。",
        "compound_pinyin": "Tā zài chúshī xuéxiào xuéxí, xiǎng chéngwéi yī míng zhuānyè chúshī.",
        "compound_definition": "She is studying at a culinary school and wants to become a professional chef.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3713,
        "character": "叉",
        "character_pinyin": "chā",
        "eng": "fork; to fork",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "请用叉子来吃沙拉，这样更方便。",
        "compound_pinyin": "Qǐng yòng chāzi lái chī shālā, zhèyàng gèng fāngbiàn.",
        "compound_definition": "Please use a fork to eat the salad; it’s more convenient that way.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3716,
        "character": "吨",
        "character_pinyin": "dūn",
        "eng": "ton",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这辆卡车的载重能力是五吨，非常强大。",
        "compound_pinyin": "Zhè liàng kǎchē de zàizhòng nénglì shì wǔ dūn, fēicháng qiángdà.",
        "compound_definition": "This truck has a load capacity of five tons, which is very powerful.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3724,
        "character": "域",
        "character_pinyin": "yù",
        "eng": "area; domain",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她是一位优秀的传统诗歌教授，这是她的专业领域。我请求她成为我的师傅。",
        "compound_pinyin": "Tā shì yī wèi yōuxiù de chuántǒng shīgē jiàoshòu, zhè shì tā de zhuānyè lǐngyù. Wǒ qǐngqiú tā chéngwéi wǒ de shīfù.",
        "compound_definition": "She was an excellent professor of traditional poetry, her area of ​​expertise, and I asked her to become my mentor.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3726,
        "character": "壁",
        "character_pinyin": "bì",
        "eng": "wall",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这面壁画很漂亮，吸引了很多游客。",
        "compound_pinyin": "Zhè miàn bìhuà hěn piàoliang, xīyǐnle hěn duō yóukè.",
        "compound_definition": "This mural is beautiful and attracts many visitors.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3727,
        "character": "夕",
        "character_pinyin": "xī",
        "eng": "evening; dusk",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "在中央公园，我和我的配偶看着夕阳睡着了。",
        "compound_pinyin": "Zài zhōngyāng gōngyuán, wǒ hé wǒ de pèi'ǒu kànzhe xīyáng shuìzhele.",
        "compound_definition": "My spouse and I fell asleep watching the sunset in Central Park.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3728,
        "character": "央",
        "character_pinyin": "yāng",
        "eng": "center; middle",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这个城市的央区有很多商店和餐厅。",
        "compound_pinyin": "Zhège chéngshì de yāngqū yǒu hěn duō shāngdiàn hé cāntīng.",
        "compound_definition": "The central area of the city has many shops and restaurants.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3732,
        "character": "宾",
        "character_pinyin": "bīn",
        "eng": "guest; visitor",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "酒店的服务员热情地欢迎每一位宾客。",
        "compound_pinyin": "Jiǔdiàn de fúwùyuán rèqíng de huānyíng měi yī wèi bīnkè.",
        "compound_definition": "The hotel staff warmly welcomes every guest.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3734,
        "character": "寿",
        "character_pinyin": "shòu",
        "eng": "longevity; life span",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她的生日派对上，大家祝她长寿。",
        "compound_pinyin": "Tā de shēngrì pàiduì shàng, dàjiā zhù tā chángshòu.",
        "compound_definition": "At her birthday party, everyone wished her longevity.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3741,
        "character": "岸",
        "character_pinyin": "àn",
        "eng": "bank; shore",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "云南海边有美丽的水岸，很适合这幅山水画。",
        "compound_pinyin": "Yúnnán hǎibiān yǒu měilì de shuǐ àn, hěn shìhé zhè fú shānshuǐhuà.",
        "compound_definition": "Yunnan has a beautiful seashore, which is very suitable for this landscape painting.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3742,
        "character": "帘",
        "character_pinyin": "lián",
        "eng": "curtain",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她把窗帘拉开，让阳光照进房间。",
        "compound_pinyin": "Tā bǎ chuānglián lā kāi, ràng yángguāng zhào jìn fángjiān.",
        "compound_definition": "She pulled back the curtain, letting sunlight into the room.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3743,
        "character": "幅",
        "character_pinyin": "fú",
        "eng": "measure word for paintings; width",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这幅画的颜色非常鲜艳，吸引了很多人。",
        "compound_pinyin": "Zhè fú huà de yánsè fēicháng xiānyàn, xīyǐnle hěn duō rén.",
        "compound_definition": "The colors of this painting are very bright and attract many people.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3744,
        "character": "幕",
        "character_pinyin": "mù",
        "eng": "curtain; scene",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "在我偶然遇见我的英雄之后，我让她在我的宾馆住了一晚，参加开幕式。",
        "compound_pinyin": "Zài wǒ ǒurán yùjiàn wǒ de yīngxióng zhīhòu, wǒ ràng tā zài wǒ de bīnguǎn zhùle yī wǎn, cānjiā kāimù shì.",
        "compound_definition": "After I met my hero by chance, I asked her to stay at my guest house for a night for the opening ceremony.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3746,
        "character": "库",
        "character_pinyin": "kù",
        "eng": "warehouse; storehouse",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "公司的仓库里存放着很多设备和材料。",
        "compound_pinyin": "Gōngsī de cāngkù lǐ cúnfàngzhe hěn duō shèbèi hé cáiliào.",
        "compound_definition": "The company's warehouse stores a lot of equipment and materials.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3750,
        "character": "德",
        "character_pinyin": "dé",
        "eng": "virtue; morality",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这可能会让人感到吃惊，尽管企业宣扬道德和英雄主义，但主席和高管们私下里只关心金钱。",
        "compound_pinyin": "Zhè kěnéng huì ràng rén gǎndào chījīng, jǐnguǎn qǐyè xuānyáng dàodé hé yīngxióng zhǔyì, dàn zhǔxí hé gāo guǎnmen sīxià lǐ zhǐ guānxīn jīnqián.",
        "compound_definition": "It may come as a surprise that despite corporate rhetoric about morality and heroism, chairmen and executives privately care only about money.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3805,
        "character": "旦",
        "character_pinyin": "dàn",
        "eng": "dawn; daybreak",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "清晨的旦时分，鸟儿开始欢快地歌唱。",
        "compound_pinyin": "Qīngchén de dàn shífēn, niǎo er kāishǐ huānkuài de gēchàng.",
        "compound_definition": "At dawn, the birds start singing happily.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3812,
        "character": "枪",
        "character_pinyin": "qiāng",
        "eng": "gun; firearm",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "居住在幽静的地方可能会给你一种虚假的安全感。即使存在一些风险，我还是强迫你在家里放一把枪来保护自己。",
        "compound_pinyin": "Jūzhù zài yōujìng dì dìfāng kěnéng huì gěi nǐ yī zhǒng xūjiǎ de ānquán gǎn. Jíshǐ cúnzài yīxiē fēngxiǎn, wǒ háishì qiǎngpò nǐ zài jiālǐ fàng yī bǎ qiāng lái bǎohù zìjǐ.",
        "compound_definition": "Living in a secluded area may give you a false sense of security. Even though there are some risks, I urge you to keep a gun in your home for protection.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3814,
        "character": "柜",
        "character_pinyin": "guì",
        "eng": "cabinet; cupboard",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "叉子和盘子存放在窗帘旁边的厨柜里。",
        "compound_pinyin": "Chāzi hé pánzi cúnfàng zài chuānglián pángbiān de chú guì lǐ.",
        "compound_definition": "The forks and plates are stored in the kitchen cabinet next to the curtains.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3815,
        "character": "柴",
        "character_pinyin": "chái",
        "eng": "firewood; kindling",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "冬天的时候，他们会在家里烧柴取暖。",
        "compound_pinyin": "Dōngtiān de shíhòu, tāmen huì zài jiālǐ shāo chái qǔnuǎn.",
        "compound_definition": "In winter, they burn firewood at home for warmth.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3816,
        "character": "柿",
        "character_pinyin": "shì",
        "eng": "persimmon",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "秋天是柿子成熟的季节，市场上满是美味的柿子。",
        "compound_pinyin": "Qiūtiān shì shìzi chéngshú de jìjié, shìchǎng shàng mǎn shì měiwèi de shìzi.",
        "compound_definition": "Autumn is the season when persimmons ripen, and the market is full of delicious ones.",
        "valid_sentence": "",
        "counter (75)\r": "\r"
    },
    {
        "id": 3817,
        "character": "核",
        "character_pinyin": "hé",
        "eng": "nucleus; core",
        "hsk_level": 5,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这颗微小的金属球最初附着在原子核上。它在元旦开幕式上掉了下来。",
        "compound_pinyin": "Zhè kē wéixiǎo de jīnshǔ qiú zuìchū fùzhuó zài yuánzǐhé shàng. Tā zài yuándàn kāimù shì shàng diàole xiàlái.",
        "compound_definition": "The tiny metal ball was originally attached to the nucleus of an atom. It fell off during the opening ceremony on New Year's Day.",
        "valid_sentence": ",",
        "counter (75)\r": ""
    }
]