var hskLevelZ = [
    {
        "id": 9000,
        "character": "乳",
        "character_pinyin": "Rǔ",
        "eng": "Milk",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "众所周知，来自欧洲的乳制品和粮物产品的浓度比中国大陆的更高。",
        "compound_pinyin": "Zhòngsuǒzhōuzhī láizì ōuzhōu de rǔ zhìpǐn hé liáng wù chǎnpǐn de nóngdù bǐ zhōngguó dàlù de gèng gāo.\"",
        "compound_definition": "It is well known that dairy and grain products from Europe have higher concentrations than those from mainland China.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9001,
        "character": "乳头",
        "character_pinyin": "Rǔtóu",
        "eng": "Nipple",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "她在母乳喂养时发现乳头变得非常敏感，所以需要使用保护乳头的乳霜。",
        "compound_pinyin": "Tā zài mǔrǔ wèiyǎng shí fāxiàn rǔtóu biànde fēicháng mǐngǎn, suǒyǐ xūyào shǐyòng bǎohù rǔtóu de rǔshuāng.",
        "compound_definition": "She found that her nipples became very sensitive during breastfeeding, so she needed to use a protective nipple cream.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9002,
        "character": "传染",
        "character_pinyin": "chuánrǎn",
        "eng": "infect",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "由于这种感冒病毒传播速度很快，医生建议大家勤洗手，以减少传染的风险。",
        "compound_pinyin": "Yóuyú zhè zhǒng gǎnmào bìngdú chuánbò sùdù hěn kuài, yīshēng jiànyì dàjiā qín xǐshǒu, yǐ jiǎnshǎo chuánrǎn de fēngxiǎn.",
        "compound_definition": "Since this cold virus spreads quickly, doctors recommend frequent handwashing to reduce the risk of infection.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9003,
        "character": "勉",
        "character_pinyin": "miǎn",
        "eng": "encourage",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "勉励幼儿园学生顺应并尊敬老师，如果他们表现出烂的态度，就会受到打击。",
        "compound_pinyin": "Miǎnlì yòu'éryuán xuéshēng shùnyìng bìng zūnjìng lǎoshī, rúguǒ tāmen biǎoxiàn chū làn de tàidù, jiù huì shòudào dǎjí.",
        "compound_definition": "Kindergarten students are encouraged to obey and respect their teachers and will be punished if they display a bad attitude.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9004,
        "character": "勉强",
        "character_pinyin": "miǎnqiáng",
        "eng": "to do reluctantly",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这顿饭他吃得很慢，看起来是勉强自己吃下去的，似乎没有什么胃口。",
        "compound_pinyin": "Zhè dùn fàn tā chī de hěn màn, kànqǐlái shì miǎnqiǎng zìjǐ chī xiàqù de, sìhū méiyǒu shénme wèikǒu.",
        "compound_definition": "He ate this meal very slowly, and it seemed like he was forcing himself to eat, as if he had no appetite.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9005,
        "character": "厕",
        "character_pinyin": "cè",
        "eng": "toilet",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "厕所里有一个荡妇正在露出她的乳房和乳头。",
        "compound_pinyin": "Cèsuǒ li yǒu yīgè dàng fù zhèngzài lùchū tā de rǔfáng hé rǔtóu.",
        "compound_definition": "There was a slut in the toilet showing her breasts and nipples.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9006,
        "character": "君",
        "character_pinyin": "Jūn",
        "eng": "Gentleman",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "打扰一下，君子。请问厕所在哪儿？我和我兄弟想找个地方聊聊天。",
        "compound_pinyin": "Dǎrǎo yīxià, jūnzǐ. Qǐngwèn cèsuǒ zài nǎ'er? Wǒ hé wǒ xiōngdì xiǎng zhǎo gè dìfāng liáo liáotiān.",
        "compound_definition": "Excuse me, sir.,Where is the toilet, please?,My brother and I need a place to chat.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9007,
        "character": "吻",
        "character_pinyin": "Wěn",
        "eng": "Kiss",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "当这个淫荡的婊子开始亲吻这个害羞而孤独的男孩时，他的肉棒就变硬了，并在裤子里射了精。",
        "compound_pinyin": "Dāng zhège yíndàng de biǎo zǐ kāishǐ qīnwěn zhège hàixiū ér gūdú de nánhái shí, tā de ròubàng jiù biàn yìngle, bìng zài kùzǐ lǐ shèle jīng.",
        "compound_definition": "When this slutty bitch starts kissing this shy and lonely boy, his cock gets hard and he cums in his pants.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9008,
        "character": "哎呀",
        "character_pinyin": "Āiyā",
        "eng": "Aiya",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀，我的手机掉进水里了，快帮我想想办法！",
        "compound_pinyin": "Āiyā, wǒ de shǒujī diào jìn shuǐ lǐ le, kuài bāng wǒ xiǎngxiǎng bànfǎ!",
        "compound_definition": "Oh no, my phone fell into the water, please help me think of a solution!",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9009,
        "character": "哎",
        "character_pinyin": "Āi",
        "eng": "Hey!",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀！我放的屁太臭了，我老婆都开始骂我了。我怕等会儿要受罚。",
        "compound_pinyin": "Āiyā! Wǒ fàng de pì tài chòule, wǒ lǎopó dōu kāishǐ mà wǒle. Wǒ pà děng huì er yào shòufá.",
        "compound_definition": "Ouch! My fart was so smelly that my wife started scolding me. I'm afraid I'll be punished later.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9010,
        "character": "啦",
        "character_pinyin": "la",
        "eng": "la",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "你别这么冷漠，安慰我啦。",
        "compound_pinyin": "Nǐ bié zhème lěngmò, ānwèi wǒ la.",
        "compound_definition": "Don't be so cold, comfort me.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9011,
        "character": "嗯",
        "character_pinyin": "Ǹg",
        "eng": "um",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "嗯…请温柔一点。嘛嘛，如果你愿意，你可以更用力一点，但我的屁股很敏感啦。",
        "compound_pinyin": "Ǹg…qǐng wēnróu yīdiǎn. Ma ma, rúguǒ nǐ yuànyì, nǐ kěyǐ gèng yònglì yīdiǎn, dàn wǒ de pìgu hěn mǐngǎn la.",
        "compound_definition": "Um... please be gentle. Um, you can be harder if you want, but my ass is very sensitive.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9012,
        "character": "嘛",
        "character_pinyin": "ma",
        "eng": "well",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "糟糕…嘛…我没能及时将我的肉棒从你的小穴中拔出来啦。",
        "compound_pinyin": "Zāogāo…ma…wǒ méi néng jíshí jiāng wǒ de ròubàng cóng nǐ de xiǎoxué zhōng bá chūlái la.",
        "compound_definition": "Oops…well…I couldn’t pull my cock out of your pussy in time.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9013,
        "character": "处男",
        "character_pinyin": "Chǔnán",
        "eng": "Virgin",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他害羞地承认自己还是处男，因为从未谈过恋爱。",
        "compound_pinyin": "Tā hàixiū de chéngrèn zìjǐ háishì chǔnán, yīnwèi cóngwèi tánguò liàn'ài.",
        "compound_definition": "He shyly admitted that he was still a virgin because he had never been in a relationship before.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9014,
        "character": "妙",
        "character_pinyin": "Miào",
        "eng": "Wonderful",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这荡妇巧妙地引诱她的炮友阻碍老师收集文献。",
        "compound_pinyin": "Zhè dàng fù qiǎomiào de yǐnyòu tā de pào yǒu zǔ'ài lǎoshī shōují wénxiàn.",
        "compound_definition": "The slut cleverly seduces her fuck buddy into hindering the teacher's collection of literature.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9015,
        "character": "婊",
        "character_pinyin": "biǎo",
        "eng": "prostitute",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个年轻的婊子到处传染班上那些不知情的处女，满足她们的性欲。",
        "compound_pinyin": "Zhège niánqīng de biǎo zǐ dàochù chuánrǎn bān shàng nàxiē bùzhī qíng de chǔnǚ, mǎnzú tāmen dì xìngyù.",
        "compound_definition": "This young bitch goes around infecting the unsuspecting virgins in her class and satisfying their sexual desires.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9016,
        "character": "婊子",
        "character_pinyin": "biǎozǐ",
        "eng": "bitch",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他说话太难听了，随便骂人婊子，让大家都觉得不舒服。",
        "compound_pinyin": "Tā shuōhuà tài nántīng le, suíbiàn mà rén biǎozi, ràng dàjiā dōu juéde bù shūfú.",
        "compound_definition": "His words were too offensive; calling someone a \"bitch\" so casually made everyone uncomfortable.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9017,
        "character": "孤",
        "character_pinyin": "gū",
        "eng": "solitary",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "孤独的女人被炮友甩了，大喊“肏，我好寂寞啊！”",
        "compound_pinyin": "Gūdú de nǚrén bèi pào yǒu shuǎile, dà hǎn “cào, wǒ hǎo jìmò a!”",
        "compound_definition": "Lonely woman gets dumped by her sex partner and screams “Fuck, I'm so lonely!”",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9018,
        "character": "害羞",
        "character_pinyin": "Hàixiū",
        "eng": "Shy",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她性格内向，见到陌生人时总是低着头，显得非常害羞。",
        "compound_pinyin": "Tā xìnggé nèixiàng, jiàndào mòshēngrén shí zǒng shì dīzhe tóu, xiǎnde fēicháng hàixiū.",
        "compound_definition": "She is introverted and always lowers her head when meeting strangers, looking very shy.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9019,
        "character": "寂",
        "character_pinyin": "Jì",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这位四川君子虽然巧妙，但是却常常因为寂寞而哭泣。",
        "compound_pinyin": "Zhè wèi sìchuān jūnzǐ suīrán qiǎomiào, dànshì què chángcháng yīnwèi jìmò ér kūqì.",
        "compound_definition": "Although this Sichuan gentleman was clever, he often cried because of loneliness.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9020,
        "character": "寂寞",
        "character_pinyin": "Jìmò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "自从搬到这座城市后，他没有什么朋友，经常一个人待在家里感到很寂寞。",
        "compound_pinyin": "Zìcóng bān dào zhè zuò chéngshì hòu, tā méiyǒu shénme péngyǒu, jīngcháng yīgè rén dāi zài jiālǐ gǎndào hěn jìmò.",
        "compound_definition": "Since moving to this city, he hasn't made many friends and often stays at home alone, feeling very lonely.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9021,
        "character": "寞",
        "character_pinyin": "mò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我希望有人能治愈我这种无法再忍受的寂寞。",
        "compound_pinyin": "Wǒ xīwàng yǒurén néng zhìyù wǒ zhè zhǒng wúfǎ zài rěnshòu de jìmò.",
        "compound_definition": "I hope someone can heal this unbearable loneliness.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9022,
        "character": "尿",
        "character_pinyin": "Niào",
        "eng": "Urine",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "哎呀！我因为喝醉了而错过了上厕所的机会，现在地板上全是尿液。我应该向其他客人道歉。",
        "compound_pinyin": "Āiyā! Wǒ yīnwèi hē zuìle ér cuòguòle shàng cèsuǒ de jīhuì, xiànzài dìbǎn shàng quán shì niào yè. Wǒ yīnggāi xiàng qítā kèrén dàoqiàn.",
        "compound_definition": "Oops!,I missed the bathroom break because I was drunk and now there is urine all over the floor.,I should apologize to the other guests.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9023,
        "character": "屁",
        "character_pinyin": "Pì",
        "eng": "Fart",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个低俗的男人，觉得亲吻女友柔软的屁股是一件很爽的事情。",
        "compound_pinyin": "Zhège dīsú de nánrén, juédé qīnwěn nǚyǒu róuruǎn de pìgu shì yī jiàn hěn shuǎng de shìqíng.",
        "compound_definition": "This vulgar man thinks it is a very pleasant thing to kiss his girlfriend's soft butt.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9024,
        "character": "屁股",
        "character_pinyin": "Pìgu",
        "eng": "Butt",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他不小心摔倒了，一下子坐在地上，屁股都摔疼了。",
        "compound_pinyin": "Tā bù xiǎoxīn shuāidǎo le, yīxiàzi zuò zài dìshàng, pìgu dōu shuāi téng le.",
        "compound_definition": "He accidentally fell and landed on the ground, making his butt hurt.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9025,
        "character": "川",
        "character_pinyin": "Chuān",
        "eng": "Sichuan",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "四川以其巨大的田野，温泉和激烈的棒球竞赛而闻名。",
        "compound_pinyin": "Sìchuān yǐ qí jùdà de tiányě, wēnquán hé jīliè de bàngqiú jìngsài ér wénmíng.",
        "compound_definition": "Sichuan is famous for its huge fields, hot springs and fierce baseball competition.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9026,
        "character": "性欲",
        "character_pinyin": "Xìngyù",
        "eng": "Sexual desire",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "长期的压力和疲劳可能会影响一个人的性欲，导致对亲密关系失去兴趣。",
        "compound_pinyin": "Chángqí de yālì hé píláo kěnéng huì yǐngxiǎng yīgè rén de xìngyù, dǎozhì duì qīnmì guānxì shīqù xìngqù.",
        "compound_definition": "Long-term stress and fatigue may affect a person's sexual desire, leading to a loss of interest in intimacy.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9027,
        "character": "愈",
        "character_pinyin": "Yù",
        "eng": "Heal",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这位欧洲护士经常用她的舌头来治愈病人的性欲。",
        "compound_pinyin": "Zhè wèi ōuzhōu hùshì jīngcháng yòng tā de shétou lái zhìyù bìngrén dì xìngyù.",
        "compound_definition": "This European nurse often used her tongue to heal her patients' sexual desires.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9028,
        "character": "抱歉",
        "character_pinyin": "Bàoqiàn",
        "eng": "Feel sorry",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我昨天忘了回复你的信息，真是抱歉，希望没有耽误你的事情。",
        "compound_pinyin": "Wǒ zuótiān wàng le huífù nǐ de xìnxī, zhēn shì bàoqiàn, xīwàng méiyǒu dānwù nǐ de shìqíng.",
        "compound_definition": "I forgot to reply to your message yesterday, I'm really sorry, and I hope I didn't delay anything for you.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9029,
        "character": "接吻",
        "character_pinyin": "Jiēwěn",
        "eng": "Kiss",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他们在电影的最后一幕深情地接吻，展现了彼此的爱意。",
        "compound_pinyin": "Tāmen zài diànyǐng de zuìhòu yīmù shēnqíng de jiēwěn, zhǎnxiàn le bǐcǐ de àiyì.",
        "compound_definition": "They kissed passionately in the final scene of the movie, showing their love for each other.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9030,
        "character": "柔",
        "character_pinyin": "róu",
        "eng": "soft",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "哎呀！亚洲女人的舌头好柔软，光是亲吻就感觉淫荡至极啦。",
        "compound_pinyin": "Āiyā! Yàzhōu nǚrén de shétou hǎo róuruǎn, guāng shì qīnwěn jiù gǎnjué yíndàng zhìjí la.",
        "compound_definition": "Oh my!,Asian women's tongues are so soft, just kissing them makes me feel extremely horny.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9031,
        "character": "欧",
        "character_pinyin": "ōu",
        "eng": "Europe",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我怀念那位专门做按摩的欧洲女人，她的按摩手法非常温柔。",
        "compound_pinyin": "Wǒ huáiniàn nà wèi zhuānmén zuò ànmó de ōuzhōu nǚrén, tā de ànmó shǒufǎ fēicháng wēnróu.",
        "compound_definition": "I miss the European woman who specialized in massage and her gentle touch.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9032,
        "character": "欲",
        "character_pinyin": "Yù",
        "eng": "Want",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我对焗米饭的欲望让我发疯，特别是当我闻到它的味道时，所以请给我一个鼻夹！",
        "compound_pinyin": "Wǒ duì jú mǐfàn de yùwàng ràng wǒ fāfēng, tèbié shì dāng wǒ wén dào tā de wèidào shí, suǒyǐ qǐng gěi wǒ yīgè bí jiā!",
        "compound_definition": "My craving for baked rice drives me crazy, especially when I smell it, so give me a nose clip please!",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9033,
        "character": "歉",
        "character_pinyin": "Qiàn",
        "eng": "Apologize",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我必须道歉。虽然我试图在厕所小便，但我的尿液洒在地板上，现在一切都很润滑。",
        "compound_pinyin": "Wǒ bìxū dàoqiàn. Suīrán wǒ shìtú zài cèsuǒ xiǎobiàn, dàn wǒ de niào yè sǎ zài dìbǎn shàng, xiànzài yīqiè dōu hěn rùnhuá.",
        "compound_definition": "I must apologize.,Although I tried to pee in the toilet, my urine spilled on the floor and now everything is lubricated.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9034,
        "character": "泣",
        "character_pinyin": "qì",
        "eng": "weep",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我的炮友温柔地按摩着我的肉棒，而她因被男友骗人而被甩了而害羞地哭泣。",
        "compound_pinyin": "Wǒ de pào yǒu wēnróu de ànmózhe wǒ de ròubàng, ér tā yīn bèi nányǒu piàn rén ér bèi shuǎile ér hàixiū de kūqì.",
        "compound_definition": "My fuck buddy gently massaged my cock while she cried shyly because she was dumped by her boyfriend who cheated on her.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9035,
        "character": "淫",
        "character_pinyin": "Yín",
        "eng": "Lewd",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她是那种如果混蛋把她绑在床上，锁在房间里并把她露出网上，她就会漏出淫水的女人。",
        "compound_pinyin": "Tā shì nà zhǒng rúguǒ húndàn bǎ tā bǎng zài chuángshàng, suǒ zài fángjiān lǐ bìng bǎ tā lùchū wǎngshàng, tā jiù huì lòuchū yínshuǐ de nǚrén.",
        "compound_definition": "She's the kind of woman who would leak juice if some asshole tied her to a bed, locked her in a room and exposed her online.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9036,
        "character": "淫水",
        "character_pinyin": "Yínshuǐ",
        "eng": "Sexual secretion",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "当她玩弄自己的肛门时，她无法停止流出淫水。",
        "compound_pinyin": "Dāng tā wànnòng zìjǐ de gāngmén shí, tā wúfǎ tíngzhǐ liúchū yínshuǐ.",
        "compound_definition": "She couldn't stop leaking juices while she played with her anus.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9037,
        "character": "混",
        "character_pinyin": "Hùn",
        "eng": "Mix",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "那个君子是个混蛋，经常用金钱诱惑穷困的女人，强迫她们顺从。",
        "compound_pinyin": "Nàgè jūnzǐ shìgè húndàn, jīngcháng yòng jīnqián yòuhuò qióngkùn de nǚrén, qiǎngpò tāmen shùncóng.",
        "compound_definition": "That gentleman is a bastard who often uses money to seduce poor women and force them to obey.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9038,
        "character": "混蛋",
        "character_pinyin": "Húndàn",
        "eng": "Asshole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个笨蛋的混蛋把车开进了我的餐馆，现在政府要罚款他三百万人民币。",
        "compound_pinyin": "Zhège bèndàn de húndàn bǎ chē kāi jìnle wǒ de cānguǎn, xiànzài zhèngfǔ yào fákuǎn tā sānbǎi wàn rénmínbì.",
        "compound_definition": "This dumb bastard drove his car into my restaurant and now the government is going to fine him three million RMB.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9039,
        "character": "温柔",
        "character_pinyin": "wēnróu",
        "eng": "gentle",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她的声音很温柔，总是让人感到放松和安心。",
        "compound_pinyin": "Tā de shēngyīn hěn wēnróu, zǒngshì ràng rén gǎndào fàngsōng hé ānxīn.",
        "compound_definition": "Her voice is very gentle, always making people feel relaxed and reassured.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9040,
        "character": "湿漉漉",
        "character_pinyin": "Shīlùlù",
        "eng": "Wet",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "外面刚下过雨，他的衣服和头发都变得湿漉漉的。",
        "compound_pinyin": "Wàimiàn gāng xiàguò yǔ, tā de yīfú hé tóufà dōu biàn de shīlùlù de.",
        "compound_definition": "It just rained outside, and his clothes and hair became soaking wet.",
        "valid_sentence": "",
        "counter (73)\r": 3
    },
    {
        "id": 9041,
        "character": "漉",
        "character_pinyin": "Lù",
        "eng": "Filter liquids",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "嗯，抱歉，你的手态湿漉漉了，所以我不想握住它们。",
        "compound_pinyin": "Ǹg, bàoqiàn, nǐ de shǒu tài shīlùlùle, suǒyǐ wǒ bùxiǎng wò zhù tāmen.",
        "compound_definition": "Um, sorry, your hands are wet, so I don't want to hold them.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9042,
        "character": "炮",
        "character_pinyin": "Pào",
        "eng": "Firecracker / cannon",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我把我的炮友绑起来，丢在一片空地田野，这让她疯狂起来，拿着长矛追着我，但我用盾牌挡住了她。",
        "compound_pinyin": "Wǒ bǎ wǒ de pào yǒu bǎng qǐlái, diū zài yīpiàn kòngdì tiányě, zhè ràng tā fēngkuáng qǐlái, názhe cháng máo zhuīzhe wǒ, dàn wǒ yòng dùnpái dǎngzhùle tā.",
        "compound_definition": "I tied up my fuck buddy and dumped her in an empty field, which made her go crazy and she chased me with a spear, but I held her off with my shield.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9043,
        "character": "焗",
        "character_pinyin": "jú",
        "eng": "baked",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "夕阳下，她在中央公园向我挥手。我们约好一起吃焗饭。",
        "compound_pinyin": "Xīyáng xià, tā zài zhōngyāng gōngyuán xiàng wǒ huīshǒu. Wǒmen yuē hǎo yīqǐ chī jú fàn.",
        "compound_definition": "She waved to me in Central Park at sunset.,We made an appointment to have baked rice together.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9044,
        "character": "煽",
        "character_pinyin": "shān",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "厨师煽动人群扰乱钢琴演，向任何能抢走玉饰的人提供焗米饭。",
        "compound_pinyin": "Chúshī shāndòng rénqún rǎoluàn gāngqín yǎn, xiàng rènhé néng qiǎng zǒu yù shì de rén tígōng jú mǐfàn.",
        "compound_definition": "The chef incites the crowd to disrupt the piano performance, offering baked rice to anyone who can grab the jade ornament.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9045,
        "character": "煽动",
        "character_pinyin": "shāndòng",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他在社交媒体上发布了一些极端言论，试图煽动人们的愤怒。",
        "compound_pinyin": "Tā zài shèjiāo méitǐ shàng fābù le yīxiē jíduān yánlùn, shìtú shāndòng rénmen de fènnù.",
        "compound_definition": "He posted some extreme comments on social media, trying to incite people's anger.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9046,
        "character": "爽",
        "character_pinyin": "Shuǎng",
        "eng": "Cool",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我不骗你，舔着一个又矮又瘦的漂亮女孩小穴里的尿液，感觉很爽。",
        "compound_pinyin": "Wǒ bù piàn nǐ, tiǎnzhe yīgè yòu ǎi yòu shòu de piàoliang nǚhái xiǎoxué lǐ de niào yè, gǎnjué hěn shuǎng.",
        "compound_definition": "I kid you not, it felt really good licking the piss out of a short, skinny pretty girl's pussy.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9047,
        "character": "甩",
        "character_pinyin": "shuǎi",
        "eng": "throw",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "被婊子甩了之后，孤独的男孩只能一边在厕所里自慰，一边听着她吸另一个男人的肉棒。",
        "compound_pinyin": "Bèi biǎo zǐ shuǎi liǎo zhīhòu, gūdú de nánhái zhǐ néng yībiān zài cèsuǒ lǐ zìwèi, yībiān tīngzhe tā xī lìng yīgè nánrén de ròubàng.",
        "compound_definition": "After being dumped by a bitch, the lonely boy can only masturbate in the bathroom while listening to her sucking another man's cock.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9048,
        "character": "甩被了",
        "character_pinyin": "bèi shuǎile",
        "eng": "dumped",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他早上起床太匆忙，直接甩被了就跑去上班了。",
        "compound_pinyin": "Tā zǎoshang qǐchuáng tài cōngmáng, zhíjiē shuǎi bèi le jiù pǎo qù shàngbān le.",
        "compound_definition": "He got up in a hurry this morning, threw off the blanket, and rushed to work.",
        "valid_sentence": "",
        "counter (73)\r": 3
    },
    {
        "id": 9049,
        "character": "田",
        "character_pinyin": "tián",
        "eng": "field",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这位美妙的女孩邀请我去四川的一片空田野，并愿意为我治愈伤。",
        "compound_pinyin": "Zhè wèi měimiào de nǚhái yāoqǐng wǒ qù sìchuān de yīpiàn kōng tiányě, bìng yuànyì wèi wǒ zhìyù shāng.",
        "compound_definition": "This wonderful girl invited me to an empty field in Sichuan and offered to heal my wounds.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9050,
        "character": "真扫兴",
        "character_pinyin": "Zhēn săoxìng",
        "eng": "What a bummer",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "我们正玩得开心，他突然说要走，真是真扫兴！",
        "compound_pinyin": "Wǒmen zhèng wán de kāixīn, tā tūrán shuō yào zǒu, zhēn shì zhēn sǎoxìng!",
        "compound_definition": "We were having fun, and he suddenly said he had to leave—what a bummer!",
        "valid_sentence": "",
        "counter (73)\r": 3
    },
    {
        "id": 9051,
        "character": "破处",
        "character_pinyin": "Pòchù",
        "eng": "Losing virginity",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我最大的耻辱是在我十八岁的时候将我的童贞给了学校的荡妇。",
        "compound_pinyin": "Wǒ zuìdà de chǐrǔ shì zài wǒ shíbā suì de shíhòu jiāng wǒ de tóngzhēn gěile xuéxiào de dàng fù.",
        "compound_definition": "My biggest shame was losing my virginity to a school slut when I was eighteen.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9052,
        "character": "穴",
        "character_pinyin": "xué",
        "eng": "hole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "她的小穴有美妙的治愈效果，这煽动了我，让我哭泣，感觉太爽了。",
        "compound_pinyin": "Tā de xiǎoxué yǒu měimiào de zhìyù xiàoguǒ, zhè shāndòngle wǒ, ràng wǒ kūqì, gǎnjué tài shuǎngle.",
        "compound_definition": "Her pussy had a wonderful healing quality that turned me on and made me cry and it felt so good.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9053,
        "character": "糟糕",
        "character_pinyin": "Zāogāo",
        "eng": "Oops",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "今天我忘记带钥匙，结果在家门口等了两个小时，最后还是请开锁师傅帮忙开的，真是太糟糕了！",
        "compound_pinyin": "Jīntiān wǒ wàngjì dài yàoshi, jiéguǒ zài jiā ménkǒu děngle liǎng gè xiǎoshí, zuìhòu háishì qǐng kāisuǒ shīfu bāngmáng kāi de, zhēn shì tài zāogāo le!",
        "compound_definition": "I forgot to bring my keys today, and as a result, I waited outside my door for two hours. In the end, I had to ask a locksmith for help to open it. It was really terrible!",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9054,
        "character": "绑",
        "character_pinyin": "bǎng",
        "eng": "tie",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "害羞的女孩只好穿着内衣和长袜，无奈地躺在床上，被绑起来并接受屁股按摩后，身湿漉漉。",
        "compound_pinyin": "Hàixiū de nǚhái zhǐhǎo chuānzhuó nèiyī hé zhǎng wà, wúnài de tǎng zài chuángshàng, bèi bǎng qǐlái bìng jiēshòu pìgu ànmó hòu, shēn shīlùlù.",
        "compound_definition": "The shy girl had no choice but to lie on the bed in her underwear and stockings, and she was wet after being tied up and receiving an ass massage.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9055,
        "character": "羞",
        "character_pinyin": "Xiū",
        "eng": "Shame",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "尽管她又瘦又害羞，但听到有人说“肏你妈妈”还是煽动了她的兴奋，她把蛋糕扔到了那个混蛋的屁股上。",
        "compound_pinyin": "Jǐnguǎn tā yòu shòu yòu hàixiū, dàn tīng dào yǒurén shuō “cào nǐ māmā” háishì shāndòngle tā de xīngfèn, tā bǎ dàngāo rēng dàole nàgè húndàn de pìgu shàng.",
        "compound_definition": "Even though she was skinny and shy, hearing someone say “fuck your mom” stirred her up and she threw the cake up the ass of that jerk.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9056,
        "character": "肉棒",
        "character_pinyin": "Ròubàng",
        "eng": "Meat stick",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "爽！我要把我的肉棒插进你的屁股里，阿川，你给我张开屁股。",
        "compound_pinyin": "Shuǎng! Wǒ yào bǎ wǒ de ròubàng chā jìn nǐ de pìgu lǐ, āchuān, nǐ gěi wǒ zhāng kāi pìgu.",
        "compound_definition": "Cool! I want to put my cock in your ass, Achuan, open your ass for me.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9057,
        "character": "肏",
        "character_pinyin": "Cào",
        "eng": "Fuck",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "肏！我感到很抱歉，但我必须随心所欲。",
        "compound_pinyin": "Cào! Wǒ gǎndào hěn bàoqiàn, dàn wǒ bìxū suíxīnsuǒyù.",
        "compound_definition": "Fuck!,I'm so sorry, but I have to do what I want.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9058,
        "character": "股",
        "character_pinyin": "gǔ",
        "eng": "Share",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这家川菜馆的股东们找到了一位称职的演员来宣扬他们的猪血菜。",
        "compound_pinyin": "Zhè jiā chuāncài guǎn de gǔdōngmen zhǎodàole yī wèi chènzhí de yǎnyuán lái xuānyáng tāmen de zhū xiě cài.",
        "compound_definition": "The shareholders of this Sichuan restaurant found a competent actor to promote their pig's blood dish.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9059,
        "character": "舌",
        "character_pinyin": "Shé",
        "eng": "Tongue",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "肏！吃这个焗饭弄伤了舌头。求求你用一个吻治愈它吧。",
        "compound_pinyin": "Cào! Chī zhège jú fàn nòng shāngle shétou. Qiú qiú nǐ yòng yīgè wěn zhìyù tā ba.",
        "compound_definition": "Fuck!,I hurt my tongue from eating this risotto.,Please heal it with a kiss.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9060,
        "character": "舔",
        "character_pinyin": "Tiǎn",
        "eng": "Lick",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "已婚妇女勉强地让邻居用舌头舔她的乳头，以换取不露出她的秘密。",
        "compound_pinyin": "Yǐ hūn fùnǚ miǎnqiáng de ràng línjū yòng shétou tiǎn tā de rǔtóu, yǐ huànqǔ bù lùchū tā de mìmì.",
        "compound_definition": "A married woman reluctantly lets her neighbor lick her nipples with his tongue in exchange for not revealing her secrets.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9061,
        "character": "荡",
        "character_pinyin": "Dàng",
        "eng": "To squander",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我很不勉强的陪伴这个学校里的荡妇去了游泳池，她向我泼水，让我疯狂。",
        "compound_pinyin": "Wǒ hěn bù miǎnqiáng de péibàn zhège xuéxiào lǐ de dàng fù qùle yóuyǒngchí, tā xiàng wǒ pōshuǐ, ràng wǒ fēngkuáng.",
        "compound_definition": "I reluctantly accompanied this school slut to the swimming pool where she splashed water on me and drove me wild.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9062,
        "character": "荡妇",
        "character_pinyin": "Dàngfù",
        "eng": "Slut",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "虽然阿川在学校是出了名的荡妇和公交车女郎，但是尽管她有那么多炮友，我还是想和她在一起。",
        "compound_pinyin": "Suīrán āchuān zài xuéxiào shì chūle míng de dàng fù hé gōngjiāo chē nǚláng, dànshì jǐnguǎn tā yǒu nàme duō pào yǒu, wǒ háishì xiǎng hé tā zài yīqǐ.",
        "compound_definition": "Although Achuan is a well-known slut and bus girl in school, I still want to be with her despite having so many sex partners.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9063,
        "character": "诱",
        "character_pinyin": "Yòu",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我女友的朋友声称她湿漉漉了，引诱我发生性关系，这种骗导致了我被暂时锁在柜子里的处罚。",
        "compound_pinyin": "Wǒ nǚyǒu de péngyǒu shēngchēng tā shīlùlùle, yǐnyòu wǒ fāshēng xìng guānxì, zhè zhǒng piàn dǎozhìle wǒ bèi zhànshí suǒ zài guìzǐ lǐ de chǔfá.",
        "compound_definition": "My girlfriend's friend lured me into sex by claiming she was wet, a deception that resulted in my punishment of being temporarily locked in a closet.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9064,
        "character": "诱惑",
        "character_pinyin": "Yòuhuò",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这家甜品店的蛋糕实在是太诱惑人了，我忍不住又买了一块。",
        "compound_pinyin": "Zhè jiā tiánpǐn diàn de dàngāo shízài shì tài yòuhuò rén le, wǒ rěnbuzhù yòu mǎile yí kuài.",
        "compound_definition": "The cakes in this dessert shop are so tempting that I couldn't resist buying another one.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9065,
        "character": "道歉",
        "character_pinyin": "dàoqiàn",
        "eng": "To apologize",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他意识到自己的错误后，立刻向朋友真诚地道歉，希望得到原谅。",
        "compound_pinyin": "Tā yìshídào zìjǐ de cuòwù hòu, lìkè xiàng péngyǒu zhēnchéng de dàoqiàn, xīwàng dédào yuánliàng.",
        "compound_definition": "After realizing his mistake, he sincerely apologized to his friend, hoping to be forgiven.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9066,
        "character": "野",
        "character_pinyin": "yě",
        "eng": "Wild",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "哎呀！你挡住了我的视线，我看不到闪电。",
        "compound_pinyin": "Āiyā! Nǐ dǎngzhùle wǒ de shìxiàn, wǒ kàn bù dào shǎndiàn.",
        "compound_definition": "Oops!,You blocked my view and I couldn't see the lightning.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9067,
        "character": "露",
        "character_pinyin": "Lù",
        "eng": "Dew",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "阿川向我透露了她无处可归宿的秘密，所以我就租了一间情趣酒店，操她直到晨朝。",
        "compound_pinyin": "Āchuān xiàng wǒ tòulùle tā wú chù kě guīsù de mìmì, suǒyǐ wǒ jiù zūle yī jiàn qíngqù jiǔdiàn, cāo tā zhídào chéncháo.",
        "compound_definition": "Achuan revealed to me her secret of having nowhere to stay, so I rented a love hotel and fucked her until dawn.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9068,
        "character": "露出",
        "character_pinyin": "Lùchū",
        "eng": "To expose",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "她听到这个好消息后，脸上立刻露出了灿烂的笑容。",
        "compound_pinyin": "Tā tīngdào zhège hǎo xiāoxi hòu, liǎn shàng lìkè lòuchūle cànlàn de xiàoróng.",
        "compound_definition": "After hearing the good news, she immediately revealed a bright smile on her face.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9069,
        "character": "顺",
        "character_pinyin": "shùn",
        "eng": "To obey",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "为了训练他的性欲，民族情妇要么给他的肉棒摩上润滑油以换取他的顺从，要么向他罚钱。",
        "compound_pinyin": "Wèile xùnliàn tā dì xìngyù, mínzú qíngfù yàome gěi tā de ròubàng mó shàng rùnhuá yóu yǐ huànqǔ tā de shùncóng, yàome xiàng tā fá qián.",
        "compound_definition": "In order to train his sexual desire, the ethnic mistress either rubs his cock with lubrication in exchange for his obedience or fines him.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9070,
        "character": "顺从",
        "character_pinyin": "Shùncóng",
        "eng": "Obedience",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "小时候，他总是顺从父母的安排，但长大后开始有了自己的想法。",
        "compound_pinyin": "Xiǎoshíhòu, tā zǒngshì shùncóng fùmǔ de ānpái, dàn zhǎngdà hòu kāishǐ yǒule zìjǐ de xiǎngfǎ.",
        "compound_definition": "As a child, he always obeyed his parents' arrangements, but as he grew up, he started having his own opinions.",
        "valid_sentence": "",
        "counter (73)\r": 2
    },
    {
        "id": 9071,
        "character": "洲",
        "character_pinyin": "zhōu",
        "eng": "Europe / continent",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "那个提倡男人应该用舌头舔妻子阴道的亚洲女人让我感到非常害羞。",
        "compound_pinyin": "Nàgè tíchàng nánrén yīnggāi yòng shétou tiǎn qīzǐ yīndào de yàzhōu nǚrén ràng wǒ gǎndào fēicháng hàixiū.",
        "compound_definition": "I'm really embarrassed by the Asian woman who advocates that men should lick their wives' vaginas with their tongues.",
        "valid_sentence": "",
        "counter (73)\r": 1
    },
    {
        "id": 9072,
        "character": "液",
        "character_pinyin": "yè",
        "eng": "Liquid",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个瘦小的大欧派强迫君子把她小穴里的尿液全部舔掉。",
        "compound_pinyin": "Zhège shòuxiǎo de dà ōu pài qiǎngpò jūnzǐ bǎ tā xiǎoxué lǐ de niào yè quánbù tiǎn diào.",
        "compound_definition": "This skinny big boobed girl forces a gentleman to lick all the urine out of her pussy.",
        "valid_sentence": "",
        "counter (73)\r": 1
    }
]