var hskLevel5Sentences = [
    {
        "id": 3673,
        "character": "丑",
        "character_pinyin": "chǒu",
        "eng": "ugly; disgraceful",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他觉得这幅画很丑，没什么艺术价值。",
        "compound_pinyin": "Tā juédé zhè fú huà hěn chǒu, méi shénme yìshù jiàzhí.",
        "compound_definition": "He thinks this painting is ugly and has no artistic value.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3675,
        "character": "乏",
        "character_pinyin": "fá",
        "eng": "tired; weary",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我这几天工作很乏，想休息一下。",
        "compound_pinyin": "Wǒ zhè jǐ tiān gōngzuò hěn fá, xiǎng xiūxí yīxià.",
        "compound_definition": "I've been very tired from work these past few days and want to rest a bit.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3685,
        "character": "俱",
        "character_pinyin": "jù",
        "eng": "all; together",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我们班的同学都俱来参加了这个活动。",
        "compound_pinyin": "Wǒmen bān de tóngxué dōu jù lái cānjiāle zhège huódòng.",
        "compound_definition": "All the students in our class came together to participate in this event.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3691,
        "character": "傻",
        "character_pinyin": "shǎ",
        "eng": "silly; foolish",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他做了个傻事，让大家都笑了。",
        "compound_pinyin": "Tā zuòle gè shǎ shì, ràng dàjiā dōu xiào le.",
        "compound_definition": "He did something silly that made everyone laugh.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3696,
        "character": "冻",
        "character_pinyin": "dòng",
        "eng": "to freeze; frozen",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "外面的天气太冷，水已经冻住了。",
        "compound_pinyin": "Wàimiàn de tiānqì tài lěng, shuǐ yǐjīng dòng zhùle.",
        "compound_definition": "The weather outside is too cold; the water has already frozen.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3704,
        "character": "勤",
        "character_pinyin": "qín",
        "eng": "diligent; hardworking",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她是一个勤奋的学生，每天都很努力学习。",
        "compound_pinyin": "Tā shì yīgè qínfèn de xuéshēng, měitiān dōu hěn nǔlì xuéxí.",
        "compound_definition": "She is a diligent student and studies hard every day.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3710,
        "character": "厉",
        "character_pinyin": "lì",
        "eng": "severe; strict",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的父母对他的学习要求很厉。",
        "compound_pinyin": "Tā de fùmǔ duì tā de xuéxí yāoqiú hěn lì.",
        "compound_definition": "His parents have very strict expectations for his studies.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3721,
        "character": "唯",
        "character_pinyin": "wéi",
        "eng": "only; just",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "唯有努力才能获得成功，这是我一直相信的。",
        "compound_pinyin": "Wéi yǒu nǔlì cáinéng huòdé chénggōng, zhè shì wǒ yīzhí xiāngxìn de.",
        "compound_definition": "Only through hard work can one achieve success; this is what I’ve always believed.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3723,
        "character": "坦",
        "character_pinyin": "tǎn",
        "eng": "flat; smooth",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这条路很坦，开车的时候很舒服。",
        "compound_pinyin": "Zhè tiáo lù hěn tǎn, kāichē de shíhòu hěn shūfú.",
        "compound_definition": "This road is very flat, making it comfortable to drive on.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3739,
        "character": "尤",
        "character_pinyin": "yóu",
        "eng": "especially; particularly",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "这个地方的风景尤为迷人，吸引了很多游客。",
        "compound_pinyin": "Zhège dìfāng de fēngjǐng yóuwéi mírén, xīyǐnle hěn duō yóukè.",
        "compound_definition": "The scenery in this place is particularly charming, attracting many visitors.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3745,
        "character": "幽",
        "character_pinyin": "yōu",
        "eng": "quiet; secluded",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个公园的角落非常幽静，适合读书和思考。",
        "compound_pinyin": "Zhège gōngyuán de jiǎoluò fēicháng yōujìng, shìhé dúshū hé sīkǎo.",
        "compound_definition": "This corner of the park is very quiet, perfect for reading and thinking.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3758,
        "character": "悄",
        "character_pinyin": "qiāo",
        "eng": "quietly; softly",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "她悄悄地走进房间，生怕打扰到他。",
        "compound_pinyin": "Tā qiāoqiāo de zǒu jìn fángjiān, shēngpà dǎrǎo dào tā.",
        "compound_definition": "She quietly entered the room, afraid of disturbing him.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3761,
        "character": "悲",
        "character_pinyin": "bēi",
        "eng": "sorrow; sadness",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的故事充满了悲伤，让人心痛。",
        "compound_pinyin": "Tā de gùshì chōngmǎnle bēishāng, ràng rén xīntòng.",
        "compound_definition": "His story is filled with sadness, causing heartache.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3765,
        "character": "慌",
        "character_pinyin": "huāng",
        "eng": "to panic; hurried",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他慌忙赶到机场，生怕错过航班。",
        "compound_pinyin": "Tā huāngmáng gǎn dào jīchǎng, shēngpà cuòguò hángbān.",
        "compound_definition": "He hurried to the airport, afraid of missing his flight.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3801,
        "character": "敏",
        "character_pinyin": "mǐn",
        "eng": "sensitive; quick",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她对别人的情感非常敏感，总是能察觉到变化。",
        "compound_pinyin": "Tā duì biérén de qínggǎn fēicháng mǐngǎn, zǒng shì néng chájúedào biànhuà.",
        "compound_definition": "She is very sensitive to others' emotions and can always sense changes.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3804,
        "character": "斜",
        "character_pinyin": "xié",
        "eng": "slanting; oblique",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "那幅画挂得有些斜，需要调整一下。",
        "compound_pinyin": "Nà fú huà guà dé yǒuxiē xié, xūyào tiáozhěng yīxià.",
        "compound_definition": "That painting is hanging at a slight angle and needs to be adjusted.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3806,
        "character": "暂",
        "character_pinyin": "zàn",
        "eng": "temporarily; for the time being",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "由于天气原因，活动暂时取消。",
        "compound_pinyin": "Yóuyú tiānqì yuányīn, huódòng zànshí qǔxiāo.",
        "compound_definition": "The event has been temporarily canceled due to weather conditions.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3808,
        "character": "朗",
        "character_pinyin": "lǎng",
        "eng": "bright; clear",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的声音朗朗上口，让人印象深刻。",
        "compound_pinyin": "Tā de shēngyīn lǎnglǎng shàngkǒu, ràng rén yìnxiàng shēnkè.",
        "compound_definition": "His voice is clear and catchy, leaving a deep impression.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3809,
        "character": "朵",
        "character_pinyin": "duǒ",
        "eng": "measure word for flowers; clusters",
        "hsk_level": 5,
        "part_of_speech": "measure word/noun",
        "compound_cantonese": "",
        "compound": "她送给我一朵美丽的玫瑰，令我感到惊喜。",
        "compound_pinyin": "Tā sòng gěi wǒ yī duǒ měilì de méiguī, lìng wǒ gǎndào jīngxǐ.",
        "compound_definition": "She gave me a beautiful rose, which surprised me.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3839,
        "character": "漠",
        "character_pinyin": "mò",
        "eng": "desert; indifferent",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的态度漠不关心，让人感到失望。",
        "compound_pinyin": "Tā de tàidù mò bù guānxīn, ràng rén gǎndào shīwàng.",
        "compound_definition": "His indifferent attitude disappointed people.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3843,
        "character": "烂",
        "character_pinyin": "làn",
        "eng": "rotten; broken",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个苹果已经烂了，不能再吃了。",
        "compound_pinyin": "Zhège píngguǒ yǐjīng lànle, bù néng zài chīle.",
        "compound_definition": "This apple is already rotten and can't be eaten anymore.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3849,
        "character": "狂",
        "character_pinyin": "kuáng",
        "eng": "crazy; mad",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他对篮球狂热，几乎每天都去打球。",
        "compound_pinyin": "Tā duì lánqiú kuángrè, jīhū měitiān dōu qù dǎqiú.",
        "compound_definition": "He is crazy about basketball and plays almost every day.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3859,
        "character": "疯",
        "character_pinyin": "fēng",
        "eng": "crazy; insane",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的行为有些疯癫，让人感到不安。",
        "compound_pinyin": "Tā de xíngwéi yǒuxiē fēngdiān, ràng rén gǎndào bù'ān.",
        "compound_definition": "His behavior is somewhat crazy, making people feel uneasy.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3860,
        "character": "瘦",
        "character_pinyin": "shòu",
        "eng": "thin; skinny",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她最近瘦了很多，朋友们都很关心她的健康。",
        "compound_pinyin": "Tā zuìjìn shòule hěn duō, péngyǒumen dōu hěn guānxīn tā de jiànkāng.",
        "compound_definition": "She has lost a lot of weight recently, and her friends are concerned about her health.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3867,
        "character": "硕",
        "character_pinyin": "shuò",
        "eng": "large; great",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他在大学里获得硕士学位，开始了新的人生阶段。",
        "compound_pinyin": "Tā zài dàxué lǐ huòdé shuòshì xuéwèi, kāishǐle xīn de rénshēng jiēduàn.",
        "compound_definition": "He earned a master's degree at university and began a new phase of life.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3868,
        "character": "硬",
        "character_pinyin": "yìng",
        "eng": "hard; tough",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个木头非常硬，制作家具非常合适。",
        "compound_pinyin": "Zhège mùtou fēicháng yìng, zhìzuò jiājù fēicháng héshì.",
        "compound_definition": "This wood is very hard, making it suitable for furniture.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3871,
        "character": "私",
        "character_pinyin": "sī",
        "eng": "private; personal",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她很注重自己的私生活，从不公开分享。",
        "compound_pinyin": "Tā hěn zhùzhòng zìjǐ de sī shēnghuó, cóng bù gōngkāi fēnxiǎng.",
        "compound_definition": "She values her private life and never shares it publicly.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3873,
        "character": "稍",
        "character_pinyin": "shāo",
        "eng": "slightly; a little",
        "hsk_level": 5,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "我稍微感到疲倦，想休息一下。",
        "compound_pinyin": "Wǒ shāowéi gǎndào píjuàn, xiǎng xiūxí yīxià.",
        "compound_definition": "I feel slightly tired and want to take a break.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3883,
        "character": "紫",
        "character_pinyin": "zǐ",
        "eng": "purple",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她穿着一件紫色的连衣裙，显得特别优雅。",
        "compound_pinyin": "Tā chuānzhuó yī jiàn zǐsè de liányīqún, xiǎndé tèbié yōuyǎ.",
        "compound_definition": "She wore a purple dress that looked particularly elegant.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3884,
        "character": "繁",
        "character_pinyin": "fán",
        "eng": "complicated;繁荣",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个城市的夜景繁华，吸引了很多游客。",
        "compound_pinyin": "Zhège chéngshì de yèjǐng fánhuá, xīyǐnle hěn duō yóukè.",
        "compound_definition": "The night view of this city is vibrant and attracts many tourists.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3892,
        "character": "聪",
        "character_pinyin": "cōng",
        "eng": "clever; intelligent",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她是一个聪明的学生，总是能很快理解老师的讲解。",
        "compound_pinyin": "Tā shì yīgè cōngmíng de xuéshēng, zǒng shì néng hěn kuài lǐjiě lǎoshī de jiǎngjiě.",
        "compound_definition": "She is a clever student who always understands the teacher's explanations quickly.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3903,
        "character": "脆",
        "character_pinyin": "cuì",
        "eng": "crispy; fragile",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个饼干非常脆，咬下去的声音很响。",
        "compound_pinyin": "Zhège bǐnggān fēicháng cuì, yǎo xiàqù de shēngyīn hěn xiǎng.",
        "compound_definition": "This biscuit is very crispy, and it makes a loud crunch when bitten.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3905,
        "character": "臭",
        "character_pinyin": "chòu",
        "eng": "smelly; stinky",
        "hsk_level": 5,
        "part_of_speech": "adjective/verb",
        "compound_cantonese": "",
        "compound": "这个垃圾散发着臭味，必须马上清理。",
        "compound_pinyin": "Zhège lājī sànfāzhe chòuwèi, bìxū mǎshàng qīnglǐ.",
        "compound_definition": "This garbage gives off a bad smell and must be cleaned up immediately.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3907,
        "character": "艰",
        "character_pinyin": "jiān",
        "eng": "difficult; hard",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这段旅程非常艰难，但她依然坚持完成。",
        "compound_pinyin": "Zhè duàn lǚchéng fēicháng jiānnán, dàn tā yīrán jiānchí wánchéng.",
        "compound_definition": "This journey was very difficult, but she persevered to complete it.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3908,
        "character": "艳",
        "character_pinyin": "yàn",
        "eng": "gorgeous; beautiful",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这幅画的色彩艳丽，令人过目不忘。",
        "compound_pinyin": "Zhè fú huà de sècǎi yànlì, lìng rén guòmù bù wàng.",
        "compound_definition": "The colors in this painting are vibrant and unforgettable.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3914,
        "character": "虚",
        "character_pinyin": "xū",
        "eng": "empty; false",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他的话听起来很虚，让人难以相信。",
        "compound_pinyin": "Tā de huà tīng qǐlái hěn xū, ràng rén nányǐ xiāngxìn.",
        "compound_definition": "His words sound empty and hard to believe.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3921,
        "character": "详",
        "character_pinyin": "xiáng",
        "eng": "detailed; elaborate",
        "hsk_level": 5,
        "part_of_speech": "adjective/verb",
        "compound_cantonese": "",
        "compound": "她对项目的计划做了详尽的说明，确保大家理解。",
        "compound_pinyin": "Tā duì xiàngmù de jìhuà zuòle xiángjìn de shuōmíng, quèbǎo dàjiā lǐjiě.",
        "compound_definition": "She provided a detailed explanation of the project plan to ensure everyone understood.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3923,
        "character": "豪",
        "character_pinyin": "háo",
        "eng": "豪华; hero; bold",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他住在一座豪华的别墅里，过着富裕的生活。",
        "compound_pinyin": "Tā zhù zài yī zuò háohuá de biéshù lǐ, guòzhe fùyù de shēnghuó.",
        "compound_definition": "He lives in a luxurious villa and leads a wealthy life.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3924,
        "character": "豫",
        "character_pinyin": "yù",
        "eng": "to be prepared; Henan province",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他们在豫省的旅行中，体验了独特的地方文化。",
        "compound_pinyin": "Tāmen zài Yùshěng de lǚxíng zhōng, tǐyànle dútè de dìfāng wénhuà.",
        "compound_definition": "During their trip to Henan province, they experienced the unique local culture.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3932,
        "character": "软",
        "character_pinyin": "ruǎn",
        "eng": "soft; gentle",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这张沙发非常软，坐上去很舒服。",
        "compound_pinyin": "Zhè zhāng shāfā fēicháng ruǎn, zuò shàngqù hěn shūfú.",
        "compound_definition": "This sofa is very soft and comfortable to sit on.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3936,
        "character": "辛",
        "character_pinyin": "xīn",
        "eng": "bitter; laborious",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "他经历了许多辛苦的日子，终于实现了自己的目标。",
        "compound_pinyin": "Tā jīnglìle xǔduō xīnkǔ de rìzi, zhōngyú shíxiànle zìjǐ de mùbiāo.",
        "compound_definition": "He went through many tough days and finally achieved his goals.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3953,
        "character": "闲",
        "character_pinyin": "xián",
        "eng": "idle; free",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她在工作之余喜欢闲逛，享受生活。",
        "compound_pinyin": "Tā zài gōngzuò zhī yú xǐhuān xián guàng, xiǎngshòu shēnghuó.",
        "compound_definition": "She enjoys wandering around in her free time to enjoy life.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3955,
        "character": "雄",
        "character_pinyin": "xióng",
        "eng": "male; heroic",
        "hsk_level": 5,
        "part_of_speech": "adjective/noun",
        "compound_cantonese": "",
        "compound": "这只雄鹰展翅高飞，展现了它的力量。",
        "compound_pinyin": "Zhè zhī xióngyīng zhǎnchì gāofēi, zhǎnxiànle tā de lìliàng.",
        "compound_definition": "The eagle soared high, showcasing its strength.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3958,
        "character": "频",
        "character_pinyin": "pín",
        "eng": "frequent; often",
        "hsk_level": 5,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她频繁地去健身房锻炼，保持身体健康。",
        "compound_pinyin": "Tā pínfán de qù jiànshēnfáng duànliàn, bǎochí shēntǐ jiànkāng.",
        "compound_definition": "She frequently goes to the gym to exercise and maintain her health.",
        "valid_sentence": "",
        "counter (45)\r": "\r"
    },
    {
        "id": 3959,
        "character": "颗",
        "character_pinyin": "kē",
        "eng": "measure word for small round objects; grain",
        "hsk_level": 5,
        "part_of_speech": "measure word/noun",
        "compound_cantonese": "",
        "compound": "他手里捧着一颗闪亮的宝石，满脸喜悦。",
        "compound_pinyin": "Tā shǒu lǐ pěngzhe yī kē shǎnliàng de bǎoshí, mǎn liǎn xǐyuè.",
        "compound_definition": "He held a shining gem in his hands, with a joyful expression.",
        "valid_sentence": ",",
        "counter (45)\r": ""
    }
]