var hskLevelZ = [
    {
        "id": 10000,
        "character": "丝",
        "character_pinyin": "sī",
        "eng": "silk, thread",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "我用皮带勃然地抽打她来惩罚她，但她的脸上却没有丝毫的痛苦。",
        "compound_pinyin": "Wǒ yòng pídài bórán dì chōuda tā lái chéngfá tā, dàn tā de liǎn shàng què méiyǒu sīháo de tòngkǔ.",
        "compound_definition": "I punished her by whipping her violently with the belt, but there was no sign of pain on her face.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10001,
        "character": "丝毫",
        "character_pinyin": "sīháo",
        "eng": "the slightest bit",
        "hsk_level": 6,
        "part_of_speech": "adverb",
        "compound_cantonese": "",
        "compound": "他做事非常认真，从不允许自己有丝毫的马虎。",
        "compound_pinyin": "Tā zuòshì fēicháng rènzhēn, cóng bù yǔnxǔ zìjǐ yǒu sīháo de mǎhu.",
        "compound_definition": "He is very serious about his work and never allows himself the slightest bit of carelessness.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10002,
        "character": "乳",
        "character_pinyin": "Rǔ",
        "eng": "Milk",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "众所周知，来自欧洲的乳制品和粮物产品的浓度比中国大陆的更高。",
        "compound_pinyin": "Zhòngsuǒzhōuzhī láizì ōuzhōu de rǔ zhìpǐn hé liáng wù chǎnpǐn de nóngdù bǐ zhōngguó dàlù de gèng gāo.\"",
        "compound_definition": "It is well known that dairy and grain products from Europe have higher concentrations than those from mainland China.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10003,
        "character": "乳头",
        "character_pinyin": "Rǔtóu",
        "eng": "Nipple",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "她在母乳喂养时发现乳头变得非常敏感，所以需要使用保护乳头的乳霜。",
        "compound_pinyin": "Tā zài mǔrǔ wèiyǎng shí fāxiàn rǔtóu biànde fēicháng mǐngǎn, suǒyǐ xūyào shǐyòng bǎohù rǔtóu de rǔshuāng.",
        "compound_definition": "She found that her nipples became very sensitive during breastfeeding, so she needed to use a protective nipple cream.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10004,
        "character": "传染",
        "character_pinyin": "chuánrǎn",
        "eng": "infect",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "由于这种感冒病毒传播速度很快，医生建议大家勤洗手，以减少传染的风险。",
        "compound_pinyin": "Yóuyú zhè zhǒng gǎnmào bìngdú chuánbò sùdù hěn kuài, yīshēng jiànyì dàjiā qín xǐshǒu, yǐ jiǎnshǎo chuánrǎn de fēngxiǎn.",
        "compound_definition": "Since this cold virus spreads quickly, doctors recommend frequent handwashing to reduce the risk of infection.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10005,
        "character": "侍",
        "character_pinyin": "shì",
        "eng": "serve, attend to",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "作为解开贞操带的交换，他必须侍奉妻子，舔她肮脏的菊花 ，并忍受她的虐待狂。",
        "compound_pinyin": "Zuòwéi jiě kāi zhēncāo dài de jiāohuàn, tā bìxū shìfèng qīzǐ, tiǎn tā āng zāng de júhuā, bìng rěnshòu tā de nüèdài kuáng.",
        "compound_definition": "In exchange for removing the chastity belt, he must serve his wife, lick her dirty asshole, and endure her sadism.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10006,
        "character": "侍奉",
        "character_pinyin": "shìfèng",
        "eng": "To serve",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "对我来说要赔钱还是你来侍奉哪个都行",
        "compound_pinyin": "Duì wǒ lái shuō yào péiqián háishì nǐ lái shìfèng nǎge dōu xíng",
        "compound_definition": "It doesn't matter to me whether you pay me or serve me.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10007,
        "character": "倾",
        "character_pinyin": "qīng",
        "eng": "lean, incline, devote",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "她倾听从主人的命令，以避免违下可能被理解为反抗的错误。",
        "compound_pinyin": "Tā qīngtīng cóng zhǔrén de mìnglìng, yǐ bìmiǎn wéi xià kěnéng bèi lǐjiě wèi fǎnkàng de cuòwù.",
        "compound_definition": "She listens to her master's orders to avoid mistakes that could be interpreted as rebellion.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10008,
        "character": "偏",
        "character_pinyin": "piān",
        "eng": "tilted, biased, insistently",
        "hsk_level": 6,
        "part_of_speech": "adjective/adverb",
        "compound_cantonese": "",
        "compound": "尽管所有人都劝他不要再执着于过去，但他偏偏不愿意放手，总觉得那些过去的日子才是他人生中最美好的时光。",
        "compound_pinyin": "Jǐnguǎn suǒyǒu rén dōu quàn tā bùyào zài zhízhuó yú guòqù, dàn tā piānpiān bù yuànyì fàngshǒu, zǒng juédé nàxiē guòqù de rìzǐ cái shì tā rénshēng zhōng zuì měihǎo de shíguāng.",
        "compound_definition": "Although everyone advised him not to cling to the past, he was unwilling to let go and always felt that those past days were the best time in his life.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10009,
        "character": "勃",
        "character_pinyin": "bó",
        "eng": "vigorous, sudden",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "蠢笨，不要勃然开始挑逗我的阴蒂并说我的淫水是酸溜溜的！",
        "compound_pinyin": "Chǔnbèn, bùyào bórán kāishǐ tiǎodòu wǒ de yīndì bìng shuō wǒ de yínshuǐ shì suānliūliū de!",
        "compound_definition": "Don't get so excited and start teasing my clitoris and telling me my juices are sour, idiot!",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10010,
        "character": "勉",
        "character_pinyin": "miǎn",
        "eng": "encourage",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "勉励幼儿园学生顺应并尊敬老师，如果他们表现出烂的态度，就会受到打击。",
        "compound_pinyin": "Miǎnlì yòu'éryuán xuéshēng shùnyìng bìng zūnjìng lǎoshī, rúguǒ tāmen biǎoxiàn chū làn de tàidù, jiù huì shòudào dǎjí.",
        "compound_definition": "Kindergarten students are encouraged to obey and respect their teachers and will be punished if they display a bad attitude.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10011,
        "character": "勉强",
        "character_pinyin": "miǎnqiáng",
        "eng": "to do reluctantly",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这顿饭他吃得很慢，看起来是勉强自己吃下去的，似乎没有什么胃口。",
        "compound_pinyin": "Zhè dùn fàn tā chī de hěn màn, kànqǐlái shì miǎnqiǎng zìjǐ chī xiàqù de, sìhū méiyǒu shénme wèikǒu.",
        "compound_definition": "He ate this meal very slowly, and it seemed like he was forcing himself to eat, as if he had no appetite.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10012,
        "character": "厕",
        "character_pinyin": "cè",
        "eng": "toilet",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "厕所里有一个荡妇正在露出她的乳房和乳头。",
        "compound_pinyin": "Cèsuǒ li yǒu yīgè dàng fù zhèngzài lùchū tā de rǔfáng hé rǔtóu.",
        "compound_definition": "There was a slut in the toilet showing her breasts and nipples.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10013,
        "character": "反抗",
        "character_pinyin": "fǎnkàng",
        "eng": "resist, rebel",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "面对强权与压迫，他不愿意低头，而是选择勇敢地反抗，不管前方的道路多么艰难，他都要坚持到底。",
        "compound_pinyin": "Miànduì qiángquán yǔ yāpò, tā bù yuànyì dītóu, ér shì xuǎnzé yǒnggǎn de fǎnkàng, bùguǎn qiánfāng de dàolù duōme jiānnán, tā dōu yào jiānchí dàodǐ.",
        "compound_definition": "Faced with tyranny and oppression, he refused to bow down and instead chose to resist bravely, determined to persist no matter how difficult the road ahead might be.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10014,
        "character": "受虐倾向",
        "character_pinyin": "shòunüè qīngxiàng",
        "eng": "masochistic tendencies",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他明知道对方总是伤害自己，却仍然无法割舍这段关系，这种受虐倾向让他的朋友们感到既心疼又无奈。",
        "compound_pinyin": "Tā míng zhīdào duìfāng zǒng shì shānghài zìjǐ, què réngrán wúfǎ gēshě zhè duàn guānxì, zhè zhǒng shòunüè qīngxiàng ràng tā de péngyǒumen gǎndào jì xīnténg yòu wúnài.",
        "compound_definition": "He knew very well that the other person kept hurting him, yet he still couldn’t let go of the relationship. His masochistic tendencies made his friends feel both heartbroken and helpless.",
        "valid_sentence": "",
        "counter (118)\r": 4
    },
    {
        "id": 10015,
        "character": "君",
        "character_pinyin": "Jūn",
        "eng": "Gentleman",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "打扰一下，君子。请问厕所在哪儿？我和我兄弟想找个地方聊聊天。",
        "compound_pinyin": "Dǎrǎo yīxià, jūnzǐ. Qǐngwèn cèsuǒ zài nǎ'er? Wǒ hé wǒ xiōngdì xiǎng zhǎo gè dìfāng liáo liáotiān.",
        "compound_definition": "Excuse me, sir.,Where is the toilet, please?,My brother and I need a place to chat.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10016,
        "character": "吮",
        "character_pinyin": "shǔn",
        "eng": "suck",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "小宝宝躺在妈妈怀里，安静地吮着奶嘴。",
        "compound_pinyin": "Xiǎo bǎobǎo tǎng zài māmā huái lǐ, ānjìng de shǔnzhe nǎizuǐ.",
        "compound_definition": "The baby lay in his mother's arms, quietly sucking on his pacifier.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10017,
        "character": "吻",
        "character_pinyin": "Wěn",
        "eng": "Kiss",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "当这个淫荡的婊子开始亲吻这个害羞而孤独的男孩时，他的肉棒就变硬了，并在裤子里射了精。",
        "compound_pinyin": "Dāng zhège yíndàng de biǎo zǐ kāishǐ qīnwěn zhège hàixiū ér gūdú de nánhái shí, tā de ròubàng jiù biàn yìngle, bìng zài kùzǐ lǐ shèle jīng.",
        "compound_definition": "When this slutty bitch starts kissing this shy and lonely boy, his cock gets hard and he cums in his pants.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10018,
        "character": "吞",
        "character_pinyin": "tūn",
        "eng": "swallow, engulf",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "在妻子勃然吸吮着肉棒之后，精液射得非常多，精液都从她的嘴里溢出来，她很难全部吞下去。",
        "compound_pinyin": "Zài qīzǐ bórán xīshǔnzhe ròubàng zhīhòu, jīngyè shè dé fēicháng duō, jīngyè dōu cóng tā de zuǐ lǐ yìchū lái, tā hěn nán quánbù tūn xiàqù.",
        "compound_definition": "After my wife sucked the cock vigorously, the cum shot out so much that it overflowed from her mouth and it was difficult for her to swallow it all.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10019,
        "character": "哎",
        "character_pinyin": "Āi",
        "eng": "Hey!",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀！我放的屁太臭了，我老婆都开始骂我了。我怕等会儿要受罚。",
        "compound_pinyin": "Āiyā! Wǒ fàng de pì tài chòule, wǒ lǎopó dōu kāishǐ mà wǒle. Wǒ pà děng huì er yào shòufá.",
        "compound_definition": "Ouch! My fart was so smelly that my wife started scolding me. I'm afraid I'll be punished later.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10020,
        "character": "哎呀",
        "character_pinyin": "Āiyā",
        "eng": "Aiya",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀，我的手机掉进水里了，快帮我想想办法！",
        "compound_pinyin": "Āiyā, wǒ de shǒujī diào jìn shuǐ lǐ le, kuài bāng wǒ xiǎngxiǎng bànfǎ!",
        "compound_definition": "Oh no, my phone fell into the water, please help me think of a solution!",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10021,
        "character": "啦",
        "character_pinyin": "la",
        "eng": "la",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "你别这么冷漠，安慰我啦。",
        "compound_pinyin": "Nǐ bié zhème lěngmò, ānwèi wǒ la.",
        "compound_definition": "Don't be so cold, comfort me.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10022,
        "character": "嗯",
        "character_pinyin": "Ǹg",
        "eng": "um",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "嗯…请温柔一点。嘛嘛，如果你愿意，你可以更用力一点，但我的屁股很敏感啦。",
        "compound_pinyin": "Ǹg…qǐng wēnróu yīdiǎn. Ma ma, rúguǒ nǐ yuànyì, nǐ kěyǐ gèng yònglì yīdiǎn, dàn wǒ de pìgu hěn mǐngǎn la.",
        "compound_definition": "Um... please be gentle. Um, you can be harder if you want, but my ass is very sensitive.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10023,
        "character": "嘛",
        "character_pinyin": "ma",
        "eng": "well",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "糟糕…嘛…我没能及时将我的肉棒从你的小穴中拔出来啦。",
        "compound_pinyin": "Zāogāo…ma…wǒ méi néng jíshí jiāng wǒ de ròubàng cóng nǐ de xiǎoxué zhōng bá chūlái la.",
        "compound_definition": "Oops…well…I couldn’t pull my cock out of your pussy in time.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10024,
        "character": "壮",
        "character_pinyin": "zhuàng",
        "eng": "strong, robust",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "那些翘楚和壮观男人们围在他的妻子身边，妻子吸吮着他们的龟头。",
        "compound_pinyin": "Nàxiē qiáochǔ hé zhuàngguān nánrénmen wéi zài tā de qīzǐ shēnbiān, qīzǐ xīshǔnzhe tāmen de guītóu.",
        "compound_definition": "Those outstanding and spectacular men gathered around his wife, who sucked their glans.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10025,
        "character": "处男",
        "character_pinyin": "Chǔnán",
        "eng": "Virgin",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他害羞地承认自己还是处男，因为从未谈过恋爱。",
        "compound_pinyin": "Tā hàixiū de chéngrèn zìjǐ háishì chǔnán, yīnwèi cóngwèi tánguò liàn'ài.",
        "compound_definition": "He shyly admitted that he was still a virgin because he had never been in a relationship before.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10026,
        "character": "奉",
        "character_pinyin": "fèng",
        "eng": "offer, dedicate, serve",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "她丝毫羞耻地盯视着丈夫的眼睛，交出了自己的菊穴贞操，以此证明她对新主人的奉献。",
        "compound_pinyin": "Tā sīháo xiūchǐ de dīng shìzhe zhàngfū de yǎnjīng, jiāo chūle zìjǐ de jú xué zhēncāo, yǐ cǐ zhèngmíng tā duì xīn zhǔrén de fèngxiàn.",
        "compound_definition": "She stared into her husband's eyes without any shame and surrendered her anal virginity to prove her devotion to her new master.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10027,
        "character": "妙",
        "character_pinyin": "Miào",
        "eng": "Wonderful",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这荡妇巧妙地引诱她的炮友阻碍老师收集文献。",
        "compound_pinyin": "Zhè dàng fù qiǎomiào de yǐnyòu tā de pào yǒu zǔ'ài lǎoshī shōují wénxiàn.",
        "compound_definition": "The slut cleverly seduces her fuck buddy into hindering the teacher's collection of literature.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10028,
        "character": "姿",
        "character_pinyin": "Zī",
        "eng": "Posture",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "而我的妻子，原本聪明而冷静的人，但是在这些年轻强壮的男性面前也只能表现出母狗的姿态",
        "compound_pinyin": "Ér wǒ de qīzǐ, yuánběn cōngmíng ér lěngjìng de rén, dànshì zài zhèxiē niánqīng qiángzhuàng de nánxìng miànqián yě zhǐ néng biǎoxiàn chū mǔgǒu de zītài",
        "compound_definition": "My wife, who was originally smart and calm, could only behave like a bitch in front of these young and strong men.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10029,
        "character": "婊",
        "character_pinyin": "biǎo",
        "eng": "prostitute",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个年轻的婊子到处传染班上那些不知情的处女，满足她们的性欲。",
        "compound_pinyin": "Zhège niánqīng de biǎo zǐ dàochù chuánrǎn bān shàng nàxiē bùzhī qíng de chǔnǚ, mǎnzú tāmen dì xìngyù.",
        "compound_definition": "This young bitch goes around infecting the unsuspecting virgins in her class and satisfying their sexual desires.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10030,
        "character": "婊子",
        "character_pinyin": "biǎozǐ",
        "eng": "bitch",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他说话太难听了，随便骂人婊子，让大家都觉得不舒服。",
        "compound_pinyin": "Tā shuōhuà tài nántīng le, suíbiàn mà rén biǎozi, ràng dàjiā dōu juéde bù shūfú.",
        "compound_definition": "His words were too offensive; calling someone a \"bitch\" so casually made everyone uncomfortable.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10031,
        "character": "孤",
        "character_pinyin": "gū",
        "eng": "solitary",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "孤独的女人被炮友甩了，大喊“肏，我好寂寞啊！”",
        "compound_pinyin": "Gūdú de nǚrén bèi pào yǒu shuǎile, dà hǎn “cào, wǒ hǎo jìmò a!”",
        "compound_definition": "Lonely woman gets dumped by her sex partner and screams “Fuck, I'm so lonely!”",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10032,
        "character": "害羞",
        "character_pinyin": "Hàixiū",
        "eng": "Shy",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她性格内向，见到陌生人时总是低着头，显得非常害羞。",
        "compound_pinyin": "Tā xìnggé nèixiàng, jiàndào mòshēngrén shí zǒng shì dīzhe tóu, xiǎnde fēicháng hàixiū.",
        "compound_definition": "She is introverted and always lowers her head when meeting strangers, looking very shy.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10033,
        "character": "寂",
        "character_pinyin": "Jì",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这位四川君子虽然巧妙，但是却常常因为寂寞而哭泣。",
        "compound_pinyin": "Zhè wèi sìchuān jūnzǐ suīrán qiǎomiào, dànshì què chángcháng yīnwèi jìmò ér kūqì.",
        "compound_definition": "Although this Sichuan gentleman was clever, he often cried because of loneliness.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10034,
        "character": "寂寞",
        "character_pinyin": "Jìmò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "自从搬到这座城市后，他没有什么朋友，经常一个人待在家里感到很寂寞。",
        "compound_pinyin": "Zìcóng bān dào zhè zuò chéngshì hòu, tā méiyǒu shénme péngyǒu, jīngcháng yīgè rén dāi zài jiālǐ gǎndào hěn jìmò.",
        "compound_definition": "Since moving to this city, he hasn't made many friends and often stays at home alone, feeling very lonely.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10035,
        "character": "寞",
        "character_pinyin": "mò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我希望有人能治愈我这种无法再忍受的寂寞。",
        "compound_pinyin": "Wǒ xīwàng yǒurén néng zhìyù wǒ zhè zhǒng wúfǎ zài rěnshòu de jìmò.",
        "compound_definition": "I hope someone can heal this unbearable loneliness.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10036,
        "character": "尿",
        "character_pinyin": "Niào",
        "eng": "Urine",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "哎呀！我因为喝醉了而错过了上厕所的机会，现在地板上全是尿液。我应该向其他客人道歉。",
        "compound_pinyin": "Āiyā! Wǒ yīnwèi hē zuìle ér cuòguòle shàng cèsuǒ de jīhuì, xiànzài dìbǎn shàng quán shì niào yè. Wǒ yīnggāi xiàng qítā kèrén dàoqiàn.",
        "compound_definition": "Oops!,I missed the bathroom break because I was drunk and now there is urine all over the floor.,I should apologize to the other guests.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10037,
        "character": "屁",
        "character_pinyin": "Pì",
        "eng": "Fart",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个低俗的男人，觉得亲吻女友柔软的屁股是一件很爽的事情。",
        "compound_pinyin": "Zhège dīsú de nánrén, juédé qīnwěn nǚyǒu róuruǎn de pìgu shì yī jiàn hěn shuǎng de shìqíng.",
        "compound_definition": "This vulgar man thinks it is a very pleasant thing to kiss his girlfriend's soft butt.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10038,
        "character": "屁股",
        "character_pinyin": "Pìgu",
        "eng": "Butt",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "他不小心摔倒了，一下子坐在地上，屁股都摔疼了。",
        "compound_pinyin": "Tā bù xiǎoxīn shuāidǎo le, yīxiàzi zuò zài dìshàng, pìgu dōu shuāi téng le.",
        "compound_definition": "He accidentally fell and landed on the ground, making his butt hurt.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10039,
        "character": "川",
        "character_pinyin": "Chuān",
        "eng": "Sichuan",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "四川以其巨大的田野，温泉和激烈的棒球竞赛而闻名。",
        "compound_pinyin": "Sìchuān yǐ qí jùdà de tiányě, wēnquán hé jīliè de bàngqiú jìngsài ér wénmíng.",
        "compound_definition": "Sichuan is famous for its huge fields, hot springs and fierce baseball competition.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10042,
        "character": "性欲",
        "character_pinyin": "Xìngyù",
        "eng": "Sexual desire",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "长期的压力和疲劳可能会影响一个人的性欲，导致对亲密关系失去兴趣。",
        "compound_pinyin": "Chángqí de yālì hé píláo kěnéng huì yǐngxiǎng yīgè rén de xìngyù, dǎozhì duì qīnmì guānxì shīqù xìngqù.",
        "compound_definition": "Long-term stress and fatigue may affect a person's sexual desire, leading to a loss of interest in intimacy.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10043,
        "character": "惩",
        "character_pinyin": "chéng",
        "eng": "punish, discipline",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "不鼓励父母使用皮带惩罚孩子，因为这会损害他们的姿势。",
        "compound_pinyin": "Bù gǔlì fùmǔ shǐyòng pídài chéngfá háizǐ, yīnwèi zhè huì sǔnhài tāmen de zīshì.",
        "compound_definition": "Parents are discouraged from using belts to punish their children as it can harm their posture.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10044,
        "character": "愈",
        "character_pinyin": "Yù",
        "eng": "Heal",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这位欧洲护士经常用她的舌头来治愈病人的性欲。",
        "compound_pinyin": "Zhè wèi ōuzhōu hùshì jīngcháng yòng tā de shétou lái zhìyù bìngrén dì xìngyù.",
        "compound_definition": "This European nurse often used her tongue to heal her patients' sexual desires.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10045,
        "character": "抗",
        "character_pinyin": "kàng",
        "eng": "resist, fight against",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "主播利用自己的隐私权来反抗那些试图利用她可羞耻的秘密的粉丝。",
        "compound_pinyin": "Zhǔbō lìyòng zìjǐ de yǐnsī quán lái fǎnkàng nàxiē shìtú lìyòng tā kě xiūchǐ de mìmì de fěnsī.",
        "compound_definition": "The streamer used her right to privacy to fight back against fans who tried to exploit her shameful secrets.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10046,
        "character": "抚",
        "character_pinyin": "fǔ",
        "eng": "stroke, comfort",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "奶奶轻轻地抚着我的头发，温柔地讲着故事。",
        "compound_pinyin": "Nǎinai qīngqīng de fǔzhe wǒ de tóufǎ, wēnróu de jiǎngzhe gùshì.",
        "compound_definition": "Grandma gently stroked my hair and told a story softly.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10047,
        "character": "抱歉",
        "character_pinyin": "Bàoqiàn",
        "eng": "Feel sorry",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我昨天忘了回复你的信息，真是抱歉，希望没有耽误你的事情。",
        "compound_pinyin": "Wǒ zuótiān wàng le huífù nǐ de xìnxī, zhēn shì bàoqiàn, xīwàng méiyǒu dānwù nǐ de shìqíng.",
        "compound_definition": "I forgot to reply to your message yesterday, I'm really sorry, and I hope I didn't delay anything for you.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10048,
        "character": "接吻",
        "character_pinyin": "Jiēwěn",
        "eng": "Kiss",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他们在电影的最后一幕深情地接吻，展现了彼此的爱意。",
        "compound_pinyin": "Tāmen zài diànyǐng de zuìhòu yīmù shēnqíng de jiēwěn, zhǎnxiàn le bǐcǐ de àiyì.",
        "compound_definition": "They kissed passionately in the final scene of the movie, showing their love for each other.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10049,
        "character": "撒",
        "character_pinyin": "sā/sǎ",
        "eng": "scatter, spread, let go",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "她必须忍受撒腿、让主人抚摸阴蒂的羞辱，而她的粉丝们则向她支付金钱奖励。",
        "compound_pinyin": "Tā bìxū rěnshòu sātuǐ, ràng zhǔrén fǔmō yīndì de xiūrù, ér tā de fěnsīmen zé xiàng tā zhīfù jīnqián jiǎnglì.",
        "compound_definition": "She has to endure the humiliation of spreading her legs and letting her master touch her clitoris, while her fans pay her monetary rewards.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10050,
        "character": "柔",
        "character_pinyin": "róu",
        "eng": "soft",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "哎呀！亚洲女人的舌头好柔软，光是亲吻就感觉淫荡至极啦。",
        "compound_pinyin": "Āiyā! Yàzhōu nǚrén de shétou hǎo róuruǎn, guāng shì qīnwěn jiù gǎnjué yíndàng zhìjí la.",
        "compound_definition": "Oh my!,Asian women's tongues are so soft, just kissing them makes me feel extremely horny.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10051,
        "character": "欧",
        "character_pinyin": "ōu",
        "eng": "Europe",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我怀念那位专门做按摩的欧洲女人，她的按摩手法非常温柔。",
        "compound_pinyin": "Wǒ huáiniàn nà wèi zhuānmén zuò ànmó de ōuzhōu nǚrén, tā de ànmó shǒufǎ fēicháng wēnróu.",
        "compound_definition": "I miss the European woman who specialized in massage and her gentle touch.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10052,
        "character": "欲",
        "character_pinyin": "Yù",
        "eng": "Want",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我对焗米饭的欲望让我发疯，特别是当我闻到它的味道时，所以请给我一个鼻夹！",
        "compound_pinyin": "Wǒ duì jú mǐfàn de yùwàng ràng wǒ fāfēng, tèbié shì dāng wǒ wén dào tā de wèidào shí, suǒyǐ qǐng gěi wǒ yīgè bí jiā!",
        "compound_definition": "My craving for baked rice drives me crazy, especially when I smell it, so give me a nose clip please!",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10053,
        "character": "欺",
        "character_pinyin": "qī",
        "eng": "deceive, bully",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "我的后辈发现我的耻辱后，她无视我的隐私权，对我进行欺压和虐待。",
        "compound_pinyin": "Wǒ de hòubèi fāxiàn wǒ de chǐrǔ hòu, tā wúshì wǒ de yǐnsī quán, duì wǒ jìnxíng qīyā hé nüèdài.",
        "compound_definition": "When my junior discovered my shame, she ignored my right to privacy and bullied and abused me.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10054,
        "character": "欺负",
        "character_pinyin": "qīfu",
        "eng": "bully, mistreat",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "小时候，他因为性格内向，总是被一些同学欺负，但后来他学会了勇敢面对，不再选择忍气吞声，而是坚定地保护自己，并帮助其他被欺负的同学。",
        "compound_pinyin": "Xiǎoshíhòu, tā yīnwèi xìnggé nèixiàng, zǒng shì bèi yīxiē tóngxué qīfu, dàn hòulái tā xuéhuì le yǒnggǎn miànduì, bù zài xuǎnzé rěnqìtūnshēng, ér shì jiāndìng de bǎohù zìjǐ, bìng bāngzhù qítā bèi qīfu de tóngxué.",
        "compound_definition": "As a child, he was often bullied by some classmates because of his introverted personality, but later he learned to face them bravely, no longer choosing to endure it silently, but instead standing firm to protect himself and help other bullied classmates.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10055,
        "character": "歉",
        "character_pinyin": "Qiàn",
        "eng": "Apologize",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我必须道歉。虽然我试图在厕所小便，但我的尿液洒在地板上，现在一切都很润滑。",
        "compound_pinyin": "Wǒ bìxū dàoqiàn. Suīrán wǒ shìtú zài cèsuǒ xiǎobiàn, dàn wǒ de niào yè sǎ zài dìbǎn shàng, xiànzài yīqiè dōu hěn rùnhuá.",
        "compound_definition": "I must apologize.,Although I tried to pee in the toilet, my urine spilled on the floor and now everything is lubricated.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10056,
        "character": "泣",
        "character_pinyin": "qì",
        "eng": "weep",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我的炮友温柔地按摩着我的肉棒，而她因被男友骗人而被甩了而害羞地哭泣。",
        "compound_pinyin": "Wǒ de pào yǒu wēnróu de ànmózhe wǒ de ròubàng, ér tā yīn bèi nányǒu piàn rén ér bèi shuǎile ér hàixiū de kūqì.",
        "compound_definition": "My fuck buddy gently massaged my cock while she cried shyly because she was dumped by her boyfriend who cheated on her.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10057,
        "character": "洲",
        "character_pinyin": "zhōu",
        "eng": "Europe / continent",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "那个提倡男人应该用舌头舔妻子阴道的亚洲女人让我感到非常害羞。",
        "compound_pinyin": "Nàgè tíchàng nánrén yīnggāi yòng shétou tiǎn qīzǐ yīndào de yàzhōu nǚrén ràng wǒ gǎndào fēicháng hàixiū.",
        "compound_definition": "I'm really embarrassed by the Asian woman who advocates that men should lick their wives' vaginas with their tongues.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10058,
        "character": "液",
        "character_pinyin": "yè",
        "eng": "Liquid",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个瘦小的大欧派强迫君子把她小穴里的尿液全部舔掉。",
        "compound_pinyin": "Zhège shòuxiǎo de dà ōu pài qiǎngpò jūnzǐ bǎ tā xiǎoxué lǐ de niào yè quánbù tiǎn diào.",
        "compound_definition": "This skinny big boobed girl forces a gentleman to lick all the urine out of her pussy.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10059,
        "character": "淫",
        "character_pinyin": "Yín",
        "eng": "Lewd",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她是那种如果混蛋把她绑在床上，锁在房间里并把她露出网上，她就会漏出淫水的女人。",
        "compound_pinyin": "Tā shì nà zhǒng rúguǒ húndàn bǎ tā bǎng zài chuángshàng, suǒ zài fángjiān lǐ bìng bǎ tā lùchū wǎngshàng, tā jiù huì lòuchū yínshuǐ de nǚrén.",
        "compound_definition": "She's the kind of woman who would leak juice if some asshole tied her to a bed, locked her in a room and exposed her online.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10060,
        "character": "淫水",
        "character_pinyin": "Yínshuǐ",
        "eng": "Sexual secretion",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "当她玩弄自己的肛门时，她无法停止流出淫水。",
        "compound_pinyin": "Dāng tā wànnòng zìjǐ de gāngmén shí, tā wúfǎ tíngzhǐ liúchū yínshuǐ.",
        "compound_definition": "She couldn't stop leaking juices while she played with her anus.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10061,
        "character": "混",
        "character_pinyin": "Hùn",
        "eng": "Mix",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "那个君子是个混蛋，经常用金钱诱惑穷困的女人，强迫她们顺从。",
        "compound_pinyin": "Nàgè jūnzǐ shìgè húndàn, jīngcháng yòng jīnqián yòuhuò qióngkùn de nǚrén, qiǎngpò tāmen shùncóng.",
        "compound_definition": "That gentleman is a bastard who often uses money to seduce poor women and force them to obey.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10062,
        "character": "混蛋",
        "character_pinyin": "Húndàn",
        "eng": "Asshole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个笨蛋的混蛋把车开进了我的餐馆，现在政府要罚款他三百万人民币。",
        "compound_pinyin": "Zhège bèndàn de húndàn bǎ chē kāi jìnle wǒ de cānguǎn, xiànzài zhèngfǔ yào fákuǎn tā sānbǎi wàn rénmínbì.",
        "compound_definition": "This dumb bastard drove his car into my restaurant and now the government is going to fine him three million RMB.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10063,
        "character": "温柔",
        "character_pinyin": "wēnróu",
        "eng": "gentle",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她的声音很温柔，总是让人感到放松和安心。",
        "compound_pinyin": "Tā de shēngyīn hěn wēnróu, zǒngshì ràng rén gǎndào fàngsōng hé ānxīn.",
        "compound_definition": "Her voice is very gentle, always making people feel relaxed and reassured.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10064,
        "character": "湿漉漉",
        "character_pinyin": "Shīlùlù",
        "eng": "Wet",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "外面刚下过雨，他的衣服和头发都变得湿漉漉的。",
        "compound_pinyin": "Wàimiàn gāng xiàguò yǔ, tā de yīfú hé tóufà dōu biàn de shīlùlù de.",
        "compound_definition": "It just rained outside, and his clothes and hair became soaking wet.",
        "valid_sentence": "",
        "counter (118)\r": 3
    },
    {
        "id": 10065,
        "character": "溜",
        "character_pinyin": "liū",
        "eng": "slip away, sneak off",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "他本来应该留在办公室完成报告，但他趁领导不注意，悄悄地溜了出去，跑到附近的咖啡馆，一边喝着咖啡，一边刷着手机，完全没有工作的紧迫感。",
        "compound_pinyin": "Tā běnlái yīnggāi liú zài bàngōngshì wánchéng bàogào, dàn tā chèn lǐngdǎo bù zhùyì, qiāoqiāo de liū le chūqù, pǎo dào fùjìn de kāfēiguǎn, yībiān hēzhe kāfēi, yībiān shuāzhe shǒujī, wánquán méiyǒu gōngzuò de jǐnpògǎn.",
        "compound_definition": "He was supposed to stay in the office to finish his report, but he sneaked out when his boss wasn’t paying attention, heading to a nearby café where he sipped coffee and scrolled through his phone, feeling no sense of urgency about work.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10066,
        "character": "溢",
        "character_pinyin": "yì",
        "eng": "overflow, brim over",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "当她听到自己获得了比赛的第一名时，激动得眼泪都快要溢出来了，她紧紧地抱住朋友，嘴里不停地说着感谢的话。",
        "compound_pinyin": "Dāng tā tīngdào zìjǐ huòdé le bǐsài de dì yī míng shí, jīdòng de yǎnlèi dōu kuàiyào yì chūlái le, tā jǐnjǐn de bàozhù péngyǒu, zuǐlǐ bùtíng de shuōzhe gǎnxiè de huà.",
        "compound_definition": "When she heard that she had won first place in the competition, she was so excited that her tears almost overflowed. She hugged her friend tightly and kept expressing her gratitude.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10067,
        "character": "漉",
        "character_pinyin": "Lù",
        "eng": "Filter liquids",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "嗯，抱歉，你的手态湿漉漉了，所以我不想握住它们。",
        "compound_pinyin": "Ǹg, bàoqiàn, nǐ de shǒu tài shīlùlùle, suǒyǐ wǒ bùxiǎng wò zhù tāmen.",
        "compound_definition": "Um, sorry, your hands are wet, so I don't want to hold them.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10068,
        "character": "炮",
        "character_pinyin": "Pào",
        "eng": "Firecracker / cannon",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我把我的炮友绑起来，丢在一片空地田野，这让她疯狂起来，拿着长矛追着我，但我用盾牌挡住了她。",
        "compound_pinyin": "Wǒ bǎ wǒ de pào yǒu bǎng qǐlái, diū zài yīpiàn kòngdì tiányě, zhè ràng tā fēngkuáng qǐlái, názhe cháng máo zhuīzhe wǒ, dàn wǒ yòng dùnpái dǎngzhùle tā.",
        "compound_definition": "I tied up my fuck buddy and dumped her in an empty field, which made her go crazy and she chased me with a spear, but I held her off with my shield.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10069,
        "character": "焗",
        "character_pinyin": "jú",
        "eng": "baked",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "夕阳下，她在中央公园向我挥手。我们约好一起吃焗饭。",
        "compound_pinyin": "Xīyáng xià, tā zài zhōngyāng gōngyuán xiàng wǒ huīshǒu. Wǒmen yuē hǎo yīqǐ chī jú fàn.",
        "compound_definition": "She waved to me in Central Park at sunset.,We made an appointment to have baked rice together.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10070,
        "character": "煽",
        "character_pinyin": "shān",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "厨师煽动人群扰乱钢琴演，向任何能抢走玉饰的人提供焗米饭。",
        "compound_pinyin": "Chúshī shāndòng rénqún rǎoluàn gāngqín yǎn, xiàng rènhé néng qiǎng zǒu yù shì de rén tígōng jú mǐfàn.",
        "compound_definition": "The chef incites the crowd to disrupt the piano performance, offering baked rice to anyone who can grab the jade ornament.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10071,
        "character": "煽动",
        "character_pinyin": "shāndòng",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他在社交媒体上发布了一些极端言论，试图煽动人们的愤怒。",
        "compound_pinyin": "Tā zài shèjiāo méitǐ shàng fābù le yīxiē jíduān yánlùn, shìtú shāndòng rénmen de fènnù.",
        "compound_definition": "He posted some extreme comments on social media, trying to incite people's anger.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10072,
        "character": "爽",
        "character_pinyin": "Shuǎng",
        "eng": "Cool",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我不骗你，舔着一个又矮又瘦的漂亮女孩小穴里的尿液，感觉很爽。",
        "compound_pinyin": "Wǒ bù piàn nǐ, tiǎnzhe yīgè yòu ǎi yòu shòu de piàoliang nǚhái xiǎoxué lǐ de niào yè, gǎnjué hěn shuǎng.",
        "compound_definition": "I kid you not, it felt really good licking the piss out of a short, skinny pretty girl's pussy.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10073,
        "character": "甩",
        "character_pinyin": "shuǎi",
        "eng": "throw",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "被婊子甩了之后，孤独的男孩只能一边在厕所里自慰，一边听着她吸另一个男人的肉棒。",
        "compound_pinyin": "Bèi biǎo zǐ shuǎi liǎo zhīhòu, gūdú de nánhái zhǐ néng yībiān zài cèsuǒ lǐ zìwèi, yībiān tīngzhe tā xī lìng yīgè nánrén de ròubàng.",
        "compound_definition": "After being dumped by a bitch, the lonely boy can only masturbate in the bathroom while listening to her sucking another man's cock.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10074,
        "character": "甩被了",
        "character_pinyin": "bèi shuǎile",
        "eng": "dumped",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他早上起床太匆忙，直接甩被了就跑去上班了。",
        "compound_pinyin": "Tā zǎoshang qǐchuáng tài cōngmáng, zhíjiē shuǎi bèi le jiù pǎo qù shàngbān le.",
        "compound_definition": "He got up in a hurry this morning, threw off the blanket, and rushed to work.",
        "valid_sentence": "",
        "counter (118)\r": 3
    },
    {
        "id": 10075,
        "character": "田",
        "character_pinyin": "tián",
        "eng": "field",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这位美妙的女孩邀请我去四川的一片空田野，并愿意为我治愈伤。",
        "compound_pinyin": "Zhè wèi měimiào de nǚhái yāoqǐng wǒ qù sìchuān de yīpiàn kōng tiányě, bìng yuànyì wèi wǒ zhìyù shāng.",
        "compound_definition": "This wonderful girl invited me to an empty field in Sichuan and offered to heal my wounds.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10076,
        "character": "盯",
        "character_pinyin": "dīng",
        "eng": "stare at, fix one's eyes on",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "当这位壮丽的炮友将他的肉棒插入妻子的阴道时，乌龟男人只能盯着他的妻子，并抚摸着自己的肉棒。",
        "compound_pinyin": "Dāng zhè wèi zhuànglì de pào yǒu jiāng tā de ròubàng chārù qīzǐ de yīndào shí, wūguī nánrén zhǐ néng dīngzhe tā de qīzǐ, bìng fǔmōzhe zìjǐ de ròubàng.",
        "compound_definition": "The cuckold man can only stare at his wife and stroke his cock as the magnificent fuck buddy inserts his cock into his wife’s vagina.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10077,
        "character": "真扫兴",
        "character_pinyin": "Zhēn săoxìng",
        "eng": "What a bummer",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "我们正玩得开心，他突然说要走，真是真扫兴！",
        "compound_pinyin": "Wǒmen zhèng wán de kāixīn, tā tūrán shuō yào zǒu, zhēn shì zhēn sǎoxìng!",
        "compound_definition": "We were having fun, and he suddenly said he had to leave—what a bummer!",
        "valid_sentence": "",
        "counter (118)\r": 3
    },
    {
        "id": 10078,
        "character": "破处",
        "character_pinyin": "Pòchù",
        "eng": "Losing virginity",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我最大的耻辱是在我十八岁的时候将我的童贞给了学校的荡妇。",
        "compound_pinyin": "Wǒ zuìdà de chǐrǔ shì zài wǒ shíbā suì de shíhòu jiāng wǒ de tóngzhēn gěile xuéxiào de dàng fù.",
        "compound_definition": "My biggest shame was losing my virginity to a school slut when I was eighteen.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10079,
        "character": "穴",
        "character_pinyin": "xué",
        "eng": "hole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "她的小穴有美妙的治愈效果，这煽动了我，让我哭泣，感觉太爽了。",
        "compound_pinyin": "Tā de xiǎoxué yǒu měimiào de zhìyù xiàoguǒ, zhè shāndòngle wǒ, ràng wǒ kūqì, gǎnjué tài shuǎngle.",
        "compound_definition": "Her pussy had a wonderful healing quality that turned me on and made me cry and it felt so good.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10080,
        "character": "粉",
        "character_pinyin": "fěn",
        "eng": "powder, pink",
        "hsk_level": 6,
        "part_of_speech": "noun/adjective",
        "compound_cantonese": "",
        "compound": "她今天穿了一件粉色的连衣裙，看起来非常温柔可爱。",
        "compound_pinyin": "Tā jīntiān chuānle yí jiàn fěnsè de liányīqún, kàn qǐlái fēicháng wēnróu kě'ài.",
        "compound_definition": "She wore a pink dress today, looking very gentle and cute.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10081,
        "character": "粉丝",
        "character_pinyin": "fěnsī",
        "eng": "fans, vermicelli",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "这位歌手的粉丝遍布世界各地，每次演唱会都会爆满。",
        "compound_pinyin": "Zhè wèi gēshǒu de fěnsī biànbù shìjiè gèdì, měi cì yǎnchànghuì dōu huì bàomǎn.",
        "compound_definition": "This singer's fans are all over the world, and every concert is packed.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10082,
        "character": "糟糕",
        "character_pinyin": "Zāogāo",
        "eng": "Oops",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "今天我忘记带钥匙，结果在家门口等了两个小时，最后还是请开锁师傅帮忙开的，真是太糟糕了！",
        "compound_pinyin": "Jīntiān wǒ wàngjì dài yàoshi, jiéguǒ zài jiā ménkǒu děngle liǎng gè xiǎoshí, zuìhòu háishì qǐng kāisuǒ shīfu bāngmáng kāi de, zhēn shì tài zāogāo le!",
        "compound_definition": "I forgot to bring my keys today, and as a result, I waited outside my door for two hours. In the end, I had to ask a locksmith for help to open it. It was really terrible!",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10083,
        "character": "绑",
        "character_pinyin": "bǎng",
        "eng": "tie",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "害羞的女孩只好穿着内衣和长袜，无奈地躺在床上，被绑起来并接受屁股按摩后，身湿漉漉。",
        "compound_pinyin": "Hàixiū de nǚhái zhǐhǎo chuānzhuó nèiyī hé zhǎng wà, wúnài de tǎng zài chuángshàng, bèi bǎng qǐlái bìng jiēshòu pìgu ànmó hòu, shēn shīlùlù.",
        "compound_definition": "The shy girl had no choice but to lie on the bed in her underwear and stockings, and she was wet after being tied up and receiving an ass massage.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10084,
        "character": "羞",
        "character_pinyin": "Xiū",
        "eng": "Shame",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "尽管她又瘦又害羞，但听到有人说“肏你妈妈”还是煽动了她的兴奋，她把蛋糕扔到了那个混蛋的屁股上。",
        "compound_pinyin": "Jǐnguǎn tā yòu shòu yòu hàixiū, dàn tīng dào yǒurén shuō “cào nǐ māmā” háishì shāndòngle tā de xīngfèn, tā bǎ dàngāo rēng dàole nàgè húndàn de pìgu shàng.",
        "compound_definition": "Even though she was skinny and shy, hearing someone say “fuck your mom” stirred her up and she threw the cake up the ass of that jerk.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10085,
        "character": "羞耻",
        "character_pinyin": "xiūchǐ",
        "eng": "shame, disgrace",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他在众人面前被揭穿了谎言，瞬间感到羞耻无比，脸色涨得通红，恨不得立刻找个地洞钻进去。",
        "compound_pinyin": "Tā zài zhòngrén miànqián bèi jiēchuān le huǎngyán, shùnjiān gǎndào xiūchǐ wúbǐ, liǎnsè zhǎng de tōnghóng, hèn bùdé lìkè zhǎo gè dìdòng zuān jìnqù.",
        "compound_definition": "When his lie was exposed in front of everyone, he felt an overwhelming sense of shame. His face turned bright red, and he wished he could find a hole in the ground to crawl into.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10086,
        "character": "翘",
        "character_pinyin": "qiào/qiáo",
        "eng": "lift, stick up, tilt",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "翘楚女孩趁机老师的认可，欺负孤立的蠢笨而不受惩罚。",
        "compound_pinyin": "Qiáochǔ nǚhái chènjī lǎoshī de rènkě, qīfù gūlì de chǔnbèn ér bù shòu chéngfá.",
        "compound_definition": "The smart girls take advantage of the teacher's approval to bully the isolated dumb ones with impunity.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10087,
        "character": "耻",
        "character_pinyin": "chǐ",
        "eng": "shame",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "他认为欺骗别人是一种可耻的行为，绝不会那么做。",
        "compound_pinyin": "Tā rènwéi qīpiàn biérén shì yī zhǒng kěchǐ de xíngwéi, jué bù huì nàme zuò.",
        "compound_definition": "He believes that deceiving others is a shameful act and would never do such a thing.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10088,
        "character": "肉棒",
        "character_pinyin": "Ròubàng",
        "eng": "Meat stick",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "爽！我要把我的肉棒插进你的屁股里，阿川，你给我张开屁股。",
        "compound_pinyin": "Shuǎng! Wǒ yào bǎ wǒ de ròubàng chā jìn nǐ de pìgu lǐ, āchuān, nǐ gěi wǒ zhāng kāi pìgu.",
        "compound_definition": "Cool! I want to put my cock in your ass, Achuan, open your ass for me.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10089,
        "character": "肏",
        "character_pinyin": "Cào",
        "eng": "Fuck",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "肏！我感到很抱歉，但我必须随心所欲。",
        "compound_pinyin": "Cào! Wǒ gǎndào hěn bàoqiàn, dàn wǒ bìxū suíxīnsuǒyù.",
        "compound_definition": "Fuck!,I'm so sorry, but I have to do what I want.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10090,
        "character": "股",
        "character_pinyin": "gǔ",
        "eng": "Share",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这家川菜馆的股东们找到了一位称职的演员来宣扬他们的猪血菜。",
        "compound_pinyin": "Zhè jiā chuāncài guǎn de gǔdōngmen zhǎodàole yī wèi chènzhí de yǎnyuán lái xuānyáng tāmen de zhū xiě cài.",
        "compound_definition": "The shareholders of this Sichuan restaurant found a competent actor to promote their pig's blood dish.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10091,
        "character": "肮",
        "character_pinyin": "āng",
        "eng": "dirty",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我必须倾心侍奉她，就像一个厕所，即使这意味着我需要吮吸她肮脏的菊花并吞下她的尿液。",
        "compound_pinyin": "Wǒ bìxū qīngxīn shìfèng tā, jiù xiàng yīgè cèsuǒ, jíshǐ zhè yìwèizhe wǒ xūyào shǔnxī tā āng zāng de júhuā bìngtūn xià tā de niào yè.",
        "compound_definition": "I had to serve her wholeheartedly, like a toilet, even if it meant I had to suck her dirty asshole and swallow her piss.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10092,
        "character": "舌",
        "character_pinyin": "Shé",
        "eng": "Tongue",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "肏！吃这个焗饭弄伤了舌头。求求你用一个吻治愈它吧。",
        "compound_pinyin": "Cào! Chī zhège jú fàn nòng shāngle shétou. Qiú qiú nǐ yòng yīgè wěn zhìyù tā ba.",
        "compound_definition": "Fuck!,I hurt my tongue from eating this risotto.,Please heal it with a kiss.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10093,
        "character": "舔",
        "character_pinyin": "Tiǎn",
        "eng": "Lick",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "已婚妇女勉强地让邻居用舌头舔她的乳头，以换取不露出她的秘密。",
        "compound_pinyin": "Yǐ hūn fùnǚ miǎnqiáng de ràng línjū yòng shétou tiǎn tā de rǔtóu, yǐ huànqǔ bù lùchū tā de mìmì.",
        "compound_definition": "A married woman reluctantly lets her neighbor lick her nipples with his tongue in exchange for not revealing her secrets.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10094,
        "character": "舔弄",
        "character_pinyin": "Tiǎnnòng",
        "eng": "Licking",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "舔弄",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10095,
        "character": "荡",
        "character_pinyin": "Dàng",
        "eng": "To squander",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我很不勉强的陪伴这个学校里的荡妇去了游泳池，她向我泼水，让我疯狂。",
        "compound_pinyin": "Wǒ hěn bù miǎnqiáng de péibàn zhège xuéxiào lǐ de dàng fù qùle yóuyǒngchí, tā xiàng wǒ pōshuǐ, ràng wǒ fēngkuáng.",
        "compound_definition": "I reluctantly accompanied this school slut to the swimming pool where she splashed water on me and drove me wild.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10096,
        "character": "荡妇",
        "character_pinyin": "Dàngfù",
        "eng": "Slut",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "虽然阿川在学校是出了名的荡妇和公交车女郎，但是尽管她有那么多炮友，我还是想和她在一起。",
        "compound_pinyin": "Suīrán āchuān zài xuéxiào shì chūle míng de dàng fù hé gōngjiāo chē nǚláng, dànshì jǐnguǎn tā yǒu nàme duō pào yǒu, wǒ háishì xiǎng hé tā zài yīqǐ.",
        "compound_definition": "Although Achuan is a well-known slut and bus girl in school, I still want to be with her despite having so many sex partners.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10097,
        "character": "菊",
        "character_pinyin": "Jú",
        "eng": "Chrysanthemum ",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "嗯……打扰了，我想点菊花茶和一些粉桃蛋糕。",
        "compound_pinyin": "Ǹg……dǎrǎole, wǒ xiǎng diǎn júhuā chá hé yīxiē fěn táo dàngāo.",
        "compound_definition": "Um...excuse me, I'd like to order chrysanthemum tea and some pink peach cake.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10098,
        "character": "菊穴",
        "character_pinyin": "júxué",
        "eng": "anus",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "菊穴",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10099,
        "character": "虐",
        "character_pinyin": "Nüè",
        "eng": "Abuse ",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "这个有偏见的骚货讨厌我，所以当她有机会时，她就趁机虐待我，抚摸我的肉棒，同时盯着我的眼睛，直到我的精液从她的手中溢出。",
        "compound_pinyin": "Zhège yǒu piānjiàn de sāo huò tǎoyàn wǒ, suǒyǐ dāng tā yǒu jīhuì shí, tā jiù chènjī nüèdài wǒ, fǔmō wǒ de ròubàng, tóngshí dīngzhe wǒ de yǎnjīng, zhídào wǒ de jīngyè cóng tā de shǒuzhōng yìchū.",
        "compound_definition": "This prejudiced slut hates me, so when she gets the chance, she takes it to abuse me, stroking my cock while staring into my eyes until my cum leaks out of her hands.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10100,
        "character": "蠢",
        "character_pinyin": "Chǔn ",
        "eng": "Stupid",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "被羞辱之后，这个蠢笨骚被激起了性欲，于是偷偷溜走，勃然抚摸自己的阴蒂，因为她是一个受虐狂。",
        "compound_pinyin": "Bèi xiūrù zhīhòu, zhège chǔnbèn sāo bèi jī qǐle xìngyù, yúshì tōutōu liū zǒu, bórán fǔmō zìjǐ de yīndì, yīnwèi tā shì yīgè shòu nüè kuáng.",
        "compound_definition": "After being humiliated, the dumb slut is so aroused that she sneaks off and fondles her clit with arousal, because she’s a masochist.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10101,
        "character": "诱",
        "character_pinyin": "Yòu",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我女友的朋友声称她湿漉漉了，引诱我发生性关系，这种骗导致了我被暂时锁在柜子里的处罚。",
        "compound_pinyin": "Wǒ nǚyǒu de péngyǒu shēngchēng tā shīlùlùle, yǐnyòu wǒ fāshēng xìng guānxì, zhè zhǒng piàn dǎozhìle wǒ bèi zhànshí suǒ zài guìzǐ lǐ de chǔfá.",
        "compound_definition": "My girlfriend's friend lured me into sex by claiming she was wet, a deception that resulted in my punishment of being temporarily locked in a closet.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10102,
        "character": "诱惑",
        "character_pinyin": "Yòuhuò",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这家甜品店的蛋糕实在是太诱惑人了，我忍不住又买了一块。",
        "compound_pinyin": "Zhè jiā tiánpǐn diàn de dàngāo shízài shì tài yòuhuò rén le, wǒ rěnbuzhù yòu mǎile yí kuài.",
        "compound_definition": "The cakes in this dessert shop are so tempting that I couldn't resist buying another one.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10103,
        "character": "贞",
        "character_pinyin": "zhēn",
        "eng": "Chastity ",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "她打开我的贞操锁后，挑逗我的龟头并阻止我达到高潮。",
        "compound_pinyin": "Tā dǎkāi wǒ de zhēncāo suǒ hòu, tiǎodòu wǒ de guītóu bìng zǔzhǐ wǒ dádào gāocháo.",
        "compound_definition": "After she opened my chastity lock, she teased my glans and prevented me from reaching orgasm.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10104,
        "character": "贞操锁",
        "character_pinyin": "Zhēncāo suǒ",
        "eng": "Chastity lock",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "进去之后，我被带上了贞操锁，然后我的妻子被脱光了衣服，在这些比我强壮的男人面前翘起了她的屁股",
        "compound_pinyin": "Jìnqù zhīhòu, wǒ bèi dài shàngle zhēncāo suǒ, ránhòu wǒ de qīzǐ bèi tuōguāngle yīfú, zài zhèxiē bǐ wǒ qiángzhuàng de nánrén miànqián qiào qǐle tā de pìgu",
        "compound_definition": "Once inside, I was put in a chastity belt, and then my wife was stripped naked and raised her ass in front of these men who were stronger than me.",
        "valid_sentence": "",
        "counter (118)\r": 3
    },
    {
        "id": 10105,
        "character": "趁",
        "character_pinyin": "chèn",
        "eng": "take advantage of (an opportunity)",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound_cantonese": "",
        "compound": "我们趁天气还没变冷，赶紧去郊外露营吧！",
        "compound_pinyin": "Wǒmen chèn tiānqì hái méi biàn lěng, gǎnjǐn qù jiāowài lùyíng ba!",
        "compound_definition": "Let's take advantage of the weather before it gets cold and go camping in the suburbs!",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10106,
        "character": "辱",
        "character_pinyin": "rǔ",
        "eng": "disgrace",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "虽然给家人带来耻辱，但她毫无羞耻地将自己的粉红色菊花发布到网上后，却收获了大批粉丝。",
        "compound_pinyin": "Suīrán gěi jiārén dài lái chǐrǔ, dàn tā háo wú xiūchǐ de jiāng zìjǐ de fěnhóng sè júhuā fābù dào wǎngshàng hòu, què shōuhuòle dàpī fěnsī.",
        "compound_definition": "Although it brought shame to her family, she gained a huge following after shamelessly posting a photo of her pink chrysanthemums online.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10107,
        "character": "逗",
        "character_pinyin": "dòu",
        "eng": "tease",
        "hsk_level": 6,
        "part_of_speech": "verb",
        "compound": "她撒腿后，阴蒂不断受到挑逗，在达到高潮后无法维持姿势。",
        "compound_pinyin": "Tā sātuǐ hòu, yīndì bùduàn shòudào tiǎodòu, zài dádào gāocháo hòu wúfǎ wéichí zīshì.",
        "compound_definition": "After she spread her legs, her clitoris was constantly teased and she was unable to maintain the position after reaching orgasm.",
        "valid_sentence": "TRUE",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10108,
        "character": "道歉",
        "character_pinyin": "dàoqiàn",
        "eng": "To apologize",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "他意识到自己的错误后，立刻向朋友真诚地道歉，希望得到原谅。",
        "compound_pinyin": "Tā yìshídào zìjǐ de cuòwù hòu, lìkè xiàng péngyǒu zhēnchéng de dàoqiàn, xīwàng dédào yuánliàng.",
        "compound_definition": "After realizing his mistake, he sincerely apologized to his friend, hoping to be forgiven.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10109,
        "character": "野",
        "character_pinyin": "yě",
        "eng": "Wild",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "哎呀！你挡住了我的视野，我看不到闪电。",
        "compound_pinyin": "Āiyā! Nǐ dǎngzhùle wǒ de shìyě, wǒ kàn bù dào shǎndiàn.",
        "compound_definition": "Oops!,You're blocking my view and I can't see the lightning.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10110,
        "character": "隐",
        "character_pinyin": "Yǐn",
        "eng": "Hidden",
        "hsk_level": 6,
        "part_of_speech": "adjective",
        "compound_cantonese": "",
        "compound": "我让那个偏矮壮的骚货倾斜在弄堂里的墙上，撒腿双腿，痛得她隐隐哭泣起来。",
        "compound_pinyin": "Wǒ ràng nàgè piān ǎi zhuàng de sāo huò qīngxié zài lòngtáng lǐ de qiáng shàng, sātuǐ shuāng tuǐ, tòng dé tā yǐnyǐn kūqì qǐlái.",
        "compound_definition": "I let that short and strong bitch lean against the wall in the alley with her legs spread out, and she started crying in pain.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10111,
        "character": "露",
        "character_pinyin": "Lù",
        "eng": "Dew",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "阿川向我透露了她无处可归宿的秘密，所以我就租了一间情趣酒店，操她直到晨朝。",
        "compound_pinyin": "Āchuān xiàng wǒ tòulùle tā wú chù kě guīsù de mìmì, suǒyǐ wǒ jiù zūle yī jiàn qíngqù jiǔdiàn, cāo tā zhídào chéncháo.",
        "compound_definition": "Achuan revealed to me her secret of having nowhere to stay, so I rented a love hotel and fucked her until dawn.",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10112,
        "character": "露出",
        "character_pinyin": "Lùchū",
        "eng": "To expose",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "她听到这个好消息后，脸上立刻露出了灿烂的笑容。",
        "compound_pinyin": "Tā tīngdào zhège hǎo xiāoxi hòu, liǎn shàng lìkè lòuchūle cànlàn de xiàoróng.",
        "compound_definition": "After hearing the good news, she immediately revealed a bright smile on her face.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10114,
        "character": "顺从",
        "character_pinyin": "Shùncóng",
        "eng": "Obedience",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "为了训练他的性欲，民族情妇要么给他的肉棒摩上润滑油以换取他的顺从，要么向他罚钱。",
        "compound_pinyin": "Wèile xùnliàn tā dì xìngyù, mínzú qíngfù yàome gěi tā de ròubàng mó shàng rùnhuá yóu yǐ huànqǔ tā de shùncóng, yàome xiàng tā fá qián.",
        "compound_definition": "In order to train his sexual desire, the ethnic mistress either rubs his cock with lubrication in exchange for his obedience or fines him.",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10115,
        "character": "骚",
        "character_pinyin": "sāo",
        "eng": "bitch",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "你这条骚母狗怎么把淫水流的到处都是？",
        "compound_pinyin": "Nǐ zhè tiáo sāo mǔgǒu zěnme bǎ yínshuǐ liú de dàochù dōu shì?",
        "compound_definition": "Why are you, a slutty bitch, leaking your juices everywhere?",
        "valid_sentence": "",
        "counter (118)\r": 1
    },
    {
        "id": 10116,
        "character": "龟",
        "character_pinyin": "guī",
        "eng": "turtle",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "嘛……龟甲虽然经常很肮脏，但是却是做汤的好材料。",
        "compound_pinyin": "Ma……guījiǎ suīrán jīngcháng hěn āng zāng, dànshì què shì zuò tāng de hǎo cáiliào.",
        "compound_definition": "Well… although tortoise shells are often dirty, they are a great ingredient for making soup.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 1
    },
    {
        "id": 10117,
        "character": "龟头",
        "character_pinyin": "guītóu",
        "eng": "glans",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "龟头",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 2
    },
    {
        "id": 10118,
        "character": "蒂",
        "character_pinyin": "dì",
        "eng": "stem (of fruit)",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "玩弄阴蒂…虽然我听到过很多次原来是这样的话说…由香的阴蒂有这么大吗？",
        "compound_pinyin": "Wànnòng yīndì…suīrán wǒ tīng dàoguò hěnduō cì yuánlái shì zhèyàng dehuà shuō…yóuxiāng de yīndì yǒu zhème dà ma?",
        "compound_definition": "Play with the clitoris... Although I have heard this many times, it turns out to be something like this... Is Yuka's clitoris this big?",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": 10119,
        "character": "乌",
        "character_pinyin": "wū",
        "eng": "crow",
        "hsk_level": 6,
        "part_of_speech": "noun",
        "compound_cantonese": "",
        "compound": "她将这个乌龟男人锁在贞操带中，并挑逗他说她不会抗拒被另一个男人内射，以此来煽情他的性欲。",
        "compound_pinyin": "Tā jiāng zhège wūguī nánrén suǒ zài zhēncāo dài zhōng, bìng tiǎodòu tā shuō tā bù huì kàngjù bèi lìng yīgè nánrén nèishè, yǐ cǐ lái shānqíng tā dì xìngyù.",
        "compound_definition": "She locks the cuckold man in a chastity belt and arouses his sexual desire by teasing him that she won’t resist being creampied by another man.",
        "valid_sentence": "TRUE",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    },
    {
        "id": "",
        "character": "",
        "character_pinyin": "",
        "eng": "",
        "hsk_level": "",
        "part_of_speech": "",
        "compound_cantonese": "",
        "compound": "",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (118)\r": 0
    }
]