var hskLevelZ = [
    {
        "id": "",
        "character": "乳",
        "character_pinyin": "Rǔ",
        "eng": "Milk",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "众所周知，来自欧洲的乳制品和粮物产品的浓度比中国大陆的更高。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "乳头",
        "character_pinyin": "Rǔtóu",
        "eng": "Nipple",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "乳头",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "传染",
        "character_pinyin": "chuánrǎn",
        "eng": "infect",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "传染",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "勉",
        "character_pinyin": "miǎn",
        "eng": "encourage",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "勉励幼儿园学生顺应并尊敬老师，如果他们表现出烂的态度，就会受到打击。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "勉强",
        "character_pinyin": "miǎnqiáng",
        "eng": "to do reluctantly",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "勉强",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "厕",
        "character_pinyin": "cè",
        "eng": "toilet",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "厕所里有一个荡妇正在露出她的乳房和乳头",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "君",
        "character_pinyin": "Jūn ",
        "eng": "Gentleman",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "打扰一下，君子。请问厕所在哪儿？我和我兄弟想找个地方聊聊天。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "吻",
        "character_pinyin": "Wěn",
        "eng": "Kiss",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "当这个淫荡的婊子开始亲吻这个害羞而孤独的男孩时，他的肉棒就变硬了，并在裤子里射了精。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "哎呀",
        "character_pinyin": "Āiyā",
        "eng": "Aiya ",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "哎",
        "character_pinyin": "Āi",
        "eng": "Hey!",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "哎呀！我放的屁太臭了，我老婆都开始骂我了。我怕等会儿要受罚。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "啦",
        "character_pinyin": "la",
        "eng": "la",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "嗯…嘛嘛… 你别这么冷漠，安慰我啦。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "嗯",
        "character_pinyin": "Ǹg",
        "eng": "um",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "嗯…请温柔一点。嘛嘛，如果你愿意，你可以更用力一点，但我的屁股很敏感啦。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "嘛",
        "character_pinyin": "ma",
        "eng": "well",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "糟糕…嘛…我没能及时将我的肉棒从你的小穴中拔出来啦。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "处男",
        "character_pinyin": "Chǔnán",
        "eng": "Virgin",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "处男",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "妙",
        "character_pinyin": "Miào",
        "eng": "Wonderful",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这荡妇巧妙地引诱她的炮友阻碍老师收集文献。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "婊",
        "character_pinyin": "biǎo",
        "eng": "prostitute",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个年轻的婊子到处传染班上那些不知情的处女，满足她们的性欲。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "婊子",
        "character_pinyin": "biǎozǐ",
        "eng": "bitch",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "婊子",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "孤",
        "character_pinyin": "gū",
        "eng": "solitary",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "孤独的女人被炮友甩了，大喊“肏，我好寂寞啊！”",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "害羞",
        "character_pinyin": "Hàixiū",
        "eng": "Shy",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "害羞",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "寂",
        "character_pinyin": "Jì",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "这位四川君子虽然巧妙，但是却常常因为寂寞而哭泣。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "寂寞",
        "character_pinyin": "Jìmò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "寂寞",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "寞",
        "character_pinyin": "mò",
        "eng": "Lonely",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我希望有人能治愈我这种无法再忍受的寂寞。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "尿",
        "character_pinyin": "Niào",
        "eng": "Urine",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "哎呀！我因为喝醉了而错过了上厕所的机会，现在地板上全是尿液。我应该向其他客人道歉。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "屁",
        "character_pinyin": "Pì",
        "eng": "Fart",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "这个低俗的男人，觉得亲吻女友柔软的屁股是一件很爽的事情。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "屁股",
        "character_pinyin": "Pìgu",
        "eng": "Butt",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "屁股",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "川",
        "character_pinyin": "Chuān",
        "eng": "Sichuan",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "四川以其巨大的田野、温泉和激烈的棒球竞赛而闻名。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "性欲",
        "character_pinyin": "Xìngyù",
        "eng": "Sexual desire",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "性欲",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "愈",
        "character_pinyin": "Yù",
        "eng": "Heal",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "这位欧洲护士经常用她的舌头来治愈病人的性欲。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "抱歉",
        "character_pinyin": "Bàoqiàn",
        "eng": "Feel sorry",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "抱歉",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "接吻",
        "character_pinyin": "Jiēwěn",
        "eng": "Kiss ",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "接吻",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "柔",
        "character_pinyin": "róu",
        "eng": "soft",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "哎呀！亚洲女人的舌头好柔软，光是亲吻就感觉淫荡至极啦。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "欧",
        "character_pinyin": "ōu",
        "eng": "Europe",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我怀念那位专门做按摩的欧洲女人，她的按摩手法非常温柔。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "欧派",
        "character_pinyin": "ōupài",
        "eng": "oppai",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "欧派",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "欲",
        "character_pinyin": "Yù",
        "eng": "Want",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我对焗米饭的欲望让我发疯，特别是当我闻到它的味道时，所以请给我一个鼻夹！",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "歉",
        "character_pinyin": "Qiàn",
        "eng": "Apologize",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我必须道歉。虽然我试图在厕所小便，但我的尿液洒在地板上，现在一切都很润滑。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "泣",
        "character_pinyin": "qì",
        "eng": "weep",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "我的炮友温柔地按摩着我的肉棒，而她因被男友骗人而被甩了而害羞地哭泣。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "淫",
        "character_pinyin": "Yín",
        "eng": "Lewd",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "她是那种如果混蛋把她绑在床上、锁在房间里并把她露出网上，她就会漏出淫水的女人。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "淫水",
        "character_pinyin": "Yínshuǐ",
        "eng": "Sexual secretion",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "淫水",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "混",
        "character_pinyin": "Hùn",
        "eng": "Mix",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "那个君子是个混蛋，经常用金钱诱惑穷困的女人，强迫她们顺从。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "混蛋",
        "character_pinyin": "Húndàn",
        "eng": "Asshole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "混蛋",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "温柔",
        "character_pinyin": "wēnróu",
        "eng": "gentle",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "温柔",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "湿漉漉",
        "character_pinyin": "Shīlùlù",
        "eng": "Wet",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "湿漉漉",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "漉",
        "character_pinyin": "Lù",
        "eng": "Filter liquids",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "嗯，抱歉，你的手态湿漉漉了，所以我不想握住它们。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "炮",
        "character_pinyin": "Pào",
        "eng": "Firecracker / cannon",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "我把我的炮友绑起来，丢在一片空地田野，这让她疯狂起来，拿着长矛追着我，但我用盾牌挡住了她。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "焗",
        "character_pinyin": "jú",
        "eng": "baked",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "夕阳下，她在中央公园向我挥手。我们约好一起吃焗饭。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "煽",
        "character_pinyin": "shān",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "厨师煽动人群扰乱钢琴演，向任何能抢走玉饰的人提供焗米饭。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "煽动",
        "character_pinyin": "shāndòng",
        "eng": "incite",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "煽动",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "爽",
        "character_pinyin": "Shuǎng",
        "eng": "Cool",
        "hsk_level": 6,
        "part_of_speech": "Adjective",
        "compound_cantonese": "",
        "compound": "我不骗你，舔着一个又矮又瘦的漂亮女孩小穴里的尿液，感觉很爽。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "甩",
        "character_pinyin": "shuǎi",
        "eng": "throw",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "甩",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "甩被了",
        "character_pinyin": "bèi shuǎile",
        "eng": "dumped",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "甩被了",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "田",
        "character_pinyin": "tián",
        "eng": "field",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "田",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "真扫兴",
        "character_pinyin": "Zhēn săoxìng",
        "eng": "What a bummer",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "真扫兴",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "破处",
        "character_pinyin": "Pòchù",
        "eng": "Losing virginity",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "破处",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "穴",
        "character_pinyin": "xué",
        "eng": "hole",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "穴",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "糟糕",
        "character_pinyin": "Zāogāo",
        "eng": "Oops",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "糟糕",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "绑",
        "character_pinyin": "bǎng",
        "eng": "tie",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "害羞的女孩只好穿着内衣和长袜，无奈地躺在床上，被绑起来并接受屁股按摩后，身湿漉漉。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "羞",
        "character_pinyin": "Xiū",
        "eng": "Shame",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "羞",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "肉棒",
        "character_pinyin": "Ròubàng",
        "eng": "Meat stick",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "肉棒",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "肏",
        "character_pinyin": "Cào",
        "eng": "Fuck",
        "hsk_level": 6,
        "part_of_speech": "Phrase",
        "compound_cantonese": "",
        "compound": "肏！我感到很抱歉，但我必须随心所欲。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "股",
        "character_pinyin": "gǔ",
        "eng": "Share",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "股",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "舌",
        "character_pinyin": "Shé",
        "eng": "Tongue",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "舌",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "舔",
        "character_pinyin": "Tiǎn",
        "eng": "Lick",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "已婚妇女勉强地让邻居用舌头舔她的乳头，以换取不露出她的秘密。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "荡",
        "character_pinyin": "Dàng",
        "eng": "To squander",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "荡",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "荡妇",
        "character_pinyin": "Dàngfù",
        "eng": "Slut",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "荡妇",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "诱",
        "character_pinyin": "Yòu",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "诱",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "诱惑",
        "character_pinyin": "Yòuhuò",
        "eng": "Lure",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "诱惑",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "道歉",
        "character_pinyin": "dàoqiàn",
        "eng": "To apologize",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "道歉",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "野",
        "character_pinyin": "yě",
        "eng": "Wild",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "野",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "露",
        "character_pinyin": "Lù",
        "eng": "Dew",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "露",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "露出",
        "character_pinyin": "Lùchū",
        "eng": "To expose",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "露出",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "顺",
        "character_pinyin": "shùn",
        "eng": "To obey",
        "hsk_level": 6,
        "part_of_speech": "Verb",
        "compound_cantonese": "",
        "compound": "顺",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "顺从",
        "character_pinyin": "Shùncóng",
        "eng": "Obedience",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "顺从",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": "\r"
    },
    {
        "id": "",
        "character": "洲",
        "character_pinyin": "zhōu",
        "eng": "Europe / continent",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "那个提倡男人应该用舌头舔妻子阴道的亚洲女人让我感到非常害羞。",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": ""
    },
    {
        "id": "",
        "character": "液",
        "character_pinyin": "yè",
        "eng": "Liquid",
        "hsk_level": 6,
        "part_of_speech": "Noun",
        "compound_cantonese": "",
        "compound": "液",
        "compound_pinyin": "",
        "compound_definition": "",
        "valid_sentence": "",
        "counter (78)\r": ""
    }
]