var data = [
    {
      "id": 1,
      "character": "多",
      "character_pinyin": "duō",
      "eng": "many",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "多",
      "compound_pinyin": "duō",
      "compound_cantonese": "do1",
      "compound_definition": "many; much; often; a lot of; numerous; more; in excess; how (to what extent); multi-; Taiwan pr. [duo2] when it means \"how",
      "": ""
    },
    {
      "id": 2,
      "character": "大",
      "character_pinyin": "dà",
      "eng": "big",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "大",
      "compound_pinyin": "dà",
      "compound_cantonese": "daai6",
      "compound_definition": "big; huge; large; major; great; wide; deep; older (than); oldest; eldest; greatly; very much; (dialect) father; father's elder or younger brother",
      "": ""
    },
    {
      "id": 3,
      "character": "高兴",
      "character_pinyin": "gāoxìng",
      "eng": "happy",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "高兴",
      "compound_pinyin": "gāoxìng",
      "compound_cantonese": "gou1hing3",
      "compound_definition": "happy; glad; willing (to do something); in a cheerful mood",
      "": ""
    },
    {
      "id": 4,
      "character": "好",
      "character_pinyin": "hǎo",
      "eng": "good",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "好",
      "compound_pinyin": "hǎo",
      "compound_cantonese": "hou2",
      "compound_definition": "good; well; proper; good to; easy to; very; so; (suffix indicating completion or readiness); (of two people) close; on intimate terms; (after a personal pronoun) hello",
      "": ""
    },
    {
      "id": 5,
      "character": "冷",
      "character_pinyin": "lěng",
      "eng": "cold",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "冷",
      "compound_pinyin": "lěng",
      "compound_cantonese": "laang5",
      "compound_definition": "cold; (Chinese surname)",
      "": ""
    },
    {
      "id": 6,
      "character": "漂亮",
      "character_pinyin": "piàoliang",
      "eng": "pretty",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "漂亮",
      "compound_pinyin": "piàoliang",
      "compound_cantonese": "piu3loeng6",
      "compound_definition": "pretty; beautiful",
      "": ""
    },
    {
      "id": 7,
      "character": "热",
      "character_pinyin": "rè",
      "eng": "to warm up",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "热",
      "compound_pinyin": "rè",
      "compound_cantonese": "jit6",
      "compound_definition": "to warm up; to heat up; hot (of weather); heat; fervent",
      "": ""
    },
    {
      "id": 8,
      "character": "少",
      "character_pinyin": "shǎo",
      "eng": "few",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "少",
      "compound_pinyin": "shǎo",
      "compound_cantonese": "siu2",
      "compound_definition": "few; less; to lack; to be missing; to stop (doing something); seldom",
      "": ""
    },
    {
      "id": 9,
      "character": "小",
      "character_pinyin": "xiǎo",
      "eng": "small",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "小",
      "compound_pinyin": "xiǎo",
      "compound_cantonese": "siu2",
      "compound_definition": "small; tiny; few; young",
      "": ""
    },
    {
      "id": 10,
      "character": "不",
      "character_pinyin": "bù",
      "eng": "(negative prefix)",
      "hsk_level": 1,
      "part_of_speech": "(副) adverb",
      "compound": "不",
      "compound_pinyin": "bù",
      "compound_cantonese": "bat1",
      "compound_definition": "(negative prefix); not; no",
      "": ""
    },
    {
      "id": 11,
      "character": "没有",
      "character_pinyin": "méiyǒu",
      "eng": "haven't",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "没有",
      "compound_pinyin": "méiyǒu",
      "compound_cantonese": "mut6jau5",
      "compound_definition": "haven't; hasn't; doesn't exist; to not have; to not be",
      "": ""
    },
    {
      "id": 12,
      "character": "很",
      "character_pinyin": "hěn",
      "eng": "(adverb of degree)",
      "hsk_level": 1,
      "part_of_speech": "(副) adverb",
      "compound": "很",
      "compound_pinyin": "hěn",
      "compound_cantonese": "han2",
      "compound_definition": "(adverb of degree); quite; very; awfully",
      "": ""
    },
    {
      "id": 13,
      "character": "太",
      "character_pinyin": "tài",
      "eng": "highest",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "太",
      "compound_pinyin": "tài",
      "compound_cantonese": "taai3",
      "compound_definition": "highest; greatest; too (much); very; extremely",
      "": ""
    },
    {
      "id": 14,
      "character": "都",
      "character_pinyin": "dōu",
      "eng": "all",
      "hsk_level": 1,
      "part_of_speech": "(副) adverb",
      "compound": "都",
      "compound_pinyin": "dōu",
      "compound_cantonese": "dou1",
      "compound_definition": "all; both; entirely; (used for emphasis) even; already; (not) at all",
      "": ""
    },
    {
      "id": 15,
      "character": "会",
      "character_pinyin": "huì",
      "eng": "can (i.e. have the skill, know how to)",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "会",
      "compound_pinyin": "huì",
      "compound_cantonese": "wui5",
      "compound_definition": "can (i.e. have the skill, know how to); likely to; sure to",
      "": ""
    },
    {
      "id": 16,
      "character": "能",
      "character_pinyin": "néng",
      "eng": "can",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "能",
      "compound_pinyin": "néng",
      "compound_cantonese": "nang4",
      "compound_definition": "can; to be able to; might possibly; ability; (physics) energy; (Chinese surname)",
      "": ""
    },
    {
      "id": 17,
      "character": "想",
      "character_pinyin": "xiǎng",
      "eng": "to think",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "想",
      "compound_pinyin": "xiǎng",
      "compound_cantonese": "soeng2",
      "compound_definition": "to think; to believe; to suppose; to wish; to want; to miss (feel wistful about the absence of somebody or something)",
      "": ""
    },
    {
      "id": 18,
      "character": "和",
      "character_pinyin": "hé",
      "eng": "and",
      "hsk_level": 1,
      "part_of_speech": "(连) conjunction",
      "compound": "和",
      "compound_pinyin": "hé",
      "compound_cantonese": "wo4",
      "compound_definition": "and; together with; with; sum; union; peace; harmony; Taiwan pr. [han4] when it means \"and\" or \"with\"; (Chinese surname); Japanese (food, clothes etc)",
      "": ""
    },
    {
      "id": 19,
      "character": "这",
      "character_pinyin": "zhè, also pr. zhèi",
      "eng": "this",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "这",
      "compound_pinyin": "zhè, also pr. zhèi",
      "compound_cantonese": "ze5",
      "compound_definition": "this; these; (commonly pr. [zhei4] before a classifier, esp. in Beijing)",
      "": ""
    },
    {
      "id": 20,
      "character": "这里",
      "character_pinyin": "zhèlǐ",
      "eng": "here",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "这里",
      "compound_pinyin": "zhèlǐ",
      "compound_cantonese": "ze2leoi5",
      "compound_definition": "here; variant of 這裏",
      "": ""
    },
    {
      "id": 21,
      "character": "这个",
      "character_pinyin": "zhège",
      "eng": "this",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "这个",
      "compound_pinyin": "zhège",
      "compound_cantonese": "ze2go3",
      "compound_definition": "this; this one",
      "": ""
    },
    {
      "id": 22,
      "character": "那",
      "character_pinyin": "nà",
      "eng": "that",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "那",
      "compound_pinyin": "nà",
      "compound_cantonese": "naa5",
      "compound_definition": "that; those; then (in that case); commonly pr. [nei4] before a classifier, esp. in Beijing",
      "": ""
    },
    {
      "id": 23,
      "character": "那里",
      "character_pinyin": "nàli, also pr. nàlǐ",
      "eng": "there",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "那里",
      "compound_pinyin": "nàli, also pr. nàlǐ",
      "compound_cantonese": "naa5leoi5",
      "compound_definition": "there; that place; there; that place; also written 那里",
      "": ""
    },
    {
      "id": 24,
      "character": "那个",
      "character_pinyin": "nàge, also pr. nèige",
      "eng": "that one",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "那个",
      "compound_pinyin": "nàge, also pr. nèige",
      "compound_cantonese": "naa5go3",
      "compound_definition": "that one; that thing; that (as opposed to this); (used before a verb or adjective for emphasis); (used to humorously or indirectly refer to something embarrassing, funny etc, or when one can't think of the right word); (used in speech as a filler, similar to \"umm\", \"you know\" etc); (euph.) menstruation; sex",
      "": ""
    },
    {
      "id": 25,
      "character": "喂",
      "character_pinyin": "wèi",
      "eng": "hey",
      "hsk_level": 1,
      "part_of_speech": "(叹) interjection",
      "compound": "喂",
      "compound_pinyin": "wèi",
      "compound_cantonese": "wai3",
      "compound_definition": "hey; to feed (an animal, baby, invalid etc)",
      "": ""
    },
    {
      "id": 26,
      "character": "多少",
      "character_pinyin": "duōshao",
      "eng": "how much?",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "多少",
      "compound_pinyin": "duōshao",
      "compound_cantonese": "do1siu2",
      "compound_definition": "how much?; how many?; (phone number, student ID etc) what number?",
      "": ""
    },
    {
      "id": 27,
      "character": "几",
      "character_pinyin": "jǐ",
      "eng": "how much",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "几",
      "compound_pinyin": "jǐ",
      "compound_cantonese": "gei2",
      "compound_definition": "how much; how many; several; a few",
      "": ""
    },
    {
      "id": 28,
      "character": "哪",
      "character_pinyin": "nǎ",
      "eng": "how",
      "hsk_level": 1,
      "part_of_speech": "(疑问代) question pronoun",
      "compound": "哪",
      "compound_pinyin": "nǎ",
      "compound_cantonese": "naa5",
      "compound_definition": "how; which; where",
      "": ""
    },
    {
      "id": 29,
      "character": "哪里",
      "character_pinyin": "nǎlǐ, also pr. nǎli",
      "eng": "where?",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "哪里",
      "compound_pinyin": "nǎlǐ, also pr. nǎli",
      "compound_cantonese": "naa5leoi5",
      "compound_definition": "where?; somewhere; anywhere; wherever; nowhere (negative answer to question); humble expression denying compliment; also written 哪里",
      "": ""
    },
    {
      "id": 30,
      "character": "什么",
      "character_pinyin": "shénme",
      "eng": "what?",
      "hsk_level": 1,
      "part_of_speech": "(疑问代) question pronoun",
      "compound": "什么",
      "compound_pinyin": "shénme",
      "compound_cantonese": "sam6mo1",
      "compound_definition": "what?; something; anything",
      "": ""
    },
    {
      "id": 31,
      "character": "谁",
      "character_pinyin": "shéi, also pr. shuí",
      "eng": "who",
      "hsk_level": 1,
      "part_of_speech": "(疑问代) question pronoun",
      "compound": "谁",
      "compound_pinyin": "shéi, also pr. shuí",
      "compound_cantonese": "seoi4",
      "compound_definition": "who",
      "": ""
    },
    {
      "id": 32,
      "character": "怎么",
      "character_pinyin": "zěnme",
      "eng": "how?",
      "hsk_level": 1,
      "part_of_speech": "(疑问代) question pronoun",
      "compound": "怎么",
      "compound_pinyin": "zěnme",
      "compound_cantonese": "zam2mo1",
      "compound_definition": "how?; what?; why?",
      "": ""
    },
    {
      "id": 33,
      "character": "怎么样",
      "character_pinyin": "zěnme yàng",
      "eng": "how?",
      "hsk_level": 1,
      "part_of_speech": "(疑问代) question pronoun",
      "compound": "怎么样",
      "compound_pinyin": "zěnme yàng",
      "compound_cantonese": "zam2mo1 joeng6",
      "compound_definition": "how?; how about?; how was it?; how are things?",
      "": ""
    },
    {
      "id": 34,
      "character": "本子",
      "character_pinyin": "běnzi",
      "eng": "book",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "本子",
      "compound_pinyin": "běnzi",
      "compound_cantonese": "bun2zi2",
      "compound_definition": "book; notebook; Japanese-style self-published comic (esp. an erotic one), aka \"dōjinshi\"; edition",
      "": ""
    },
    {
      "id": 35,
      "character": "个",
      "character_pinyin": "gè",
      "eng": "individual",
      "hsk_level": 1,
      "part_of_speech": "(量) measure word",
      "compound": "个",
      "compound_pinyin": "gè",
      "compound_cantonese": "go3",
      "compound_definition": "individual; this; that; size; measure word for people or objects in general",
      "": ""
    },
    {
      "id": 36,
      "character": "块",
      "character_pinyin": "kuài",
      "eng": "lump (of earth)",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "块",
      "compound_pinyin": "kuài",
      "compound_cantonese": "faai3",
      "compound_definition": "lump (of earth); chunk; piece; measure word for pieces of cloth, cake, soap etc; (coll.) measure word for money and currency units",
      "": ""
    },
    {
      "id": 37,
      "character": "岁",
      "character_pinyin": "suì",
      "eng": "measure word for years (of age)",
      "hsk_level": 1,
      "part_of_speech": "(量) measure word",
      "compound": "岁",
      "compound_pinyin": "suì",
      "compound_cantonese": "seoi3",
      "compound_definition": "measure word for years (of age); year; year (of crop harvests)",
      "": ""
    },
    {
      "id": 38,
      "character": "一些",
      "character_pinyin": "yīxiē",
      "eng": "some",
      "hsk_level": 1,
      "part_of_speech": "(量) measure word",
      "compound": "一些",
      "compound_pinyin": "yīxiē",
      "compound_cantonese": "jat1se1",
      "compound_definition": "some; a few; a little; (following an adjective) slightly ...er",
      "": ""
    },
    {
      "id": 39,
      "character": "一点点",
      "character_pinyin": "yī diǎndiǎn",
      "eng": "a little bit",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "一点点",
      "compound_pinyin": "yī diǎndiǎn",
      "compound_cantonese": "jat1 dim2dim2",
      "compound_definition": "a little bit",
      "": ""
    },
    {
      "id": 40,
      "character": "爸",
      "character_pinyin": "bà",
      "eng": "father",
      "hsk_level": 1,
      "part_of_speech": "English Definition",
      "compound": "爸",
      "compound_pinyin": "bà",
      "compound_cantonese": "baa1",
      "compound_definition": "father; dad; pa; papa",
      "": ""
    },
    {
      "id": 41,
      "character": "北",
      "character_pinyin": "běi",
      "eng": "north",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "北",
      "compound_pinyin": "běi",
      "compound_cantonese": "bak1",
      "compound_definition": "north; (classical) to be defeated",
      "": ""
    },
    {
      "id": 42,
      "character": "京",
      "character_pinyin": "jīng",
      "eng": "capital city of a country",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "京",
      "compound_pinyin": "jīng",
      "compound_cantonese": "ging1",
      "compound_definition": "capital city of a country; big; algebraic term for a large number (old); artificial mound (old); abbr. for Beijing; (Chinese surname); Jing ethnic minority",
      "": ""
    },
    {
      "id": 43,
      "character": "杯子",
      "character_pinyin": "bēizi",
      "eng": "cup",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "杯子",
      "compound_pinyin": "bēizi",
      "compound_cantonese": "bui1zi2",
      "compound_definition": "cup; glass",
      "": ""
    },
    {
      "id": 44,
      "character": "菜",
      "character_pinyin": "cài",
      "eng": "dish (type of food)",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "菜",
      "compound_pinyin": "cài",
      "compound_cantonese": "coi3",
      "compound_definition": "dish (type of food); vegetable; cuisine; (coll.) (one's) type; (of one's skills etc) weak; poor",
      "": ""
    },
    {
      "id": 45,
      "character": "茶",
      "character_pinyin": "chá",
      "eng": "tea",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "茶",
      "compound_pinyin": "chá",
      "compound_cantonese": "caa4",
      "compound_definition": "tea; tea plant",
      "": ""
    },
    {
      "id": 46,
      "character": "车",
      "character_pinyin": "chē",
      "eng": "car",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "车",
      "compound_pinyin": "chē",
      "compound_cantonese": "ce1",
      "compound_definition": "car; vehicle; machine; to shape with a lathe; Kangxi radical 159; (Chinese surname)",
      "": ""
    },
    {
      "id": 47,
      "character": "出租车",
      "character_pinyin": "chūzū chē",
      "eng": "taxi",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "出租车",
      "compound_pinyin": "chūzū chē",
      "compound_cantonese": "ceot1zou1 ce1",
      "compound_definition": "taxi; (Tw) rental car",
      "": ""
    },
    {
      "id": 48,
      "character": "点",
      "character_pinyin": "diǎn",
      "eng": "point",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "点",
      "compound_pinyin": "diǎn",
      "compound_cantonese": "dim2",
      "compound_definition": "point; dot; drop; speck; o'clock; point (in space or time); to draw a dot; to check on a list; to choose; to order (food in a restaurant); to touch briefly; to hint; to light; to ignite; to pour a liquid drop by drop; (old) one fifth of a two-hour watch 更; dot stroke in Chinese characters; measure word for items",
      "": ""
    },
    {
      "id": 49,
      "character": "电",
      "character_pinyin": "diàn",
      "eng": "lightning",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "电",
      "compound_pinyin": "diàn",
      "compound_cantonese": "din6",
      "compound_definition": "lightning; electricity; electric (bound form); to get (or give) an electric shock; phone call or telegram etc; to send via telephone or telegram etc",
      "": ""
    },
    {
      "id": 50,
      "character": "电脑",
      "character_pinyin": "diànnǎo",
      "eng": "computer",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "电脑",
      "compound_pinyin": "diànnǎo",
      "compound_cantonese": "din6nou5",
      "compound_definition": "computer",
      "": ""
    },
    {
      "id": 51,
      "character": "电视",
      "character_pinyin": "diànshì",
      "eng": "television",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "电视",
      "compound_pinyin": "diànshì",
      "compound_cantonese": "din6si6",
      "compound_definition": "television; TV",
      "": ""
    },
    {
      "id": 52,
      "character": "电影",
      "character_pinyin": "diànyǐng",
      "eng": "movie",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "电影",
      "compound_pinyin": "diànyǐng",
      "compound_cantonese": "din6jing2",
      "compound_definition": "movie; film",
      "": ""
    },
    {
      "id": 53,
      "character": "东",
      "character_pinyin": "dōng",
      "eng": "east",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "东",
      "compound_pinyin": "dōng",
      "compound_cantonese": "dung1",
      "compound_definition": "east; host (i.e. sitting on east side of guest); landlord; (Chinese surname)",
      "": ""
    },
    {
      "id": 54,
      "character": "西",
      "character_pinyin": "xī",
      "eng": "west",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "西",
      "compound_pinyin": "xī",
      "compound_cantonese": "sai1",
      "compound_definition": "west; the West; abbr. for Spain 西班牙; Spanish",
      "": ""
    },
    {
      "id": 55,
      "character": "东西",
      "character_pinyin": "dōngxi",
      "eng": "thing",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "东西",
      "compound_pinyin": "dōngxi",
      "compound_cantonese": "dung1sai1",
      "compound_definition": "thing; stuff; person",
      "": ""
    },
    {
      "id": 56,
      "character": "儿子",
      "character_pinyin": "érzi",
      "eng": "son",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "儿子",
      "compound_pinyin": "érzi",
      "compound_cantonese": "ji4zi2",
      "compound_definition": "son",
      "": ""
    },
    {
      "id": 57,
      "character": "饭",
      "character_pinyin": "fàn",
      "eng": "cooked rice",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "饭",
      "compound_pinyin": "fàn",
      "compound_cantonese": "faan6",
      "compound_definition": "cooked rice; meal; (loanword) fan; devotee",
      "": ""
    },
    {
      "id": 58,
      "character": "饭店",
      "character_pinyin": "fàndiàn",
      "eng": "restaurant",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "饭店",
      "compound_pinyin": "fàndiàn",
      "compound_cantonese": "faan6dim3",
      "compound_definition": "restaurant; hotel",
      "": ""
    },
    {
      "id": 59,
      "character": "店",
      "character_pinyin": "diàn",
      "eng": "inn",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "店",
      "compound_pinyin": "diàn",
      "compound_cantonese": "dim3",
      "compound_definition": "inn; shop; store",
      "": ""
    },
    {
      "id": 60,
      "character": "飞",
      "character_pinyin": "fēi",
      "eng": "to fly",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "飞",
      "compound_pinyin": "fēi",
      "compound_cantonese": "fei1",
      "compound_definition": "to fly",
      "": ""
    },
    {
      "id": 61,
      "character": "飞机",
      "character_pinyin": "fēijī",
      "eng": "airplane",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "飞机",
      "compound_pinyin": "fēijī",
      "compound_cantonese": "fei1gei1",
      "compound_definition": "airplane",
      "": ""
    },
    {
      "id": 62,
      "character": "分",
      "character_pinyin": "fēn",
      "eng": "to divide",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "分",
      "compound_pinyin": "fēn",
      "compound_cantonese": "fan1",
      "compound_definition": "to divide; to separate; to distribute; to allocate; to distinguish (good and bad); part or subdivision; fraction; one tenth (of certain units); unit of length equivalent to 0.33 cm; minute (unit of time); minute (angular measurement unit); a point (in sports or games); 0.01 yuan (unit of money)",
      "": ""
    },
    {
      "id": 63,
      "character": "分钟",
      "character_pinyin": "fēnzhōng",
      "eng": "minute",
      "hsk_level": 1,
      "part_of_speech": "(量) measure word",
      "compound": "分钟",
      "compound_pinyin": "fēnzhōng",
      "compound_cantonese": "fan1zung1",
      "compound_definition": "minute",
      "": ""
    },
    {
      "id": 64,
      "character": "狗",
      "character_pinyin": "gǒu",
      "eng": "dog",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "狗",
      "compound_pinyin": "gǒu",
      "compound_cantonese": "gau2",
      "compound_definition": "dog",
      "": ""
    },
    {
      "id": 65,
      "character": "汉语",
      "character_pinyin": "hànyǔ",
      "eng": "Chinese language",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "汉语",
      "compound_pinyin": "hànyǔ",
      "compound_cantonese": "hon3jyu5",
      "compound_definition": "Chinese language",
      "": ""
    },
    {
      "id": 66,
      "character": "后",
      "character_pinyin": "hòu",
      "eng": "back",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "后",
      "compound_pinyin": "hòu",
      "compound_cantonese": "hau6",
      "compound_definition": "back; behind; rear; afterwards; after; later; post-",
      "": ""
    },
    {
      "id": 67,
      "character": "后面",
      "character_pinyin": "hòumiàn, also pr. hòumian",
      "eng": "rear",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "后面",
      "compound_pinyin": "hòumiàn, also pr. hòumian",
      "compound_cantonese": "hau6min6",
      "compound_definition": "rear; back; behind; later; afterwards",
      "": ""
    },
    {
      "id": 68,
      "character": "家",
      "character_pinyin": "jiā",
      "eng": "home",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "家",
      "compound_pinyin": "jiā",
      "compound_cantonese": "gaa1",
      "compound_definition": "home; family; (polite) my (sister, uncle etc); measure word for families or businesses; refers to the philosophical schools of pre-Han China; noun suffix for a specialist in some activity, such as a musician or revolutionary, corresponding to English -ist, -er, -ary or -ian",
      "": ""
    },
    {
      "id": 69,
      "character": "今天",
      "character_pinyin": "jīntiān",
      "eng": "today",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "今天",
      "compound_pinyin": "jīntiān",
      "compound_cantonese": "gam1tin1",
      "compound_definition": "today; at the present; now",
      "": ""
    },
    {
      "id": 70,
      "character": "老",
      "character_pinyin": "lǎo",
      "eng": "prefix used before the surname of a person or a numeral indicating the order of birth of the children in a family or to indicate affection or familiarity",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "老",
      "compound_pinyin": "lǎo",
      "compound_cantonese": "lou5",
      "compound_definition": "prefix used before the surname of a person or a numeral indicating the order of birth of the children in a family or to indicate affection or familiarity; old (of people); venerable (person); experienced; of long standing; always; all the time; of the past; very; outdated; (of meat etc) tough",
      "": ""
    },
    {
      "id": 71,
      "character": "老师",
      "character_pinyin": "lǎoshī",
      "eng": "teacher",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "老师",
      "compound_pinyin": "lǎoshī",
      "compound_cantonese": "lou5si1",
      "compound_definition": "teacher",
      "": ""
    },
    {
      "id": 72,
      "character": "里",
      "character_pinyin": "lǐ",
      "eng": "li, ancient measure of length, approx. 500 m",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "里",
      "compound_pinyin": "lǐ",
      "compound_cantonese": "lei5",
      "compound_definition": "li, ancient measure of length, approx. 500 m; neighborhood; ancient administrative unit of 25 families; (Tw) borough, administrative unit between the township 镇 and neighborhood 邻 levels; Li (surname)",
      "": ""
    },
    {
      "id": 73,
      "character": "里面",
      "character_pinyin": "lǐmiàn, also pr. lǐmian",
      "eng": "inside",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "里面",
      "compound_pinyin": "lǐmiàn, also pr. lǐmian",
      "compound_cantonese": "leoi5min6",
      "compound_definition": "inside; interior",
      "": ""
    },
    {
      "id": 74,
      "character": "妈",
      "character_pinyin": "mā",
      "eng": "ma",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "妈",
      "compound_pinyin": "mā",
      "compound_cantonese": "maa1",
      "compound_definition": "ma; mom; mother",
      "": ""
    },
    {
      "id": 75,
      "character": "猫",
      "character_pinyin": "māo",
      "eng": "cat",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "猫",
      "compound_pinyin": "māo",
      "compound_cantonese": "maau1",
      "compound_definition": "cat; (dialect) to hide oneself; (coll.) modem",
      "": ""
    },
    {
      "id": 76,
      "character": "米饭",
      "character_pinyin": "mǐfàn",
      "eng": "(cooked) rice",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "米饭",
      "compound_pinyin": "mǐfàn",
      "compound_cantonese": "mai5faan6",
      "compound_definition": "(cooked) rice",
      "": ""
    },
    {
      "id": 77,
      "character": "明天",
      "character_pinyin": "míngtiān",
      "eng": "tomorrow",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "明天",
      "compound_pinyin": "míngtiān",
      "compound_cantonese": "ming4tin1",
      "compound_definition": "tomorrow",
      "": ""
    },
    {
      "id": 78,
      "character": "名字",
      "character_pinyin": "míngzi",
      "eng": "name (of a person or thing)",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "名字",
      "compound_pinyin": "míngzi",
      "compound_cantonese": "ming4zi6",
      "compound_definition": "name (of a person or thing)",
      "": ""
    },
    {
      "id": 79,
      "character": "年",
      "character_pinyin": "nián",
      "eng": "year",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "年",
      "compound_pinyin": "nián",
      "compound_cantonese": "nin4",
      "compound_definition": "year; (Chinese surname)",
      "": ""
    },
    {
      "id": 80,
      "character": "女",
      "character_pinyin": "nǚ",
      "eng": "female",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "女",
      "compound_pinyin": "nǚ",
      "compound_cantonese": "neoi5",
      "compound_definition": "female; woman; daughter",
      "": ""
    },
    {
      "id": 81,
      "character": "女儿",
      "character_pinyin": "nǚ'ér",
      "eng": "daughter",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "女儿",
      "compound_pinyin": "nǚ'ér",
      "compound_cantonese": "neoi5ji4",
      "compound_definition": "daughter",
      "": ""
    },
    {
      "id": 82,
      "character": "女人",
      "character_pinyin": "nǚrén",
      "eng": "woman",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "女人",
      "compound_pinyin": "nǚrén",
      "compound_cantonese": "neoi5jan4",
      "compound_definition": "woman",
      "": ""
    },
    {
      "id": 83,
      "character": "男",
      "character_pinyin": "nán",
      "eng": "male",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "男",
      "compound_pinyin": "nán",
      "compound_cantonese": "naam4",
      "compound_definition": "male; Baron, lowest of five orders of nobility 五等爵位",
      "": ""
    },
    {
      "id": 84,
      "character": "男人",
      "character_pinyin": "nánrén",
      "eng": "a man",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "男人",
      "compound_pinyin": "nánrén",
      "compound_cantonese": "naam4jan4",
      "compound_definition": "a man; a male; men",
      "": ""
    },
    {
      "id": 85,
      "character": "朋友",
      "character_pinyin": "péngyou",
      "eng": "friend",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "朋友",
      "compound_pinyin": "péngyou",
      "compound_cantonese": "pang4jau5",
      "compound_definition": "friend",
      "": ""
    },
    {
      "id": 86,
      "character": "水果",
      "character_pinyin": "shuǐguǒ",
      "eng": "fruit",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "水果",
      "compound_pinyin": "shuǐguǒ",
      "compound_cantonese": "seoi2gwo2",
      "compound_definition": "fruit",
      "": ""
    },
    {
      "id": 87,
      "character": "苹果",
      "character_pinyin": "píngguǒ",
      "eng": "apple",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "苹果",
      "compound_pinyin": "píngguǒ",
      "compound_cantonese": "ping4gwo2",
      "compound_definition": "apple",
      "": ""
    },
    {
      "id": 88,
      "character": "钱",
      "character_pinyin": "qián",
      "eng": "money",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "钱",
      "compound_pinyin": "qián",
      "compound_cantonese": "cin2",
      "compound_definition": "money; coin; unit of weight, one tenth of a tael 两; (Chinese surname)",
      "": ""
    },
    {
      "id": 89,
      "character": "前",
      "character_pinyin": "qián",
      "eng": "front",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "前",
      "compound_pinyin": "qián",
      "compound_cantonese": "cin4",
      "compound_definition": "front; forward; ahead; first; top (followed by a number); future; ago; before; BC (e.g. 前293年); former; formerly",
      "": ""
    },
    {
      "id": 90,
      "character": "前面",
      "character_pinyin": "qiánmiàn, also pr. qiánmian",
      "eng": "ahead",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "前面",
      "compound_pinyin": "qiánmiàn, also pr. qiánmian",
      "compound_cantonese": "cin4min6",
      "compound_definition": "ahead; in front; preceding; above",
      "": ""
    },
    {
      "id": 91,
      "character": "人",
      "character_pinyin": "rén",
      "eng": "person",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "人",
      "compound_pinyin": "rén",
      "compound_cantonese": "Jan4",
      "compound_definition": "person; people",
      "": ""
    },
    {
      "id": 92,
      "character": "上",
      "character_pinyin": "shàng",
      "eng": "on top",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "上",
      "compound_pinyin": "shàng",
      "compound_cantonese": "soeng6",
      "compound_definition": "on top; upon; above; upper; previous; first (of multiple parts)",
      "": ""
    },
    {
      "id": 93,
      "character": "商店",
      "character_pinyin": "shāngdiàn",
      "eng": "store",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "商店",
      "compound_pinyin": "shāngdiàn",
      "compound_cantonese": "soeng1dim3",
      "compound_definition": "store; shop",
      "": ""
    },
    {
      "id": 94,
      "character": "上午",
      "character_pinyin": "shàngwǔ",
      "eng": "morning",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "上午",
      "compound_pinyin": "shàngwǔ",
      "compound_cantonese": "soeng6ng5",
      "compound_definition": "morning",
      "": ""
    },
    {
      "id": 95,
      "character": "时间",
      "character_pinyin": "shíjiān",
      "eng": "time",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "时间",
      "compound_pinyin": "shíjiān",
      "compound_cantonese": "si4gaan3",
      "compound_definition": "time; period",
      "": ""
    },
    {
      "id": 96,
      "character": "书",
      "character_pinyin": "shū",
      "eng": "book",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "书",
      "compound_pinyin": "shū",
      "compound_cantonese": "syu1",
      "compound_definition": "book; letter; document; to write; abbr. for 书经",
      "": ""
    },
    {
      "id": 97,
      "character": "水",
      "character_pinyin": "shuǐ",
      "eng": "water",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "水",
      "compound_pinyin": "shuǐ",
      "compound_cantonese": "seoi2",
      "compound_definition": "water; river; liquid; beverage; additional charges or income; (of clothes) measure word for number of washes; (Chinese surname)",
      "": ""
    },
    {
      "id": 98,
      "character": "天",
      "character_pinyin": "tiān",
      "eng": "day",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "天",
      "compound_pinyin": "tiān",
      "compound_cantonese": "tin1",
      "compound_definition": "day; sky; heaven",
      "": ""
    },
    {
      "id": 99,
      "character": "天气",
      "character_pinyin": "tiānqì",
      "eng": "weather",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "天气",
      "compound_pinyin": "tiānqì",
      "compound_cantonese": "tin1hei3",
      "compound_definition": "weather",
      "": ""
    },
    {
      "id": 100,
      "character": "同学",
      "character_pinyin": "tóngxué",
      "eng": "to study at the same school",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "同学",
      "compound_pinyin": "tóngxué",
      "compound_cantonese": "tung4hok6",
      "compound_definition": "to study at the same school; fellow student; classmate",
      "": ""
    },
    {
      "id": 101,
      "character": "下",
      "character_pinyin": "xià",
      "eng": "down",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "下",
      "compound_pinyin": "xià",
      "compound_cantonese": "haa6",
      "compound_definition": "down; downwards; below; lower; later; next (week etc); second (of two parts); to decline; to go down; to arrive at (a decision, conclusion etc)",
      "": ""
    },
    {
      "id": 102,
      "character": "先",
      "character_pinyin": "xiān",
      "eng": "early",
      "hsk_level": 1,
      "part_of_speech": "(副) adverb",
      "compound": "先",
      "compound_pinyin": "xiān",
      "compound_cantonese": "sin1",
      "compound_definition": "early; prior; former; in advance; first",
      "": "s (possessive particle); (used after an attribute); (used to form a nominal expression); (used at the end of a declarative sentence for emphasis); also pr. [di4] or [di5] in poetry and songs"
    },
    {
      "id": 103,
      "character": "先生",
      "character_pinyin": "xiānsheng",
      "eng": "teacher",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "先生",
      "compound_pinyin": "xiānsheng",
      "compound_cantonese": "sin1saang1",
      "compound_definition": "teacher; husband; doctor (dialect); Mister (Mr.)",
      "": ""
    },
    {
      "id": 104,
      "character": "现在",
      "character_pinyin": "xiànzài",
      "eng": "now",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "现在",
      "compound_pinyin": "xiànzài",
      "compound_cantonese": "jin6zoi6",
      "compound_definition": "now; at present; at the moment; modern; current; nowadays",
      "": ""
    },
    {
      "id": 105,
      "character": "小姐",
      "character_pinyin": "xiǎojiě",
      "eng": "young lady",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "小姐",
      "compound_pinyin": "xiǎojiě",
      "compound_cantonese": "siu2ze2",
      "compound_definition": "young lady; miss; (slang) prostitute",
      "": ""
    },
    {
      "id": 106,
      "character": "下午",
      "character_pinyin": "xiàwǔ",
      "eng": "afternoon",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "下午",
      "compound_pinyin": "xiàwǔ",
      "compound_cantonese": "haa6ng5",
      "compound_definition": "afternoon; p.m.",
      "": ""
    },
    {
      "id": 107,
      "character": "星期",
      "character_pinyin": "xīngqī",
      "eng": "week",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "星期",
      "compound_pinyin": "xīngqī",
      "compound_cantonese": "sing1kei4",
      "compound_definition": "week; day of the week; Sunday",
      "": ""
    },
    {
      "id": 108,
      "character": "学",
      "character_pinyin": "xué",
      "eng": "to learn",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "学",
      "compound_pinyin": "xué",
      "compound_cantonese": "hok6",
      "compound_definition": "to learn; to study; to imitate; science; -ology",
      "": ""
    },
    {
      "id": 109,
      "character": "学生",
      "character_pinyin": "xuésheng, also pr. xuéshēng",
      "eng": "student",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "学生",
      "compound_pinyin": "xuésheng, also pr. xuéshēng",
      "compound_cantonese": "hok6saang1",
      "compound_definition": "student; schoolchild",
      "": ""
    },
    {
      "id": 110,
      "character": "学校",
      "character_pinyin": "xuéxiào",
      "eng": "school",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "学校",
      "compound_pinyin": "xuéxiào",
      "compound_cantonese": "hok6haau6",
      "compound_definition": "school",
      "": ""
    },
    {
      "id": 111,
      "character": "衣服",
      "character_pinyin": "yīfu",
      "eng": "clothes",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "衣服",
      "compound_pinyin": "yīfu",
      "compound_cantonese": "ji1fuk6",
      "compound_definition": "clothes",
      "": ""
    },
    {
      "id": 112,
      "character": "医生",
      "character_pinyin": "yīshēng",
      "eng": "doctor",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "医生",
      "compound_pinyin": "yīshēng",
      "compound_cantonese": "ji1sang1",
      "compound_definition": "doctor",
      "": ""
    },
    {
      "id": 113,
      "character": "医院",
      "character_pinyin": "yīyuàn",
      "eng": "hospital",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "医院",
      "compound_pinyin": "yīyuàn",
      "compound_cantonese": "ji1jyun2",
      "compound_definition": "hospital",
      "": ""
    },
    {
      "id": 114,
      "character": "椅子",
      "character_pinyin": "yǐzi",
      "eng": "chair",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "椅子",
      "compound_pinyin": "yǐzi",
      "compound_cantonese": "ji2zi2",
      "compound_definition": "chair",
      "": ""
    },
    {
      "id": 115,
      "character": "月",
      "character_pinyin": "yuè",
      "eng": "moon",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "月",
      "compound_pinyin": "yuè",
      "compound_cantonese": "jyut6",
      "compound_definition": "moon; month; monthly",
      "": ""
    },
    {
      "id": 116,
      "character": "中",
      "character_pinyin": "zhōng",
      "eng": "within",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "中",
      "compound_pinyin": "zhōng",
      "compound_cantonese": "zung1",
      "compound_definition": "within; among; in; middle; center; while (doing something); during; (dialect) OK; all right; China; Chinese; (Chinese surname)",
      "": ""
    },
    {
      "id": 117,
      "character": "中间",
      "character_pinyin": "zhōngjiān",
      "eng": "between",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "中间",
      "compound_pinyin": "zhōngjiān",
      "compound_cantonese": "zung1gaan1",
      "compound_definition": "between; intermediate; mid; middle",
      "": ""
    },
    {
      "id": 118,
      "character": "国",
      "character_pinyin": "guó",
      "eng": "country",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "国",
      "compound_pinyin": "guó",
      "compound_cantonese": "gwok3",
      "compound_definition": "country; nation; state; national; (Chinese surname)",
      "": ""
    },
    {
      "id": 119,
      "character": "中午",
      "character_pinyin": "zhōngwǔ",
      "eng": "noon",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "中午",
      "compound_pinyin": "zhōngwǔ",
      "compound_cantonese": "zung1ng5",
      "compound_definition": "noon; midday",
      "": ""
    },
    {
      "id": 120,
      "character": "桌子",
      "character_pinyin": "zhuōzi",
      "eng": "table",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "桌子",
      "compound_pinyin": "zhuōzi",
      "compound_cantonese": "coek3zi2",
      "compound_definition": "table; desk",
      "": ""
    },
    {
      "id": 121,
      "character": "字",
      "character_pinyin": "zì",
      "eng": "letter",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "字",
      "compound_pinyin": "zì",
      "compound_cantonese": "zi6",
      "compound_definition": "letter; symbol; character; word; courtesy or style name traditionally given to males aged 20 in dynastic China",
      "": ""
    },
    {
      "id": 122,
      "character": "昨天",
      "character_pinyin": "zuótiān",
      "eng": "yesterday",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "昨天",
      "compound_pinyin": "zuótiān",
      "compound_cantonese": "zok6tin1",
      "compound_definition": "yesterday",
      "": ""
    },
    {
      "id": 123,
      "character": "一",
      "character_pinyin": "yī, also pr. yāo",
      "eng": "one",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "一",
      "compound_pinyin": "yī, also pr. yāo",
      "compound_cantonese": "jat1",
      "compound_definition": "one; 1; single; a (article); as soon as; entire; whole; all; throughout; \"one\" radical in Chinese characters (Kangxi radical 1); also pr. [yao1] for greater clarity when spelling out numbers digit by digit",
      "": ""
    },
    {
      "id": 124,
      "character": "二",
      "character_pinyin": "èr",
      "eng": "two",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "二",
      "compound_pinyin": "èr",
      "compound_cantonese": "ji6",
      "compound_definition": "two; 2; (Beijing dialect) stupid",
      "": ""
    },
    {
      "id": 125,
      "character": "三",
      "character_pinyin": "sān",
      "eng": "three",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "三",
      "compound_pinyin": "sān",
      "compound_cantonese": "saam1",
      "compound_definition": "three; 3; (Chinese surname)",
      "": ""
    },
    {
      "id": 126,
      "character": "四",
      "character_pinyin": "sì",
      "eng": "four",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "四",
      "compound_pinyin": "sì",
      "compound_cantonese": "sei3",
      "compound_definition": "four; 4",
      "": ""
    },
    {
      "id": 127,
      "character": "五",
      "character_pinyin": "wǔ",
      "eng": "five",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "五",
      "compound_pinyin": "wǔ",
      "compound_cantonese": "ng5",
      "compound_definition": "five; 5",
      "": ""
    },
    {
      "id": 128,
      "character": "六",
      "character_pinyin": "liù",
      "eng": "six",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "六",
      "compound_pinyin": "liù",
      "compound_cantonese": "luk6",
      "compound_definition": "six; 6",
      "": ""
    },
    {
      "id": 129,
      "character": "七",
      "character_pinyin": "qī",
      "eng": "seven",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "七",
      "compound_pinyin": "qī",
      "compound_cantonese": "cat1",
      "compound_definition": "seven; 7",
      "": ""
    },
    {
      "id": 130,
      "character": "八",
      "character_pinyin": "bā",
      "eng": "eight",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "八",
      "compound_pinyin": "bā",
      "compound_cantonese": "baat3",
      "compound_definition": "eight; 8",
      "": ""
    },
    {
      "id": 131,
      "character": "九",
      "character_pinyin": "jiǔ",
      "eng": "nine",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "九",
      "compound_pinyin": "jiǔ",
      "compound_cantonese": "gau2",
      "compound_definition": "nine; 9",
      "": ""
    },
    {
      "id": 132,
      "character": "十",
      "character_pinyin": "shí",
      "eng": "ten",
      "hsk_level": 1,
      "part_of_speech": "(数) numeral",
      "compound": "十",
      "compound_pinyin": "shí",
      "compound_cantonese": "sap6",
      "compound_definition": "ten; 10",
      "": ""
    },
    {
      "id": 133,
      "character": "号",
      "character_pinyin": "hào",
      "eng": "ordinal number",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "号",
      "compound_pinyin": "hào",
      "compound_cantonese": "hou6",
      "compound_definition": "ordinal number; day of a month; mark; sign; business establishment; size; ship suffix; horn (wind instrument); bugle call; assumed name; to take a pulse; classifier used to indicate number of people",
      "": ""
    },
    {
      "id": 134,
      "character": "的",
      "character_pinyin": "de",
      "eng": "of",
      "hsk_level": 1,
      "part_of_speech": "(助) particle",
      "compound": "的",
      "compound_pinyin": "de",
      "compound_cantonese": "dik1",
      "compound_definition": "of;",
      "": ""
    },
    {
      "id": 135,
      "character": "了",
      "character_pinyin": "le",
      "eng": "(completed action marker)",
      "hsk_level": 1,
      "part_of_speech": "(助) particle",
      "compound": "了",
      "compound_pinyin": "le",
      "compound_cantonese": "liu5",
      "compound_definition": "(completed action marker); (modal particle indicating change of state, situation now); (modal particle intensifying preceding clause)",
      "": ""
    },
    {
      "id": 136,
      "character": "吗",
      "character_pinyin": "má, also pr. ma",
      "eng": "(question particle for \"yes-no\" questions)",
      "hsk_level": 1,
      "part_of_speech": "(疑问助) question particle",
      "compound": "吗",
      "compound_pinyin": "má, also pr. ma",
      "compound_cantonese": "maa3",
      "compound_definition": "(question particle for \"yes-no\" questions)",
      "": ""
    },
    {
      "id": 137,
      "character": "呢",
      "character_pinyin": "ne",
      "eng": "particle indicating that a previously asked question is to be applied to the preceding word (\"What about ...?\", \"And ...?\")",
      "hsk_level": 1,
      "part_of_speech": "(疑问助) question particle",
      "compound": "呢",
      "compound_pinyin": "ne",
      "compound_cantonese": "ne1",
      "compound_definition": "particle indicating that a previously asked question is to be applied to the preceding word (\"What about ...?\", \"And ...?\"); particle for inquiring about location (\"Where is ...?\"); particle signaling a pause, to emphasize the preceding words and allow the listener time to take them on board (\"ok?\", \"are you with me?\"); (at the end of a declarative sentence) particle indicating continuation of a state or action; particle indicating strong affirmation",
      "": ""
    },
    {
      "id": 138,
      "character": "你",
      "character_pinyin": "nǐ",
      "eng": "you (informal, as opposed to courteous 您)",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "你",
      "compound_pinyin": "nǐ",
      "compound_cantonese": "nei5",
      "compound_definition": "you (informal, as opposed to courteous 您)",
      "": ""
    },
    {
      "id": 139,
      "character": "他",
      "character_pinyin": "tā",
      "eng": "he or him",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "他",
      "compound_pinyin": "tā",
      "compound_cantonese": "taa1",
      "compound_definition": "he or him; (used for either sex when the sex is unknown or unimportant); (used before somebody's name for emphasis); (used as a meaningless mock object); other; another",
      "": ""
    },
    {
      "id": 140,
      "character": "她",
      "character_pinyin": "tā",
      "eng": "she",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "她",
      "compound_pinyin": "tā",
      "compound_cantonese": "taa1",
      "compound_definition": "she",
      "": ""
    },
    {
      "id": 141,
      "character": "我",
      "character_pinyin": "wǒ",
      "eng": "I",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "我",
      "compound_pinyin": "wǒ",
      "compound_cantonese": "ngo5",
      "compound_definition": "I; me; my",
      "": ""
    },
    {
      "id": 142,
      "character": "我们",
      "character_pinyin": "wǒmen",
      "eng": "we",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "我们",
      "compound_pinyin": "wǒmen",
      "compound_cantonese": "ngo5mun4",
      "compound_definition": "we; us; ourselves; our",
      "": ""
    },
    {
      "id": 143,
      "character": "你们",
      "character_pinyin": "nǐmen",
      "eng": "you (plural)",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "你们",
      "compound_pinyin": "nǐmen",
      "compound_cantonese": "nei5mun4",
      "compound_definition": "you (plural)",
      "": ""
    },
    {
      "id": 144,
      "character": "他们",
      "character_pinyin": "tāmen",
      "eng": "they",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "他们",
      "compound_pinyin": "tāmen",
      "compound_cantonese": "taa1mun4",
      "compound_definition": "they",
      "": ""
    },
    {
      "id": 145,
      "character": "她们",
      "character_pinyin": "tāmen",
      "eng": "they",
      "hsk_level": 1,
      "part_of_speech": "(代) pronoun",
      "compound": "她们",
      "compound_pinyin": "tāmen",
      "compound_cantonese": "taa1mun4",
      "compound_definition": "they; them (for females)",
      "": ""
    },
    {
      "id": 146,
      "character": "不客气",
      "character_pinyin": "bù kèqi, also pr. bù kèqì",
      "eng": "you're welcome",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "不客气",
      "compound_pinyin": "bù kèqi, also pr. bù kèqì",
      "compound_cantonese": "bat1 haak3hei3",
      "compound_definition": "you're welcome; don't mention it; impolite; rude; blunt",
      "": ""
    },
    {
      "id": 147,
      "character": "打电话",
      "character_pinyin": "dǎ diànhuà",
      "eng": "to make a telephone call",
      "hsk_level": 1,
      "part_of_speech": "(动宾式) verb object",
      "compound": "打电话",
      "compound_pinyin": "dǎ diànhuà",
      "compound_cantonese": "daa2 din6waa2",
      "compound_definition": "to make a telephone call",
      "": ""
    },
    {
      "id": 148,
      "character": "没关系",
      "character_pinyin": "méi guānxi",
      "eng": "it doesn't matter",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "没关系",
      "compound_pinyin": "méi guānxi",
      "compound_cantonese": "mut6 gwaan1hai6",
      "compound_definition": "it doesn't matter",
      "": ""
    },
    {
      "id": 149,
      "character": "在",
      "character_pinyin": "zài",
      "eng": "(located) at",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "在",
      "compound_pinyin": "zài",
      "compound_cantonese": "zoi6",
      "compound_definition": "(located) at; (to be) in; to exist; in the middle of doing something; (indicating an action in progress)",
      "": ""
    },
    {
      "id": 150,
      "character": "爱",
      "character_pinyin": "ài",
      "eng": "to love",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "爱",
      "compound_pinyin": "ài",
      "compound_cantonese": "oi3",
      "compound_definition": "to love; to be fond of; to like; affection; to be inclined (to do something); to tend to (happen)",
      "": ""
    },
    {
      "id": 151,
      "character": "吃",
      "character_pinyin": "chī",
      "eng": "to eat",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "吃",
      "compound_pinyin": "chī",
      "compound_cantonese": "hek3",
      "compound_definition": "to eat; to consume; to eat at (a cafeteria etc); to eradicate; to destroy; to absorb; to suffer; to stammer (Taiwan pr. for this sense is [ji2])",
      "": ""
    },
    {
      "id": 152,
      "character": "读",
      "character_pinyin": "dú",
      "eng": "to read",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "读",
      "compound_pinyin": "dú",
      "compound_cantonese": "duk6",
      "compound_definition": "to read; to study; reading of word (i.e. pronunciation), similar to 拼音",
      "": ""
    },
    {
      "id": 153,
      "character": "读书",
      "character_pinyin": "dúshū",
      "eng": "to read a book",
      "hsk_level": 1,
      "part_of_speech": "(动宾式) verb object",
      "compound": "读书",
      "compound_pinyin": "dúshū",
      "compound_cantonese": "duk6syu1",
      "compound_definition": "to read a book; to study; to attend school",
      "": ""
    },
    {
      "id": 154,
      "character": "对不起",
      "character_pinyin": "duì bu qǐ",
      "eng": "unworthy",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "对不起",
      "compound_pinyin": "duì bu qǐ",
      "compound_cantonese": "deoi3 bat1 hei2",
      "compound_definition": "unworthy; to let down; I'm sorry; excuse me; pardon me; if you please; sorry? (please repeat)",
      "": ""
    },
    {
      "id": 155,
      "character": "工作",
      "character_pinyin": "gōngzuò",
      "eng": "to work",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "工作",
      "compound_pinyin": "gōngzuò",
      "compound_cantonese": "gung1zok3",
      "compound_definition": "to work; (of a machine) to operate; job; work; task",
      "": ""
    },
    {
      "id": 156,
      "character": "喝",
      "character_pinyin": "hē",
      "eng": "to drink",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "喝",
      "compound_pinyin": "hē",
      "compound_cantonese": "hot3",
      "compound_definition": "to drink; variant of 嗬",
      "": ""
    },
    {
      "id": 157,
      "character": "回",
      "character_pinyin": "huí",
      "eng": "to go back",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "回",
      "compound_pinyin": "huí",
      "compound_cantonese": "wui4",
      "compound_definition": "to go back; to turn around; to return; to answer; Hui ethnic group (Chinese Muslims); time; measure word for acts of a play; section or chapter (of a classic book)",
      "": ""
    },
    {
      "id": 158,
      "character": "叫",
      "character_pinyin": "jiào",
      "eng": "to shout",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "叫",
      "compound_pinyin": "jiào",
      "compound_cantonese": "giu3",
      "compound_definition": "to shout; to call; to order; to ask; to be called; by (indicates agent in the passive mood)",
      "": ""
    },
    {
      "id": 159,
      "character": "开",
      "character_pinyin": "kāi",
      "eng": "to open",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "开",
      "compound_pinyin": "kāi",
      "compound_cantonese": "hoi1",
      "compound_definition": "to open; to start; to turn on; to boil; to write out (a prescription, check, invoice etc); to operate (a vehicle); carat (gold); abbr. for Kelvin, 开尔文; abbr. for 开本, book format",
      "": ""
    },
    {
      "id": 160,
      "character": "看",
      "character_pinyin": "kàn",
      "eng": "to see",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "看",
      "compound_pinyin": "kàn",
      "compound_cantonese": "hon3",
      "compound_definition": "to see; to look at; to read; to watch; to visit; to call on; to consider; to look after; to treat (an illness); to depend on; to feel (that); (after verb) to give it a try; Watch out! (for a danger)",
      "": ""
    },
    {
      "id": 161,
      "character": "看见",
      "character_pinyin": "kànjiàn",
      "eng": "to see",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "看见",
      "compound_pinyin": "kànjiàn",
      "compound_cantonese": "hon3gin3",
      "compound_definition": "to see; to catch sight of",
      "": ""
    },
    {
      "id": 162,
      "character": "买",
      "character_pinyin": "mǎi",
      "eng": "to buy",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "买",
      "compound_pinyin": "mǎi",
      "compound_cantonese": "maai5",
      "compound_definition": "to buy; to purchase",
      "": ""
    },
    {
      "id": 163,
      "character": "请",
      "character_pinyin": "qǐng",
      "eng": "to ask",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "请",
      "compound_pinyin": "qǐng",
      "compound_cantonese": "ceng2",
      "compound_definition": "to ask; to invite; please (do something); to treat (to a meal etc); to request",
      "": ""
    },
    {
      "id": 164,
      "character": "去",
      "character_pinyin": "qù",
      "eng": "to go",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "去",
      "compound_pinyin": "qù",
      "compound_cantonese": "heoi3",
      "compound_definition": "to go; to go to (a place); (of a time etc) last; just passed; to send; to remove; to get rid of; to reduce; to be apart from in space or time; to die (euphemism); to play (a part); (when used either before or after a verb) to go in order to do something; (after a verb of motion indicates movement away from the speaker); (used after certain verbs to indicate detachment or separation)",
      "": ""
    },
    {
      "id": 165,
      "character": "认识",
      "character_pinyin": "rènshi",
      "eng": "to know",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "认识",
      "compound_pinyin": "rènshi",
      "compound_cantonese": "jing6sik1",
      "compound_definition": "to know; to recognize; to be familiar with; to get acquainted with somebody; knowledge; understanding; awareness; cognition",
      "": ""
    },
    {
      "id": 166,
      "character": "是",
      "character_pinyin": "shì",
      "eng": "is",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "是",
      "compound_pinyin": "shì",
      "compound_cantonese": "si6",
      "compound_definition": "is; are; am; yes; to be",
      "": ""
    },
    {
      "id": 167,
      "character": "睡",
      "character_pinyin": "shuì",
      "eng": "to sleep",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "睡",
      "compound_pinyin": "shuì",
      "compound_cantonese": "seoi6",
      "compound_definition": "to sleep; to lie down",
      "": ""
    },
    {
      "id": 168,
      "character": "睡觉",
      "character_pinyin": "shuìjiào",
      "eng": "to go to bed",
      "hsk_level": 1,
      "part_of_speech": "(动宾式) verb object",
      "compound": "睡觉",
      "compound_pinyin": "shuìjiào",
      "compound_cantonese": "seoi6gaau3",
      "compound_definition": "to go to bed; to sleep",
      "": ""
    },
    {
      "id": 169,
      "character": "说",
      "character_pinyin": "shuō",
      "eng": "to speak",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "说",
      "compound_pinyin": "shuō",
      "compound_cantonese": "syut3",
      "compound_definition": "to speak; to say; to explain; to scold; to tell off; a theory (typically the last character in a compound, as in 日心说 heliocentric theory)",
      "": ""
    },
    {
      "id": 170,
      "character": "说话",
      "character_pinyin": "shuōhuà",
      "eng": "to speak",
      "hsk_level": 1,
      "part_of_speech": "(动宾式) verb object",
      "compound": "说话",
      "compound_pinyin": "shuōhuà",
      "compound_cantonese": "syut3waa6",
      "compound_definition": "to speak; to say; to talk; to gossip; to tell stories; talk; word",
      "": ""
    },
    {
      "id": 171,
      "character": "话",
      "character_pinyin": "huà",
      "eng": "dialect",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "话",
      "compound_pinyin": "huà",
      "compound_cantonese": "waa6",
      "compound_definition": "dialect; language; spoken words; speech; talk; words; conversation; what somebody said",
      "": ""
    },
    {
      "id": 172,
      "character": "听",
      "character_pinyin": "tīng",
      "eng": "to listen",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "听",
      "compound_pinyin": "tīng",
      "compound_cantonese": "teng1",
      "compound_definition": "to listen; to hear; to obey; a can (loanword from English \"tin\"); measure word for canned beverages",
      "": ""
    },
    {
      "id": 173,
      "character": "雨",
      "character_pinyin": "yǔ",
      "eng": "rain",
      "hsk_level": 1,
      "part_of_speech": "(名) noun",
      "compound": "雨",
      "compound_pinyin": "yǔ",
      "compound_cantonese": "jyu5",
      "compound_definition": "rain",
      "": ""
    },
    {
      "id": 174,
      "character": "下雨",
      "character_pinyin": "xiàyǔ",
      "eng": "to rain",
      "hsk_level": 1,
      "part_of_speech": "(动宾式) verb object",
      "compound": "下雨",
      "compound_pinyin": "xiàyǔ",
      "compound_cantonese": "haa6jyu5",
      "compound_definition": "to rain",
      "": ""
    },
    {
      "id": 175,
      "character": "写",
      "character_pinyin": "xiě",
      "eng": "to write",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "写",
      "compound_pinyin": "xiě",
      "compound_cantonese": "se2",
      "compound_definition": "to write",
      "": ""
    },
    {
      "id": 176,
      "character": "谢谢",
      "character_pinyin": "xièxie",
      "eng": "to thank",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "谢谢",
      "compound_pinyin": "xièxie",
      "compound_cantonese": "ze6ze6",
      "compound_definition": "to thank; thanks; thank you",
      "": ""
    },
    {
      "id": 177,
      "character": "喜欢",
      "character_pinyin": "xǐhuan",
      "eng": "to like",
      "hsk_level": 1,
      "part_of_speech": "(形) adjective",
      "compound": "喜欢",
      "compound_pinyin": "xǐhuan",
      "compound_cantonese": "hei2fun1",
      "compound_definition": "to like; to be fond of",
      "": ""
    },
    {
      "id": 178,
      "character": "学习",
      "character_pinyin": "xuéxí",
      "eng": "to learn",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "学习",
      "compound_pinyin": "xuéxí",
      "compound_cantonese": "hok6zaap6",
      "compound_definition": "to learn; to study",
      "": ""
    },
    {
      "id": 179,
      "character": "有",
      "character_pinyin": "yǒu",
      "eng": "to have",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "有",
      "compound_pinyin": "yǒu",
      "compound_cantonese": "jau5",
      "compound_definition": "to have; there is; there are; to exist; to be",
      "": ""
    },
    {
      "id": 180,
      "character": "再",
      "character_pinyin": "zài",
      "eng": "again",
      "hsk_level": 1,
      "part_of_speech": "(副) adverb",
      "compound": "再",
      "compound_pinyin": "zài",
      "compound_cantonese": "zoi3",
      "compound_definition": "again; once more; re-; second; another; then (after something, and not until then); no matter how ... (followed by an adjective or verb, and then (usually) 也 or 都 for emphasis)",
      "": ""
    },
    {
      "id": 181,
      "character": "再见",
      "character_pinyin": "zàijiàn",
      "eng": "goodbye",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "再见",
      "compound_pinyin": "zàijiàn",
      "compound_cantonese": "zoi3gin3",
      "compound_definition": "goodbye; see you again later",
      "": ""
    },
    {
      "id": 182,
      "character": "住",
      "character_pinyin": "zhù",
      "eng": "to live",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "住",
      "compound_pinyin": "zhù",
      "compound_cantonese": "zyu6",
      "compound_definition": "to live; to dwell; to stay; to reside; to stop; (suffix indicating firmness, steadiness, or coming to a halt)",
      "": ""
    },
    {
      "id": 183,
      "character": "做",
      "character_pinyin": "zuò",
      "eng": "to do",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "做",
      "compound_pinyin": "zuò",
      "compound_cantonese": "zou6",
      "compound_definition": "to do; to make; to produce; to write; to compose; to act as; to engage in; to hold (a party); to be; to become; to function (in some capacity); to serve as; to be used for; to form (a bond or relationship); to pretend; to feign; to act a part; to put on appearance",
      "": ""
    },
    {
      "id": 184,
      "character": "坐",
      "character_pinyin": "zuò",
      "eng": "to sit",
      "hsk_level": 1,
      "part_of_speech": "(动) verb",
      "compound": "坐",
      "compound_pinyin": "zuò",
      "compound_cantonese": "co5",
      "compound_definition": "to sit; to take a seat; to take (a bus, airplane etc); to bear fruit; variant of 座; (Chinese surname)",
      "": ""
    }
  ];